#!/usr/bin/env bash
# Regenerate every file the gauntlet benchmarks from its source, with the
# compiler at HEAD. One line per file: target, source, -name, output.
#
# The gauntlet benchmarks committed copies of generated code, and until
# gauntlet-2026-09-29 they were regenerated by hand, from commands recorded in
# the results that first wrote them, if at all: most were last written on
# 2026-08-20, by the term backends the IR later replaced. This is the one list.
#
# A source whose first line says "BUILT WITH `-checked`" is compiled with it,
# the rule cmd/check's sweep uses. The JSON programs are written against Go's
# names; their JavaScript and Java versions substitute the host prefix, the
# derivation jsontok-2026-08-26 §6 recorded.
#
#   bash gauntlet/regen.sh           # write into the gauntlet
#   bash gauntlet/regen.sh DIR       # write under DIR instead, to compare
set -euo pipefail
cd "$(dirname "$0")/.."
out=${1:-.}
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT
go build -o "$tmp/gen" ./cmd/gen

ported() { # ported SRC HOST: SRC with Go's host prefix replaced by HOST's
	local f="$tmp/$(basename "$1" .oro)-$2.oro"
	sed -e "s/(use go)/(use $2)/" -e "s/go[.]/$2./g" "$1" >"$f"
	echo "$f"
}

while read -r target src name dst; do
	[ -z "$target" ] || [ "${target#\#}" != "$target" ] && continue
	case "$src" in
	js:*) src=$(ported "${src#js:}" js) ;;
	java:*) src=$(ported "${src#java:}" java) ;;
	esac
	flags=()
	head -1 "$src" | grep -q 'BUILT WITH `-checked`' && flags+=(-checked)
	mkdir -p "$(dirname "$out/$dst")"
	"$tmp/gen" "${flags[@]}" -name "$name" "$src" "$target" "$out/$dst" >/dev/null
	echo "$dst"
done <<'EOF'
# Go
go   examples/native/dot-go.oro        native      gauntlet/go/gen_dot_native.go
go   examples/native/centroid-go.oro   native      gauntlet/go/gen_centroid_native.go
go   examples/native/generic-go.oro    native      gauntlet/go/gen_generic_native.go
go   examples/native/wordcount-go.oro  native      gauntlet/go/gen_wordcount_native.go
go   examples/native/report-go.oro     gen         gauntlet/go/gen_report_native.go
go   examples/native/smooth-go.oro     native      gauntlet/go/gen_smooth_native.go
go   examples/native/search-go.oro     native      gauntlet/go/gen_search_native.go
go   examples/json/tokenize.oro        gen         gauntlet/go/gen_jsontok.go
go   examples/json/tree.oro            tree        gauntlet/go/gen_jsontree.go
# JavaScript
js   examples/native/dot-js.oro        native      gauntlet/js/gen_dot_native.mjs
js   examples/native/centroid-js.oro   native      gauntlet/js/gen_centroid_native.mjs
js   examples/native/generic-js.oro    native      gauntlet/js/gen_generic_native.mjs
js   examples/native/wordcount-js.oro  native      gauntlet/js/gen_wordcount_native.mjs
js   examples/native/smooth-js.oro     native      gauntlet/js/gen_smooth_native.mjs
js   examples/native/search-js.oro     native      gauntlet/js/gen_search_native.mjs
js   js:examples/json/tokenize.oro     native      gauntlet/js/gen_jsontok_native.mjs
js   js:examples/json/tree.oro         native      gauntlet/js/gen_jsontree_native.mjs
# Java
java examples/native/dot-java.oro      nat-dot     gauntlet/java/gen/NatDot.java
java examples/native/centroid-java.oro nat-centroid gauntlet/java/gen/NatCentroid.java
java examples/native/generic-java.oro  nat-gen     gauntlet/java/gen/NatGen.java
java examples/native/wordcount-java.oro nat-wc     gauntlet/java/gen/NatWc.java
java examples/native/report-java.oro   nat-rep     gauntlet/java/gen/NatRep.java
java examples/native/smooth-java.oro   nat-sm      gauntlet/java/gen/NatSm.java
java examples/native/search-java.oro   nat-search  gauntlet/java/gen/NatSearch.java
java java:examples/json/tokenize.oro   gen         gauntlet/java/gen/GenJsonTok.java
java java:examples/json/tree.oro       gen         gauntlet/java/gen/GenJsonTree.java
EOF
