// Code generated by oroboros. DO NOT EDIT.

package gauntlet

func GenFactLimbs(n int) []int32 {
	b := make([]int32, 55)
	b2 := b
	var i2 int = 0
	var r int = 1
	for ; ; i2, r = (i2 + 1), (r / 16777216) {
		if (i2 >= 55) {
			break
		}
		b2[i2] = int32((r % 16777216))
		continue
	}
	acc := b2
	var i int = 2
	sp1 := make([]int32, 55)
	for ; ; i = (i + 1) {
		if (i > n) {
			break
		}
		clear(sp1)
		o := sp1
		o2 := o
		var i3 int = 0
		var c int = 0
		for ; ; i3 = (i3 + 1) {
			if (i3 >= 55) {
				var i4 int = 54
				var t2 int
				if (i4 < 0) {
					t2 = 0
				} else {
					var t3 int
					if (i4 >= len(o2)) {
						t3 = 0
					} else {
						t3 = int(o2[i4])
					}
					t2 = t3
				}
				var t4 int
				if ((t2 % 16777216) < 32) {
					t4 = 0
				} else {
					t4 = 1
				}
				if ((func(oroC int) int { if oroC != 0 { panic("bignum overflow: the declared range is too small") }; return 0 }((c + t4))) == 0) {
					break
				}
				break
			}
			var t5 int
			if (i3 < 0) {
				t5 = 0
			} else {
				var t6 int
				if (i3 >= len(acc)) {
					t6 = 0
				} else {
					t6 = int(acc[i3])
				}
				t5 = t6
			}
			var t int = (((t5 % 16777216) * i) + c)
			o2[i3] = int32((t % 16777216))
			c = (t / 16777216)
			continue
		}
		acc, sp1 = o2, acc
		continue
	}
	return acc
}

