// Code generated by oroboros. DO NOT EDIT.

package gauntlet

import "fmt"

func GenMain() float64 {
	v2 := make([]float64, 1000)
	var v1 []float64
	v5 := v2
	var v6 int = 0
	for ; ; v6 = (v6 + 1) {
		v8 := (v6 >= 1000)
		if v8 {
			break
		}
		v11 := (float64(v6))
		v5[v6] = v11
		continue
	}
	v1 = v5
	fmt.Println("report")
	v17 := len(v1)
	fmt.Println(v17)
	var v22 float64 = 0.0
	var v23 int = 0
	for ; ; v23 = (v23 + 1) {
		v24 := len(v1)
		v25 := (v23 >= v24)
		if v25 {
			break
		}
		v30 := v1[v23]
		v31 := v1[v23]
		v32 := (v30 * v31)
		v33 := (v22 + v32)
		v22 = v33
		continue
	}
	fmt.Println(v22)
	return v22
}

