// Code generated by oroboros. DO NOT EDIT.

package gauntlet

import "fmt"

func CheckedCountPrimes(n int) int {
	c := (make([]bool, n))
	var i int = 2
	for {
		if ((func(a, b int) int { t := a * b; if a != 0 && t/a != b { panic("int overflow") }; return t }(i, i)) >= n) {
			break
		}
		if (c[i]) {
			i = (func(a, b int) int { t := a + b; if (t > a) != (b > 0) { panic("int overflow") }; return t }(i, 1))
			continue
		}
		var j int = (func(a, b int) int { t := a * b; if a != 0 && t/a != b { panic("int overflow") }; return t }(i, i))
		for {
			if (j < n) {
				c[j] = true
				j = (func(a, b int) int { t := a + b; if (t > a) != (b > 0) { panic("int overflow") }; return t }(j, i))
				continue
			}
			break
		}
		i = (func(a, b int) int { t := a + b; if (t > a) != (b > 0) { panic("int overflow") }; return t }(i, 1))
		continue
	}
	c2 := c
	var acc int = 0
	var k int = 2
	for {
		if (k >= n) {
			break
		}
		if (c2[k]) {
			k = (func(a, b int) int { t := a + b; if (t > a) != (b > 0) { panic("int overflow") }; return t }(k, 1))
			continue
		}
		acc, k = (func(a, b int) int { t := a + b; if (t > a) != (b > 0) { panic("int overflow") }; return t }(acc, 1)), (func(a, b int) int { t := a + b; if (t > a) != (b > 0) { panic("int overflow") }; return t }(k, 1))
		continue
	}
	return acc
}

func CheckedMain() int {
	c := (make([]bool, 20000))
	var i int = 2
	for {
		if ((i * i) >= 20000) {
			break
		}
		if (c[i]) {
			i = (i + 1)
			continue
		}
		var j int = (i * i)
		for {
			if (j < 20000) {
				c[j] = true
				j = (j + i)
				continue
			}
			break
		}
		i = (i + 1)
		continue
	}
	c2 := c
	var acc int = 0
	var k int = 2
	for {
		if (k >= 20000) {
			break
		}
		if (c2[k]) {
			k = (k + 1)
			continue
		}
		acc, k = (acc + 1), (k + 1)
		continue
	}
	fmt.Println(acc)
	return acc
}

