// Code generated by oroboros. DO NOT EDIT.

package gauntlet

import "strings"

func NativeTally(text string) map[string]int {
	ws := (strings.Fields(text))
	m := (make(map[string]int))
	var i int = 0
	for {
		if (i >= (len(ws))) {
			break
		}
		w := (ws[i])
		m[w] = ((m[w]) + 1)
		i = (i + 1)
		continue
	}
	return m
}

func NativeTallyInc(text string) map[string]int {
	ws := (strings.Fields(text))
	m := (make(map[string]int))
	var i int = 0
	for {
		if (i >= (len(ws))) {
			break
		}
		m[(ws[i])]++
		i = (i + 1)
		continue
	}
	return m
}

