// Code generated by oroboros. DO NOT EDIT.

package gauntlet

func GenMacFresh(a []byte, b []byte) []int {
	w := make([]int, 65536)
	w2 := w
	var i int = 0
	var n1 int = 65536
	s2 := a[:n1]
	s3 := b[:n1]
	for ; ; i = (i + 1) {
		if (i >= 65536) {
			break
		}
		w2[i] = (int(s2[i]) * int(s3[i]))
		continue
	}
	return w2
}

func GenMacInto(w []int, a []byte, b []byte) []int {
	w2 := w
	var i int = 0
	var n1 int = 65536
	s2 := a[:n1]
	s3 := b[:n1]
	for ; ; i = (i + 1) {
		if (i >= 65536) {
			break
		}
		w2[i] = (int(s2[i]) * int(s3[i]))
		continue
	}
	return w2
}

