// Code generated by oroboros. DO NOT EDIT.

package gauntlet

import "math/big"

func GenBoundedFactLimbs(n int) *big.Int {
	acc := (big.NewInt(int64(1)))
	var i int = 2
	for ; ; i = (i + 1) {
		if (i > n) {
			break
		}
		acc = (func(oroZ *big.Int, oroK int) *big.Int { if oroZ.BitLen() > oroK { panic("bignum overflow: the declared range is too small") }; return oroZ }((acc.Mul(acc, (big.NewInt(int64(i))))), 1301))
		continue
	}
	return acc
}

