// Code generated by oroboros. DO NOT EDIT.

package gauntlet

func GenRun(k int) int {
	var t1 int
	if (k == 0) {
		src := []int{123, 34, 97, 34, 58, 91, 49, 44, 50, 93, 44, 34, 98, 34, 58, 116, 114, 117, 101, 125}
		stk := make([]byte, 32)
		stk2 := stk
		var i int = 0
		var nt int = 0
		var sp int = 0
		var mx int = 0
		var ok int = 1
		var r2 int
		for {
			if (i < 0) {
				r2 = 0
				break
			}
			if (i >= len(src)) {
				var t3 int
				if (sp == 0) {
					t3 = ok
				} else {
					t3 = 0
				}
				r2 = ((nt * 1000) + ((mx * 10) + t3))
				break
			}
			if (sp >= 32) {
				r2 = (nt * 1000)
				break
			}
			var c int = src[i]
			if ((c == 32) || ((c == 9) || ((c == 10) || (c == 13)))) {
				i = (i + 1)
				continue
			}
			var c2 int = src[i]
			if ((c2 == 123) || (c2 == 91)) {
				var t4 int
				if (src[i] == 123) {
					t4 = 125
				} else {
					t4 = 93
				}
				stk2[sp] = byte(t4)
				var t5 int
				if ((sp + 1) > mx) {
					t5 = (sp + 1)
				} else {
					t5 = mx
				}
				i, nt, sp, mx = (i + 1), (nt + 1), (sp + 1), t5
				continue
			}
			var c3 int = src[i]
			if ((c3 == 125) || (c3 == 93)) {
				var t6 int
				if (sp < 1) {
					t6 = 0
				} else {
					t6 = (sp - 1)
				}
				var t7 int
				if (sp < 1) {
					t7 = 0
				} else {
					var t8 int
					if (sp < 1) {
						t8 = 0
					} else {
						t8 = (sp - 1)
					}
					var t9 int
					if (int(stk2[t8]) == src[i]) {
						t9 = ok
					} else {
						t9 = 0
					}
					t7 = t9
				}
				i, nt, sp, ok = (i + 1), (nt + 1), t6, t7
				continue
			}
			var c4 int = src[i]
			if ((c4 == 58) || (c4 == 44)) {
				i, nt = (i + 1), (nt + 1)
				continue
			}
			if (src[i] == 34) {
				var j int = (i + 1)
				var r10 int
				for {
					if (j < 0) {
						r10 = j
						break
					}
					if (j >= len(src)) {
						r10 = j
						break
					}
					if (src[j] == 92) {
						j = (j + 2)
						continue
					}
					if (src[j] == 34) {
						r10 = (j + 1)
						break
					}
					j = (j + 1)
					continue
				}
				i, nt = r10, (nt + 1)
				continue
			}
			var c5 int = src[i]
			if (((c5 >= 48) && (c5 <= 57)) || ((c5 == 45) || ((c5 == 43) || ((c5 == 46) || ((c5 == 101) || (c5 == 69)))))) {
				var j2 int = (i + 1)
				for ; ; j2 = (j2 + 1) {
					if (j2 < 0) {
						break
					}
					if (j2 >= len(src)) {
						break
					}
					var c6 int = src[j2]
					if (((c6 >= 48) && (c6 <= 57)) || ((c6 == 45) || ((c6 == 43) || ((c6 == 46) || ((c6 == 101) || (c6 == 69)))))) {
						continue
					}
					break
				}
				i, nt = j2, (nt + 1)
				continue
			}
			var c7 int = src[i]
			if ((c7 >= 97) && (c7 <= 122)) {
				var j3 int = (i + 1)
				for ; ; j3 = (j3 + 1) {
					if (j3 < 0) {
						break
					}
					if (j3 >= len(src)) {
						break
					}
					var c8 int = src[j3]
					if ((c8 >= 97) && (c8 <= 122)) {
						continue
					}
					break
				}
				i, nt = j3, (nt + 1)
				continue
			}
			i, ok = (i + 1), 0
			continue
		}
		t1 = r2
	} else {
		var t11 int
		if (k == 1) {
			src2 := []int{91, 91, 91, 49, 93, 93, 93}
			stk3 := make([]byte, 32)
			stk4 := stk3
			var i2 int = 0
			var nt2 int = 0
			var sp2 int = 0
			var mx2 int = 0
			var ok2 int = 1
			var r12 int
			for {
				if (i2 < 0) {
					r12 = 0
					break
				}
				if (i2 >= len(src2)) {
					var t13 int
					if (sp2 == 0) {
						t13 = ok2
					} else {
						t13 = 0
					}
					r12 = ((nt2 * 1000) + ((mx2 * 10) + t13))
					break
				}
				if (sp2 >= 32) {
					r12 = (nt2 * 1000)
					break
				}
				var c9 int = src2[i2]
				if ((c9 == 32) || ((c9 == 9) || ((c9 == 10) || (c9 == 13)))) {
					i2 = (i2 + 1)
					continue
				}
				var c10 int = src2[i2]
				if ((c10 == 123) || (c10 == 91)) {
					var t14 int
					if (src2[i2] == 123) {
						t14 = 125
					} else {
						t14 = 93
					}
					stk4[sp2] = byte(t14)
					var t15 int
					if ((sp2 + 1) > mx2) {
						t15 = (sp2 + 1)
					} else {
						t15 = mx2
					}
					i2, nt2, sp2, mx2 = (i2 + 1), (nt2 + 1), (sp2 + 1), t15
					continue
				}
				var c11 int = src2[i2]
				if ((c11 == 125) || (c11 == 93)) {
					var t16 int
					if (sp2 < 1) {
						t16 = 0
					} else {
						t16 = (sp2 - 1)
					}
					var t17 int
					if (sp2 < 1) {
						t17 = 0
					} else {
						var t18 int
						if (sp2 < 1) {
							t18 = 0
						} else {
							t18 = (sp2 - 1)
						}
						var t19 int
						if (int(stk4[t18]) == src2[i2]) {
							t19 = ok2
						} else {
							t19 = 0
						}
						t17 = t19
					}
					i2, nt2, sp2, ok2 = (i2 + 1), (nt2 + 1), t16, t17
					continue
				}
				var c12 int = src2[i2]
				if ((c12 == 58) || (c12 == 44)) {
					i2, nt2 = (i2 + 1), (nt2 + 1)
					continue
				}
				if (src2[i2] == 34) {
					var j4 int = (i2 + 1)
					var r20 int
					for {
						if (j4 < 0) {
							r20 = j4
							break
						}
						if (j4 >= len(src2)) {
							r20 = j4
							break
						}
						if (src2[j4] == 92) {
							j4 = (j4 + 2)
							continue
						}
						if (src2[j4] == 34) {
							r20 = (j4 + 1)
							break
						}
						j4 = (j4 + 1)
						continue
					}
					i2, nt2 = r20, (nt2 + 1)
					continue
				}
				var c13 int = src2[i2]
				if (((c13 >= 48) && (c13 <= 57)) || ((c13 == 45) || ((c13 == 43) || ((c13 == 46) || ((c13 == 101) || (c13 == 69)))))) {
					var j5 int = (i2 + 1)
					for ; ; j5 = (j5 + 1) {
						if (j5 < 0) {
							break
						}
						if (j5 >= len(src2)) {
							break
						}
						var c14 int = src2[j5]
						if (((c14 >= 48) && (c14 <= 57)) || ((c14 == 45) || ((c14 == 43) || ((c14 == 46) || ((c14 == 101) || (c14 == 69)))))) {
							continue
						}
						break
					}
					i2, nt2 = j5, (nt2 + 1)
					continue
				}
				var c15 int = src2[i2]
				if ((c15 >= 97) && (c15 <= 122)) {
					var j6 int = (i2 + 1)
					for ; ; j6 = (j6 + 1) {
						if (j6 < 0) {
							break
						}
						if (j6 >= len(src2)) {
							break
						}
						var c16 int = src2[j6]
						if ((c16 >= 97) && (c16 <= 122)) {
							continue
						}
						break
					}
					i2, nt2 = j6, (nt2 + 1)
					continue
				}
				i2, ok2 = (i2 + 1), 0
				continue
			}
			t11 = r12
		} else {
			var t21 int
			if (k == 2) {
				src3 := []int{123, 34, 97, 34, 58, 49}
				stk5 := make([]byte, 32)
				stk6 := stk5
				var i3 int = 0
				var nt3 int = 0
				var sp3 int = 0
				var mx3 int = 0
				var ok3 int = 1
				var r22 int
				for {
					if (i3 < 0) {
						r22 = 0
						break
					}
					if (i3 >= len(src3)) {
						var t23 int
						if (sp3 == 0) {
							t23 = ok3
						} else {
							t23 = 0
						}
						r22 = ((nt3 * 1000) + ((mx3 * 10) + t23))
						break
					}
					if (sp3 >= 32) {
						r22 = (nt3 * 1000)
						break
					}
					var c17 int = src3[i3]
					if ((c17 == 32) || ((c17 == 9) || ((c17 == 10) || (c17 == 13)))) {
						i3 = (i3 + 1)
						continue
					}
					var c18 int = src3[i3]
					if ((c18 == 123) || (c18 == 91)) {
						var t24 int
						if (src3[i3] == 123) {
							t24 = 125
						} else {
							t24 = 93
						}
						stk6[sp3] = byte(t24)
						var t25 int
						if ((sp3 + 1) > mx3) {
							t25 = (sp3 + 1)
						} else {
							t25 = mx3
						}
						i3, nt3, sp3, mx3 = (i3 + 1), (nt3 + 1), (sp3 + 1), t25
						continue
					}
					var c19 int = src3[i3]
					if ((c19 == 125) || (c19 == 93)) {
						var t26 int
						if (sp3 < 1) {
							t26 = 0
						} else {
							t26 = (sp3 - 1)
						}
						var t27 int
						if (sp3 < 1) {
							t27 = 0
						} else {
							var t28 int
							if (sp3 < 1) {
								t28 = 0
							} else {
								t28 = (sp3 - 1)
							}
							var t29 int
							if (int(stk6[t28]) == src3[i3]) {
								t29 = ok3
							} else {
								t29 = 0
							}
							t27 = t29
						}
						i3, nt3, sp3, ok3 = (i3 + 1), (nt3 + 1), t26, t27
						continue
					}
					var c20 int = src3[i3]
					if ((c20 == 58) || (c20 == 44)) {
						i3, nt3 = (i3 + 1), (nt3 + 1)
						continue
					}
					if (src3[i3] == 34) {
						var j7 int = (i3 + 1)
						var r30 int
						for {
							if (j7 < 0) {
								r30 = j7
								break
							}
							if (j7 >= len(src3)) {
								r30 = j7
								break
							}
							if (src3[j7] == 92) {
								j7 = (j7 + 2)
								continue
							}
							if (src3[j7] == 34) {
								r30 = (j7 + 1)
								break
							}
							j7 = (j7 + 1)
							continue
						}
						i3, nt3 = r30, (nt3 + 1)
						continue
					}
					var c21 int = src3[i3]
					if (((c21 >= 48) && (c21 <= 57)) || ((c21 == 45) || ((c21 == 43) || ((c21 == 46) || ((c21 == 101) || (c21 == 69)))))) {
						var j8 int = (i3 + 1)
						for ; ; j8 = (j8 + 1) {
							if (j8 < 0) {
								break
							}
							if (j8 >= len(src3)) {
								break
							}
							var c22 int = src3[j8]
							if (((c22 >= 48) && (c22 <= 57)) || ((c22 == 45) || ((c22 == 43) || ((c22 == 46) || ((c22 == 101) || (c22 == 69)))))) {
								continue
							}
							break
						}
						i3, nt3 = j8, (nt3 + 1)
						continue
					}
					var c23 int = src3[i3]
					if ((c23 >= 97) && (c23 <= 122)) {
						var j9 int = (i3 + 1)
						for ; ; j9 = (j9 + 1) {
							if (j9 < 0) {
								break
							}
							if (j9 >= len(src3)) {
								break
							}
							var c24 int = src3[j9]
							if ((c24 >= 97) && (c24 <= 122)) {
								continue
							}
							break
						}
						i3, nt3 = j9, (nt3 + 1)
						continue
					}
					i3, ok3 = (i3 + 1), 0
					continue
				}
				t21 = r22
			} else {
				src4 := []int{93}
				stk7 := make([]byte, 32)
				stk8 := stk7
				var i4 int = 0
				var nt4 int = 0
				var sp4 int = 0
				var mx4 int = 0
				var ok4 int = 1
				var r31 int
				for {
					if (i4 < 0) {
						r31 = 0
						break
					}
					if (i4 >= len(src4)) {
						var t32 int
						if (sp4 == 0) {
							t32 = ok4
						} else {
							t32 = 0
						}
						r31 = ((nt4 * 1000) + ((mx4 * 10) + t32))
						break
					}
					if (sp4 >= 32) {
						r31 = (nt4 * 1000)
						break
					}
					var c25 int = src4[i4]
					if ((c25 == 32) || ((c25 == 9) || ((c25 == 10) || (c25 == 13)))) {
						i4 = (i4 + 1)
						continue
					}
					var c26 int = src4[i4]
					if ((c26 == 123) || (c26 == 91)) {
						var t33 int
						if (src4[i4] == 123) {
							t33 = 125
						} else {
							t33 = 93
						}
						stk8[sp4] = byte(t33)
						var t34 int
						if ((sp4 + 1) > mx4) {
							t34 = (sp4 + 1)
						} else {
							t34 = mx4
						}
						i4, nt4, sp4, mx4 = (i4 + 1), (nt4 + 1), (sp4 + 1), t34
						continue
					}
					var c27 int = src4[i4]
					if ((c27 == 125) || (c27 == 93)) {
						var t35 int
						if (sp4 < 1) {
							t35 = 0
						} else {
							t35 = (sp4 - 1)
						}
						var t36 int
						if (sp4 < 1) {
							t36 = 0
						} else {
							var t37 int
							if (sp4 < 1) {
								t37 = 0
							} else {
								t37 = (sp4 - 1)
							}
							var t38 int
							if (int(stk8[t37]) == src4[i4]) {
								t38 = ok4
							} else {
								t38 = 0
							}
							t36 = t38
						}
						i4, nt4, sp4, ok4 = (i4 + 1), (nt4 + 1), t35, t36
						continue
					}
					var c28 int = src4[i4]
					if ((c28 == 58) || (c28 == 44)) {
						i4, nt4 = (i4 + 1), (nt4 + 1)
						continue
					}
					if (src4[i4] == 34) {
						var j10 int = (i4 + 1)
						var r39 int
						for {
							if (j10 < 0) {
								r39 = j10
								break
							}
							if (j10 >= len(src4)) {
								r39 = j10
								break
							}
							if (src4[j10] == 92) {
								j10 = (j10 + 2)
								continue
							}
							if (src4[j10] == 34) {
								r39 = (j10 + 1)
								break
							}
							j10 = (j10 + 1)
							continue
						}
						i4, nt4 = r39, (nt4 + 1)
						continue
					}
					var c29 int = src4[i4]
					if (((c29 >= 48) && (c29 <= 57)) || ((c29 == 45) || ((c29 == 43) || ((c29 == 46) || ((c29 == 101) || (c29 == 69)))))) {
						var j11 int = (i4 + 1)
						for ; ; j11 = (j11 + 1) {
							if (j11 < 0) {
								break
							}
							if (j11 >= len(src4)) {
								break
							}
							var c30 int = src4[j11]
							if (((c30 >= 48) && (c30 <= 57)) || ((c30 == 45) || ((c30 == 43) || ((c30 == 46) || ((c30 == 101) || (c30 == 69)))))) {
								continue
							}
							break
						}
						i4, nt4 = j11, (nt4 + 1)
						continue
					}
					var c31 int = src4[i4]
					if ((c31 >= 97) && (c31 <= 122)) {
						var j12 int = (i4 + 1)
						for ; ; j12 = (j12 + 1) {
							if (j12 < 0) {
								break
							}
							if (j12 >= len(src4)) {
								break
							}
							var c32 int = src4[j12]
							if ((c32 >= 97) && (c32 <= 122)) {
								continue
							}
							break
						}
						i4, nt4 = j12, (nt4 + 1)
						continue
					}
					i4, ok4 = (i4 + 1), 0
					continue
				}
				t21 = r31
			}
			t11 = t21
		}
		t1 = t11
	}
	return t1
}

func GenTokens(src []byte) int {
	stk := make([]byte, 32)
	stk2 := stk
	var i int = 0
	var nt int = 0
	var sp int = 0
	var mx int = 0
	var ok int = 1
	var r1 int
	for {
		if (i < 0) {
			r1 = 0
			break
		}
		if (i >= len(src)) {
			var t2 int
			if (sp == 0) {
				t2 = ok
			} else {
				t2 = 0
			}
			r1 = ((nt * 1000) + ((mx * 10) + t2))
			break
		}
		if (sp >= 32) {
			r1 = (nt * 1000)
			break
		}
		var c int = int(src[i])
		if ((c == 32) || ((c == 9) || ((c == 10) || (c == 13)))) {
			i = (i + 1)
			continue
		}
		var c2 int = int(src[i])
		if ((c2 == 123) || (c2 == 91)) {
			var t3 int
			if (int(src[i]) == 123) {
				t3 = 125
			} else {
				t3 = 93
			}
			stk2[sp] = byte(t3)
			var t4 int
			if ((sp + 1) > mx) {
				t4 = (sp + 1)
			} else {
				t4 = mx
			}
			i, nt, sp, mx = (i + 1), (nt + 1), (sp + 1), t4
			continue
		}
		var c3 int = int(src[i])
		if ((c3 == 125) || (c3 == 93)) {
			var t5 int
			if (sp < 1) {
				t5 = 0
			} else {
				t5 = (sp - 1)
			}
			var t6 int
			if (sp < 1) {
				t6 = 0
			} else {
				var t7 int
				if (sp < 1) {
					t7 = 0
				} else {
					t7 = (sp - 1)
				}
				var t8 int
				if (int(stk2[t7]) == int(src[i])) {
					t8 = ok
				} else {
					t8 = 0
				}
				t6 = t8
			}
			i, nt, sp, ok = (i + 1), (nt + 1), t5, t6
			continue
		}
		var c4 int = int(src[i])
		if ((c4 == 58) || (c4 == 44)) {
			i, nt = (i + 1), (nt + 1)
			continue
		}
		if (int(src[i]) == 34) {
			var j int = (i + 1)
			var r9 int
			for {
				if (j < 0) {
					r9 = j
					break
				}
				if (j >= len(src)) {
					r9 = j
					break
				}
				if (int(src[j]) == 92) {
					j = (j + 2)
					continue
				}
				if (int(src[j]) == 34) {
					r9 = (j + 1)
					break
				}
				j = (j + 1)
				continue
			}
			i, nt = r9, (nt + 1)
			continue
		}
		var c5 int = int(src[i])
		if (((c5 >= 48) && (c5 <= 57)) || ((c5 == 45) || ((c5 == 43) || ((c5 == 46) || ((c5 == 101) || (c5 == 69)))))) {
			var j2 int = (i + 1)
			for ; ; j2 = (j2 + 1) {
				if (j2 < 0) {
					break
				}
				if (j2 >= len(src)) {
					break
				}
				var c6 int = int(src[j2])
				if (((c6 >= 48) && (c6 <= 57)) || ((c6 == 45) || ((c6 == 43) || ((c6 == 46) || ((c6 == 101) || (c6 == 69)))))) {
					continue
				}
				break
			}
			i, nt = j2, (nt + 1)
			continue
		}
		var c7 int = int(src[i])
		if ((c7 >= 97) && (c7 <= 122)) {
			var j3 int = (i + 1)
			for ; ; j3 = (j3 + 1) {
				if (j3 < 0) {
					break
				}
				if (j3 >= len(src)) {
					break
				}
				var c8 int = int(src[j3])
				if ((c8 >= 97) && (c8 <= 122)) {
					continue
				}
				break
			}
			i, nt = j3, (nt + 1)
			continue
		}
		i, ok = (i + 1), 0
		continue
	}
	return r1
}

