// Code generated by oroboros. DO NOT EDIT.

package gauntlet

import "math/big"

func GenPower(b int, e int) *big.Int {
	acc := (big.NewInt(int64(1)))
	x := (big.NewInt(int64(b)))
	var k int = e
	for ; ; x, k = (x.Mul(x, x)), (k / 2) {
		if (k == 0) {
			break
		}
		if ((k % 2) == 1) {
			acc = (acc.Mul(acc, x))
			continue
		}
		continue
	}
	return acc
}

