// Code generated by oroboros. DO NOT EDIT.

package gauntlet

func TableDot(a []float64, b []float64) float64 {
	acc := 0.0
	var i int = 0
	var n1 int = len(a)
	b = b[:n1]
	for {
		if (i >= len(a)) {
			break
		}
		acc, i = (acc + (a[i] * b[i])), (i + 1)
		continue
	}
	return acc
}

