// Code generated by oroboros. DO NOT EDIT.

package gauntlet

func GenlDot(p []float64, q []float64) float64 {
	acc := 0.0
	var i int64 = 0
	var r1 float64
	for {
		if (i < (int64(len(p)))) {
			acc, i = (acc + ((p[i]) * (q[i]))), (i + 1)
			continue
		}
		r1 = acc
		break
	}
	return r1
}

