// Code generated by oroboros. DO NOT EDIT.

package gauntlet

func GenSmooth(a []float64) []float64 {
	var n1 int64 = ((int64(len(a))) - 2)
	v2 := make([]float64, n1)
	for i := int64(0); i < n1; i++ {
		v2[i] = ((((a[i]) + (a[(i + 1)])) + (a[(i + 2)])) / 3.0)
	}
	return v2
}

