// Code generated by oroboros. DO NOT EDIT.

package gauntlet

import "math"

func GenNorm(a []float64) float64 {
	acc := 0.0
	n1 := (len(a))
	for i := 0; i < n1; i++ {
		x := (a[i])
		acc = (acc + (x * x))
	}
	return (math.Sqrt(acc))
}

