// Code generated by oroboros. DO NOT EDIT.

package gauntlet

import "strings"

func GenGeneric0(a []float64) float64 {
	acc := 0.0
	n1 := (len(a))
	for i := 0; i < n1; i++ {
		acc = (acc + (a[i]))
	}
	return acc
}

func GenGeneric1(text string) map[string]int {
	ws := (strings.Fields(text))
	init := (make(map[string]int))
	acc := init
	n1 := (len(ws))
	for i := 0; i < n1; i++ {
		acc[(ws[i])]++
	}
	return acc
}

