// Code generated by oroboros. DO NOT EDIT.

package gauntlet

import "strings"

func GenWordcount(text string) map[string]int {
	ws := (strings.Fields(text))
	acc := (make(map[string]int))
	var n1 int64 = (int64(len(ws)))
	ws = ws[:n1]
	for i := int64(0); i < n1; i++ {
		acc[(ws[i])]++
	}
	return acc
}

