// Code generated by oroboros. DO NOT EDIT.

package gauntlet

func GenFilter(a []float64) float64 {
	acc := 0.0
	var n1 int64 = (int64(len(a)))
	a = a[:n1]
	for i := int64(0); i < n1; i++ {
		x := (a[i])
		var t2 float64
		if (x > 0.0) {
			t2 = (acc + x)
		} else {
			t2 = acc
		}
		acc = t2
	}
	return acc
}

