// Code generated by oroboros. DO NOT EDIT.

package gauntlet

func GenCentroid(xs []float64, ys []float64) float64 {
	ax, ay := 0.0, 0.0
	var n1 int64 = (int64(len(xs)))
	xs = xs[:n1]
	ys = ys[:n1]
	for i := int64(0); i < n1; i++ {
		ax, ay = (ax + (xs[i])), (ay + (ys[i]))
	}
	return (ax + ay)
}

