// Code generated by oroboros. DO NOT EDIT.

package gauntlet

func GenlCentroid(xs []float64, ys []float64) float64 {
	ax := 0.0
	ay := 0.0
	var i int64 = 0
	var r1 float64
	for {
		if (i < (int64(len(xs)))) {
			ax, ay, i = (ax + (xs[i])), (ay + (ys[i])), (i + 1)
			continue
		}
		r1 = (ax + ay)
		break
	}
	return r1
}

