// Code generated by oroboros. DO NOT EDIT.

package gauntlet

import "math"

func GenNorm(a []float64) float64 {
	acc := 0.0
	var n1 int64 = (int64(len(a)))
	a = a[:n1]
	for i := int64(0); i < n1; i++ {
		x := (a[i])
		acc = (acc + (x * x))
	}
	return (math.Sqrt(acc))
}

