package gauntlet

import "testing"

// The full-size benchmarks (65536 elements = 512KB per slice) are memory-bound,
// which hides everything the compiler does. These run at 1024 elements (8KB per
// slice, comfortably in L1) so that bounds checks and call overhead are visible.

const NSmall = 1024

var (
	smallA = MakeVec(NSmall, 1)
	smallB = MakeVec(NSmall, 2)
	smallI = MakeInts(NSmall, 3)
)

func BenchmarkSmallDotNaive(b *testing.B) {
	for b.Loop() {
		sinkF = DotNaive(smallA, smallB)
	}
}

func BenchmarkSmallDotHoisted(b *testing.B) {
	for b.Loop() {
		sinkF = DotHoisted(smallA, smallB)
	}
}

func BenchmarkSmallDotRange(b *testing.B) {
	for b.Loop() {
		sinkF = DotRange(smallA, smallB)
	}
}

func BenchmarkSmallSumF64(b *testing.B) {
	for b.Loop() {
		sinkF = SumF64(smallA)
	}
}

func BenchmarkSmallSumF64Generic(b *testing.B) {
	for b.Loop() {
		sinkF = SumF64Generic(smallA)
	}
}

func BenchmarkSmallCountPositive(b *testing.B) {
	for b.Loop() {
		sinkI = CountPositive(smallI)
	}
}

func BenchmarkSmallCountPositiveGeneric(b *testing.B) {
	for b.Loop() {
		sinkI = CountPositiveGeneric(smallI)
	}
}

func BenchmarkSmallDotUnordered4(b *testing.B) {
	for b.Loop() {
		sinkF = DotUnordered4(smallA, smallB)
	}
}

func BenchmarkSmallSumF64Unordered4(b *testing.B) {
	for b.Loop() {
		sinkF = SumF64Unordered4(smallA)
	}
}

// Generated by oroboros from examples/dot.oro. The first benchmark in this
// project that measures our own output rather than the bar.
func BenchmarkSmallGenDot(b *testing.B) {
	for b.Loop() {
		sinkF = GenDot(smallA, smallB)
	}
}

// The duplicated-read question: generated (two reads) against hand-written with
// one read and hand-written with two.
func BenchmarkSmallFilterRef(b *testing.B) {
	for b.Loop() {
		sinkF = FilterSumRef(smallA)
	}
}

func BenchmarkSmallFilterDup(b *testing.B) {
	for b.Loop() {
		sinkF = FilterSumDup(smallA)
	}
}

func BenchmarkSmallGenFilter(b *testing.B) {
	for b.Loop() {
		sinkF = GenFilterSum(smallA)
	}
}

var smallY = MakeVec(NSmall, 9)

func BenchmarkSmallCentroidRef(b *testing.B) {
	for b.Loop() {
		sinkF = CentroidSumRef(smallA, smallY)
	}
}

func BenchmarkSmallGenCentroid(b *testing.B) {
	for b.Loop() {
		sinkF = GenCentroid(smallA, smallY)
	}
}

// Word count at DELIBERATELY small n: the generated version calls
// strings.Fields inside the loop, so it is O(n^2) and 65536 words would not
// finish. See gauntlet/results/wordcount-2026-08-14.md.
var wcText = MakeText(2000, 5)

func BenchmarkWCHandWritten(b *testing.B) {
	for b.Loop() {
		sinkM = WordCountIncr(wcText)
	}
}

func BenchmarkWCGenerated(b *testing.B) {
	for b.Loop() {
		sinkM = GenWordCount(wcText)
	}
}
