// Code generated by oroboros. DO NOT EDIT.

package gauntlet

import "bufio"
import "fmt"
import "os"

func GenMain() int {
	var v26c string
	var v27c int
	v0 := (os.Stdin)
	v1 := (bufio.NewScanner(v0))
	var v9 int = 0
	var v10 int = 0
	var v11 int = 0
	var v12 string = ""
	var v13 int = -1
	var v14 int = 0
	var v8 int
	for ; ; v9 = (v9 + 1) {
		v15 := (v1.Scan())
		if v15 {
			v17 := (v9 >= 16777216)
			if v17 {
				fmt.Println("ages: more than 16777216 lines")
				v8 = 1
				break
			}
			v25 := (v1.Text())
			v26c = ""
			v26 := &v26c
			v27c = 0
			v27 := &v27c
			_, v30 := fmt.Sscan(v25, v26, v27)
			v31 := *v26
			v32 := *v27
			v33 := (v30 == nil)
			if v33 {
				v35 := (v32 >= 0)
				if v35 {
					v38 := (v32 <= 150)
					if v38 {
						v41 := (v10 < 16777216)
						if v41 {
							v44 := (v10 + 1)
							v45 := (v11 + v32)
							v46 := (v32 > v13)
							if v46 {
								v10, v11, v12, v13 = v44, v45, v31, v32
								continue
							}
							v10, v11 = v44, v45
							continue
						}
						v57 := (v14 < 16777216)
						if v57 {
							v62 := (v14 + 1)
							v14 = v62
							continue
						}
						continue
					}
					v68 := (v14 < 16777216)
					if v68 {
						v73 := (v14 + 1)
						v14 = v73
						continue
					}
					continue
				}
				v79 := (v14 < 16777216)
				if v79 {
					v84 := (v14 + 1)
					v14 = v84
					continue
				}
				continue
			}
			v89 := (v14 < 16777216)
			if v89 {
				v94 := (v14 + 1)
				v14 = v94
				continue
			}
			continue
		}
		v98 := (v1.Err())
		v99 := (v98 == nil)
		if v99 {
			v101 := (v10 == 0)
			if v101 {
				fmt.Println("no people")
			} else {
				v110 := (v11 / v10)
				fmt.Printf("%d people, mean age %d, oldest %s (%d)\n", v10, v110, v12, v13)
			}
			fmt.Printf("%d lines skipped\n", v14)
			v8 = 0
			break
		}
		fmt.Println("ages: cannot read standard input")
		v8 = 1
		break
	}
	os.Exit(v8)
	return v8
}

