// Code generated by oroboros. DO NOT EDIT.

package gauntlet

func GenDigitSum(v0 int) int {
	var v11 int = v0
	var v12 int = 0
	for {
		v14 := (v11 <= 0)
		if v14 {
			break
		}
		v18 := (v11 / 10)
		v20 := (v11 % 10)
		v21 := (v12 + v20)
		v11, v12 = v18, v21
		continue
	}
	return v12
}

