// Code generated by oroboros. DO NOT EDIT.

export function genMain() {
	const v1 = (new Float64Array(1000));
	let v4 = v1;
	let v5 = 0;
	for (;; v5 = (v5 + 1)) {
		if ((v5 >= 1000)) {
			break;
		}
		v4[v5] = v5;
		continue;
	}
	console.log("report");
	console.log(v4.length);
	let v20 = 0;
	let v21 = 0;
	for (;; v21 = (v21 + 1)) {
		if ((v21 >= v4.length)) {
			break;
		}
		v20 = (v20 + ((v4[v21]) * (v4[v21])));
		continue;
	}
	console.log(v20);
	return v20;
}

