// Code generated by oroboros. DO NOT EDIT.

public final class examples_big_fib.java {
	public static java.math.BigInteger genFib(int v0) {
		final java.math.BigInteger v10 = (java.math.BigInteger.valueOf(0));
		final java.math.BigInteger v12 = (java.math.BigInteger.valueOf(1));
		java.math.BigInteger v15 = v10;
		java.math.BigInteger v16 = v12;
		int v17 = 0;
		for (;; v17 = (v17 + 1)) {
			final boolean v18 = (v17 >= v0);
			if (v18) {
				break;
			}
			final java.math.BigInteger v23 = (v15.add(v16));
			v15 = v16;
			v16 = v23;
			continue;
		}
		return v15;
	}

}
