// Code generated by oroboros. DO NOT EDIT.

package gauntlet

func GenFindFirst(a []float64, k float64) int {
	var i int = 0
	var r1 int
	for ; ; i = (i + 1) {
		if (i >= (len(a))) {
			r1 = -1
			break
		}
		if ((a[i]) > k) {
			r1 = i
			break
		}
		continue
	}
	return r1
}

