// Code generated by oroboros. DO NOT EDIT.

package gauntlet

import "fmt"
import "math/bits"
import "strconv"

func GenMain() int {
	var n int = 0
	h := (uint64(0))
	l := (uint64(1))
	var over int = 0
	var r1 int
	for {
		if (over == 1) {
			fmt.Println(n, "overflows 128 bits")
			r1 = n
			break
		}
		if (n > 40) {
			r1 = 0
			break
		}
		h2 := h
		l2 := l
		s := ""
		var r2 string
		for {
			if (((h2 == (uint64(0)))) && ((l2 < (uint64(1000000000000000000))))) {
				r2 = ((strconv.FormatUint(uint64(l2), 10)) + s)
				break
			}
			q, _ := bits.Div64(uint64(((h2 % (uint64(1000000000000000000))))), uint64(l2), uint64((uint64(1000000000000000000))))
			var i int = 0
			v := (bits.Rem64(uint64(h2), uint64(l2), uint64((uint64(1000000000000000000)))))
			s2 := ""
			for ; ; i = (i + 1) {
				if (i >= 18) {
					break
				}
				v, s2 = ((v / (uint64(10)))), ((string(rune((48 + (int(((v % (uint64(10)))))))))) + s2)
				continue
			}
			h2, l2, s = ((h2 / (uint64(1000000000000000000)))), q, (s2 + s)
			continue
		}
		fmt.Println(n, r2)
		var _c17 int = (n + 1)
		_nl1, _nl2 := bits.Mul64(uint64(l), uint64((uint64(_c17))))
		_nl3, _nl4 := bits.Mul64(uint64(h), uint64((uint64(_c17))))
		_nl5, _nl6h3 := func(x, y, c uint64) (uint64, int) { s, o := bits.Add64(x, y, c); return s, int(o) }(uint64(_nl4), uint64(_nl1), uint64((uint64(0))))
		_nl6 := int(_nl6h3)
		var t4 int
		if (((_nl3 == (uint64(0)))) && (_nl6 == 0)) {
			t4 = 0
		} else {
			t4 = 1
		}
		n, h, l, over = (n + 1), _nl5, _nl2, t4
		continue
	}
	return r1
}

