// Code generated by oroboros. DO NOT EDIT.

public final class examples_native_dot-java.java {
	public static double genDot(double[] a, double[] b) {
		double acc = 0.0;
		int i = 0;
		for (;; i = (i + 1)) {
			if ((i >= a.length)) {
				break;
			}
			acc = (acc + (a[i] * b[i]));
			continue;
		}
		return acc;
	}

}
