// Code generated by oroboros. DO NOT EDIT.

export function genAlwaysCrashes(v0) {
	throw new Error("the value is never a success");
}

export function genQuarter(v0) {
	if (((v0 & 1) === 0)) {
		const v14 = (v0 >> 1);
		if (((v14 & 1) === 0)) {
			return (v14 >> 1);
		}
		throw new Error("a multiple of four is expected");
	}
	throw new Error("an even number is expected");
}

