// Code generated by oroboros. DO NOT EDIT.

public final class examples_big_limbs.java {
	public static long genLimb(long k) {
		final int[] b = new int[(int) 64];
		int[] b2 = b;
		long i2 = 0;
		long r = 1;
		for (;; i2 = (i2 + 1), r = (r >> 24)) {
			if ((i2 >= 64)) {
				break;
			}
			b2[(int) i2] = (int) (r & 16777215);
			continue;
		}
		int[] acc = b2;
		long i = 2;
		int[] sp1 = new int[64];
		for (;; i = (i + 1)) {
			if ((i > 200)) {
				break;
			}
			java.util.Arrays.fill(sp1, (int) 0);
			final int[] o = sp1;
			int[] o3 = o;
			long i1 = 0;
			long c = 0;
			for (;; i1 = (i1 + 1)) {
				if ((i1 >= 64)) {
					break;
				}
				final long t145 = ((((i1 < 0) ? 0 : ((i1 >= acc.length) ? 0 : (long) acc[(int) i1])) * i) + c);
				o3[(int) i1] = (int) (t145 & 16777215);
				c = (t145 >> 24);
				continue;
			}
			final var sw2 = acc;
			acc = o3;
			sp1 = sw2;
			continue;
		}
		final int[] t1452 = acc;
		return ((k < 0) ? 0 : ((k >= t1452.length) ? 0 : (long) t1452[(int) k]));
	}

}
