// Code generated by oroboros. DO NOT EDIT.

package gauntlet

import "fmt"

func GenCountPrimes(n int) int {
	c := (make([]bool, n))
	var i int = 2
	for ; ; i = (i + 1) {
		if ((i * i) >= n) {
			break
		}
		if (c[i]) {
			continue
		}
		s := c
		var j int = (i * i)
		for ; ; j = (j + i) {
			if (j < n) {
				s[j] = true
				continue
			}
			break
		}
		c = s
		continue
	}
	c2 := c
	var acc int = 0
	var k int = 2
	var n1 int = n
	s2 := c2[:n1]
	for ; ; k = (k + 1) {
		if (k >= n) {
			break
		}
		if (s2[k]) {
			continue
		}
		acc = (acc + 1)
		continue
	}
	return acc
}

func GenMain() int {
	c := (make([]bool, 20000))
	var i int = 2
	for ; ; i = (i + 1) {
		if ((i * i) >= 20000) {
			break
		}
		if (c[i]) {
			continue
		}
		s := c
		var j int = (i * i)
		for ; ; j = (j + i) {
			if (j < 20000) {
				s[j] = true
				continue
			}
			break
		}
		c = s
		continue
	}
	c2 := c
	var acc int = 0
	var k int = 2
	var n1 int = 20000
	s2 := c2[:n1]
	for ; ; k = (k + 1) {
		if (k >= 20000) {
			break
		}
		if (s2[k]) {
			continue
		}
		acc = (acc + 1)
		continue
	}
	fmt.Println(acc)
	return acc
}

