// Code generated by oroboros. DO NOT EDIT.

package gauntlet

func GenSmooth(v0 []float64) []float64 {
	v1 := len(v0)
	v3 := (v1 - 2)
	v4 := (make([]float64, v3))
	v7 := v4
	var v8 int = 0
	for ; ; v8 = (v8 + 1) {
		v9 := len(v0)
		v11 := (v9 - 2)
		v12 := (v8 >= v11)
		if v12 {
			break
		}
		v15 := v0[v8]
		v17 := (v8 + 1)
		v18 := v0[v17]
		v19 := (v15 + v18)
		v21 := (v8 + 2)
		v22 := v0[v21]
		v23 := (v19 + v22)
		v25 := (v23 / 3.0)
		v7[v8] = v25
		continue
	}
	return v7
}

func GenSmoothInto(v0 []float64, v1 []float64) []float64 {
	v7 := v0
	var v8 int = 0
	for ; ; v8 = (v8 + 1) {
		v9 := len(v1)
		v11 := (v9 - 2)
		v12 := (v8 >= v11)
		if v12 {
			break
		}
		v15 := v1[v8]
		v17 := (v8 + 1)
		v18 := v1[v17]
		v19 := (v15 + v18)
		v21 := (v8 + 2)
		v22 := v1[v21]
		v23 := (v19 + v22)
		v25 := (v23 / 3.0)
		v7[v8] = v25
		continue
	}
	return v7
}

