// Code generated by oroboros. DO NOT EDIT.

package gauntlet

func GenMeasure(src []byte) int {
	nodes := make([]int16, (4 * 512))
	stk := make([]int16, (2 * 32))
	nodes2 := nodes
	stk2 := stk
	var i int = 0
	var nn int = 1
	var sp int = 0
	var ok int = 1
	var r1 []int16
	for {
		if (i < 0) {
			nodes2[0] = int16(nn)
			nodes2[1] = int16(0)
			r1 = nodes2
			break
		}
		if (i >= len(src)) {
			nodes2[0] = int16(nn)
			var t2 int
			if (sp == 0) {
				t2 = ok
			} else {
				t2 = 0
			}
			nodes2[1] = int16(t2)
			r1 = nodes2
			break
		}
		if (nn >= 512) {
			nodes2[0] = int16(nn)
			nodes2[1] = int16(0)
			r1 = nodes2
			break
		}
		if (sp >= 32) {
			nodes2[0] = int16(nn)
			nodes2[1] = int16(0)
			r1 = nodes2
			break
		}
		var c int = int(src[i])
		if ((c == 32) || ((c == 9) || ((c == 10) || (c == 13)))) {
			i = (i + 1)
			continue
		}
		var c2 int = int(src[i])
		if ((c2 == 58) || (c2 == 44)) {
			i = (i + 1)
			continue
		}
		var c3 int = int(src[i])
		if ((c3 == 123) || (c3 == 91)) {
			var t3 int
			if (int(src[i]) == 123) {
				t3 = 5
			} else {
				t3 = 4
			}
			nodes2[((4 * nn) + 0)] = int16(t3)
			nodes2[((4 * nn) + 1)] = int16(0)
			nodes3 := nodes2
			var t4 []int16
			if (sp < 1) {
				t4 = nodes3
			} else {
				var lc int = int(stk2[((2 * (sp - 1)) + 1)])
				var t5 []int16
				if (lc == 0) {
					nodes3[((4 * int(stk2[((2 * (sp - 1)) + 0)])) + 2)] = int16(nn)
					t5 = nodes3
				} else {
					nodes3[((4 * lc) + 3)] = int16(nn)
					t5 = nodes3
				}
				t4 = t5
			}
			var t6 []int16
			if (sp < 1) {
				t6 = stk2
			} else {
				stk2[((2 * (sp - 1)) + 1)] = int16(nn)
				t6 = stk2
			}
			stk3 := t6
			stk3[((2 * sp) + 0)] = int16(nn)
			stk3[((2 * sp) + 1)] = int16(0)
			nodes2, stk2, i, nn, sp = t4, stk3, (i + 1), (nn + 1), (sp + 1)
			continue
		}
		var c4 int = int(src[i])
		if ((c4 == 125) || (c4 == 93)) {
			var t7 int
			if (sp < 1) {
				t7 = 0
			} else {
				t7 = (sp - 1)
			}
			var t8 int
			if (sp < 1) {
				t8 = 0
			} else {
				var t9 int
				if (int(src[i]) == 125) {
					t9 = 5
				} else {
					t9 = 4
				}
				var t10 int
				if (int(nodes2[((4 * int(stk2[((2 * (sp - 1)) + 0)])) + 0)]) == t9) {
					t10 = ok
				} else {
					t10 = 0
				}
				t8 = t10
			}
			i, sp, ok = (i + 1), t7, t8
			continue
		}
		var c5 int = int(src[i])
		if ((c5 == 34) || ((((c5 >= 48) && (c5 <= 57)) || ((c5 == 45) || ((c5 == 43) || ((c5 == 46) || ((c5 == 101) || (c5 == 69)))))) || ((c5 >= 97) && (c5 <= 122)))) {
			var t11 int
			if (int(src[i]) == 34) {
				t11 = 2
			} else {
				var c6 int = int(src[i])
				var t12 int
				if (((c6 >= 48) && (c6 <= 57)) || ((c6 == 45) || ((c6 == 43) || ((c6 == 46) || ((c6 == 101) || (c6 == 69)))))) {
					t12 = 1
				} else {
					t12 = 3
				}
				t11 = t12
			}
			var tg int = t11
			var t13 int
			if (int(src[i]) == 34) {
				var j int = (i + 1)
				var r14 int
				for {
					if (j < 0) {
						r14 = j
						break
					}
					if (j >= len(src)) {
						r14 = j
						break
					}
					if (int(src[j]) == 92) {
						j = (j + 2)
						continue
					}
					if (int(src[j]) == 34) {
						r14 = (j + 1)
						break
					}
					j = (j + 1)
					continue
				}
				t13 = r14
			} else {
				var c7 int = int(src[i])
				var t15 int
				if (((c7 >= 48) && (c7 <= 57)) || ((c7 == 45) || ((c7 == 43) || ((c7 == 46) || ((c7 == 101) || (c7 == 69)))))) {
					var j2 int = (i + 1)
					for ; ; j2 = (j2 + 1) {
						if (j2 < 0) {
							break
						}
						if (j2 >= len(src)) {
							break
						}
						var c8 int = int(src[j2])
						if (((c8 >= 48) && (c8 <= 57)) || ((c8 == 45) || ((c8 == 43) || ((c8 == 46) || ((c8 == 101) || (c8 == 69)))))) {
							continue
						}
						break
					}
					t15 = j2
				} else {
					var j3 int = (i + 1)
					for ; ; j3 = (j3 + 1) {
						if (j3 < 0) {
							break
						}
						if (j3 >= len(src)) {
							break
						}
						var c9 int = int(src[j3])
						if ((c9 >= 97) && (c9 <= 122)) {
							continue
						}
						break
					}
					t15 = j3
				}
				t13 = t15
			}
			var ni int = t13
			nodes2[((4 * nn) + 0)] = int16(tg)
			nodes2[((4 * nn) + 1)] = int16((ni - i))
			nodes4 := nodes2
			var t16 []int16
			if (sp < 1) {
				t16 = nodes4
			} else {
				var lc2 int = int(stk2[((2 * (sp - 1)) + 1)])
				var t17 []int16
				if (lc2 == 0) {
					nodes4[((4 * int(stk2[((2 * (sp - 1)) + 0)])) + 2)] = int16(nn)
					t17 = nodes4
				} else {
					nodes4[((4 * lc2) + 3)] = int16(nn)
					t17 = nodes4
				}
				t16 = t17
			}
			var t18 []int16
			if (sp < 1) {
				t18 = stk2
			} else {
				stk2[((2 * (sp - 1)) + 1)] = int16(nn)
				t18 = stk2
			}
			nodes2, stk2, i, nn = t16, t18, ni, (nn + 1)
			continue
		}
		i, ok = (i + 1), 0
		continue
	}
	nodes5 := r1
	wl := make([]int, (2 * 512))
	wl[0] = 1
	wl[1] = 1
	wl2 := wl
	var sp2 int = 1
	var seen int = 0
	var acc int = 0
	var steps int = 0
	var r19 int
	for ; ; seen, steps = (seen + 1), (steps + 1) {
		if (steps >= (2 * 512)) {
			r19 = ((seen * 1000) + acc)
			break
		}
		if (sp2 < 1) {
			r19 = ((seen * 1000) + acc)
			break
		}
		if (sp2 >= 512) {
			r19 = ((seen * 1000) + acc)
			break
		}
		var n int = wl2[((2 * (sp2 - 1)) + 0)]
		var d int = wl2[((2 * (sp2 - 1)) + 1)]
		var sb int = int(nodes5[((4 * n) + 3)])
		var kd int = int(nodes5[((4 * n) + 2)])
		var s1 int = (sp2 - 1)
		var t20 []int
		if (sb == 0) {
			t20 = wl2
		} else {
			wl2[((2 * s1) + 0)] = sb
			wl2[((2 * s1) + 1)] = d
			t20 = wl2
		}
		w1 := t20
		var t21 int
		if (sb == 0) {
			t21 = s1
		} else {
			t21 = (s1 + 1)
		}
		var s2 int = t21
		var t22 []int
		if (kd == 0) {
			t22 = w1
		} else {
			w1[((2 * s2) + 0)] = kd
			w1[((2 * s2) + 1)] = (d + 1)
			t22 = w1
		}
		w2 := t22
		var t23 int
		if (kd == 0) {
			t23 = s2
		} else {
			t23 = (s2 + 1)
		}
		wl2, sp2, acc = w2, t23, (acc + (int(nodes5[((4 * n) + 0)]) * d))
		continue
	}
	return r19
}

func GenRun(k int) int {
	var t1 int
	if (k == 0) {
		src := []byte{91, 49, 44, 50, 93}
		nodes := make([]int, (4 * 512))
		stk := make([]int, (2 * 32))
		nodes2 := nodes
		stk2 := stk
		var i int = 0
		var nn int = 1
		var sp int = 0
		var ok int = 1
		var r2 []int
		for {
			if (i < 0) {
				nodes2[0] = nn
				nodes2[1] = 0
				r2 = nodes2
				break
			}
			if (i >= len(src)) {
				nodes2[0] = nn
				var t3 int
				if (sp == 0) {
					t3 = ok
				} else {
					t3 = 0
				}
				nodes2[1] = t3
				r2 = nodes2
				break
			}
			if (nn >= 512) {
				nodes2[0] = nn
				nodes2[1] = 0
				r2 = nodes2
				break
			}
			if (sp >= 32) {
				nodes2[0] = nn
				nodes2[1] = 0
				r2 = nodes2
				break
			}
			var c int = int(src[i])
			if ((c == 32) || ((c == 9) || ((c == 10) || (c == 13)))) {
				i = (i + 1)
				continue
			}
			var c2 int = int(src[i])
			if ((c2 == 58) || (c2 == 44)) {
				i = (i + 1)
				continue
			}
			var c3 int = int(src[i])
			if ((c3 == 123) || (c3 == 91)) {
				var t4 int
				if (int(src[i]) == 123) {
					t4 = 5
				} else {
					t4 = 4
				}
				nodes2[((4 * nn) + 0)] = t4
				nodes2[((4 * nn) + 1)] = 0
				nodes3 := nodes2
				var t5 []int
				if (sp < 1) {
					t5 = nodes3
				} else {
					var lc int = stk2[((2 * (sp - 1)) + 1)]
					var t6 []int
					if (lc == 0) {
						nodes3[((4 * stk2[((2 * (sp - 1)) + 0)]) + 2)] = nn
						t6 = nodes3
					} else {
						nodes3[((4 * lc) + 3)] = nn
						t6 = nodes3
					}
					t5 = t6
				}
				var t7 []int
				if (sp < 1) {
					t7 = stk2
				} else {
					stk2[((2 * (sp - 1)) + 1)] = nn
					t7 = stk2
				}
				stk3 := t7
				stk3[((2 * sp) + 0)] = nn
				stk3[((2 * sp) + 1)] = 0
				nodes2, stk2, i, nn, sp = t5, stk3, (i + 1), (nn + 1), (sp + 1)
				continue
			}
			var c4 int = int(src[i])
			if ((c4 == 125) || (c4 == 93)) {
				var t8 int
				if (sp < 1) {
					t8 = 0
				} else {
					t8 = (sp - 1)
				}
				var t9 int
				if (sp < 1) {
					t9 = 0
				} else {
					var t10 int
					if (int(src[i]) == 125) {
						t10 = 5
					} else {
						t10 = 4
					}
					var t11 int
					if (nodes2[((4 * stk2[((2 * (sp - 1)) + 0)]) + 0)] == t10) {
						t11 = ok
					} else {
						t11 = 0
					}
					t9 = t11
				}
				i, sp, ok = (i + 1), t8, t9
				continue
			}
			var c5 int = int(src[i])
			if ((c5 == 34) || ((((c5 >= 48) && (c5 <= 57)) || ((c5 == 45) || ((c5 == 43) || ((c5 == 46) || ((c5 == 101) || (c5 == 69)))))) || ((c5 >= 97) && (c5 <= 122)))) {
				var t12 int
				if (int(src[i]) == 34) {
					t12 = 2
				} else {
					var c6 int = int(src[i])
					var t13 int
					if (((c6 >= 48) && (c6 <= 57)) || ((c6 == 45) || ((c6 == 43) || ((c6 == 46) || ((c6 == 101) || (c6 == 69)))))) {
						t13 = 1
					} else {
						t13 = 3
					}
					t12 = t13
				}
				var tg int = t12
				var t14 int
				if (int(src[i]) == 34) {
					var j int = (i + 1)
					var r15 int
					for {
						if (j < 0) {
							r15 = j
							break
						}
						if (j >= len(src)) {
							r15 = j
							break
						}
						if (int(src[j]) == 92) {
							j = (j + 2)
							continue
						}
						if (int(src[j]) == 34) {
							r15 = (j + 1)
							break
						}
						j = (j + 1)
						continue
					}
					t14 = r15
				} else {
					var c7 int = int(src[i])
					var t16 int
					if (((c7 >= 48) && (c7 <= 57)) || ((c7 == 45) || ((c7 == 43) || ((c7 == 46) || ((c7 == 101) || (c7 == 69)))))) {
						var j2 int = (i + 1)
						for ; ; j2 = (j2 + 1) {
							if (j2 < 0) {
								break
							}
							if (j2 >= len(src)) {
								break
							}
							var c8 int = int(src[j2])
							if (((c8 >= 48) && (c8 <= 57)) || ((c8 == 45) || ((c8 == 43) || ((c8 == 46) || ((c8 == 101) || (c8 == 69)))))) {
								continue
							}
							break
						}
						t16 = j2
					} else {
						var j3 int = (i + 1)
						for ; ; j3 = (j3 + 1) {
							if (j3 < 0) {
								break
							}
							if (j3 >= len(src)) {
								break
							}
							var c9 int = int(src[j3])
							if ((c9 >= 97) && (c9 <= 122)) {
								continue
							}
							break
						}
						t16 = j3
					}
					t14 = t16
				}
				var ni int = t14
				nodes2[((4 * nn) + 0)] = tg
				nodes2[((4 * nn) + 1)] = (ni - i)
				nodes4 := nodes2
				var t17 []int
				if (sp < 1) {
					t17 = nodes4
				} else {
					var lc2 int = stk2[((2 * (sp - 1)) + 1)]
					var t18 []int
					if (lc2 == 0) {
						nodes4[((4 * stk2[((2 * (sp - 1)) + 0)]) + 2)] = nn
						t18 = nodes4
					} else {
						nodes4[((4 * lc2) + 3)] = nn
						t18 = nodes4
					}
					t17 = t18
				}
				var t19 []int
				if (sp < 1) {
					t19 = stk2
				} else {
					stk2[((2 * (sp - 1)) + 1)] = nn
					t19 = stk2
				}
				nodes2, stk2, i, nn = t17, t19, ni, (nn + 1)
				continue
			}
			i, ok = (i + 1), 0
			continue
		}
		nodes5 := r2
		wl := make([]int, (2 * 512))
		wl[0] = 1
		wl[1] = 1
		wl2 := wl
		var sp2 int = 1
		var seen int = 0
		var acc int = 0
		var steps int = 0
		var r20 int
		for ; ; seen, steps = (seen + 1), (steps + 1) {
			if (steps >= (2 * 512)) {
				r20 = ((seen * 1000) + acc)
				break
			}
			if (sp2 < 1) {
				r20 = ((seen * 1000) + acc)
				break
			}
			if (sp2 >= 512) {
				r20 = ((seen * 1000) + acc)
				break
			}
			var n int = wl2[((2 * (sp2 - 1)) + 0)]
			var d int = wl2[((2 * (sp2 - 1)) + 1)]
			var sb int = nodes5[((4 * n) + 3)]
			var kd int = nodes5[((4 * n) + 2)]
			var s1 int = (sp2 - 1)
			var t21 []int
			if (sb == 0) {
				t21 = wl2
			} else {
				wl2[((2 * s1) + 0)] = sb
				wl2[((2 * s1) + 1)] = d
				t21 = wl2
			}
			w1 := t21
			var t22 int
			if (sb == 0) {
				t22 = s1
			} else {
				t22 = (s1 + 1)
			}
			var s2 int = t22
			var t23 []int
			if (kd == 0) {
				t23 = w1
			} else {
				w1[((2 * s2) + 0)] = kd
				w1[((2 * s2) + 1)] = (d + 1)
				t23 = w1
			}
			w2 := t23
			var t24 int
			if (kd == 0) {
				t24 = s2
			} else {
				t24 = (s2 + 1)
			}
			wl2, sp2, acc = w2, t24, (acc + (nodes5[((4 * n) + 0)] * d))
			continue
		}
		t1 = (((nodes5[0] - 1) * 1000000) + ((r20 * 10) + nodes5[1]))
	} else {
		var t25 int
		if (k == 1) {
			src2 := []byte{123, 34, 97, 34, 58, 49, 125}
			nodes6 := make([]int, (4 * 512))
			stk4 := make([]int, (2 * 32))
			nodes7 := nodes6
			stk5 := stk4
			var i2 int = 0
			var nn2 int = 1
			var sp3 int = 0
			var ok2 int = 1
			var r26 []int
			for {
				if (i2 < 0) {
					nodes7[0] = nn2
					nodes7[1] = 0
					r26 = nodes7
					break
				}
				if (i2 >= len(src2)) {
					nodes7[0] = nn2
					var t27 int
					if (sp3 == 0) {
						t27 = ok2
					} else {
						t27 = 0
					}
					nodes7[1] = t27
					r26 = nodes7
					break
				}
				if (nn2 >= 512) {
					nodes7[0] = nn2
					nodes7[1] = 0
					r26 = nodes7
					break
				}
				if (sp3 >= 32) {
					nodes7[0] = nn2
					nodes7[1] = 0
					r26 = nodes7
					break
				}
				var c10 int = int(src2[i2])
				if ((c10 == 32) || ((c10 == 9) || ((c10 == 10) || (c10 == 13)))) {
					i2 = (i2 + 1)
					continue
				}
				var c11 int = int(src2[i2])
				if ((c11 == 58) || (c11 == 44)) {
					i2 = (i2 + 1)
					continue
				}
				var c12 int = int(src2[i2])
				if ((c12 == 123) || (c12 == 91)) {
					var t28 int
					if (int(src2[i2]) == 123) {
						t28 = 5
					} else {
						t28 = 4
					}
					nodes7[((4 * nn2) + 0)] = t28
					nodes7[((4 * nn2) + 1)] = 0
					nodes8 := nodes7
					var t29 []int
					if (sp3 < 1) {
						t29 = nodes8
					} else {
						var lc3 int = stk5[((2 * (sp3 - 1)) + 1)]
						var t30 []int
						if (lc3 == 0) {
							nodes8[((4 * stk5[((2 * (sp3 - 1)) + 0)]) + 2)] = nn2
							t30 = nodes8
						} else {
							nodes8[((4 * lc3) + 3)] = nn2
							t30 = nodes8
						}
						t29 = t30
					}
					var t31 []int
					if (sp3 < 1) {
						t31 = stk5
					} else {
						stk5[((2 * (sp3 - 1)) + 1)] = nn2
						t31 = stk5
					}
					stk6 := t31
					stk6[((2 * sp3) + 0)] = nn2
					stk6[((2 * sp3) + 1)] = 0
					nodes7, stk5, i2, nn2, sp3 = t29, stk6, (i2 + 1), (nn2 + 1), (sp3 + 1)
					continue
				}
				var c13 int = int(src2[i2])
				if ((c13 == 125) || (c13 == 93)) {
					var t32 int
					if (sp3 < 1) {
						t32 = 0
					} else {
						t32 = (sp3 - 1)
					}
					var t33 int
					if (sp3 < 1) {
						t33 = 0
					} else {
						var t34 int
						if (int(src2[i2]) == 125) {
							t34 = 5
						} else {
							t34 = 4
						}
						var t35 int
						if (nodes7[((4 * stk5[((2 * (sp3 - 1)) + 0)]) + 0)] == t34) {
							t35 = ok2
						} else {
							t35 = 0
						}
						t33 = t35
					}
					i2, sp3, ok2 = (i2 + 1), t32, t33
					continue
				}
				var c14 int = int(src2[i2])
				if ((c14 == 34) || ((((c14 >= 48) && (c14 <= 57)) || ((c14 == 45) || ((c14 == 43) || ((c14 == 46) || ((c14 == 101) || (c14 == 69)))))) || ((c14 >= 97) && (c14 <= 122)))) {
					var t36 int
					if (int(src2[i2]) == 34) {
						t36 = 2
					} else {
						var c15 int = int(src2[i2])
						var t37 int
						if (((c15 >= 48) && (c15 <= 57)) || ((c15 == 45) || ((c15 == 43) || ((c15 == 46) || ((c15 == 101) || (c15 == 69)))))) {
							t37 = 1
						} else {
							t37 = 3
						}
						t36 = t37
					}
					var tg2 int = t36
					var t38 int
					if (int(src2[i2]) == 34) {
						var j4 int = (i2 + 1)
						var r39 int
						for {
							if (j4 < 0) {
								r39 = j4
								break
							}
							if (j4 >= len(src2)) {
								r39 = j4
								break
							}
							if (int(src2[j4]) == 92) {
								j4 = (j4 + 2)
								continue
							}
							if (int(src2[j4]) == 34) {
								r39 = (j4 + 1)
								break
							}
							j4 = (j4 + 1)
							continue
						}
						t38 = r39
					} else {
						var c16 int = int(src2[i2])
						var t40 int
						if (((c16 >= 48) && (c16 <= 57)) || ((c16 == 45) || ((c16 == 43) || ((c16 == 46) || ((c16 == 101) || (c16 == 69)))))) {
							var j5 int = (i2 + 1)
							for ; ; j5 = (j5 + 1) {
								if (j5 < 0) {
									break
								}
								if (j5 >= len(src2)) {
									break
								}
								var c17 int = int(src2[j5])
								if (((c17 >= 48) && (c17 <= 57)) || ((c17 == 45) || ((c17 == 43) || ((c17 == 46) || ((c17 == 101) || (c17 == 69)))))) {
									continue
								}
								break
							}
							t40 = j5
						} else {
							var j6 int = (i2 + 1)
							for ; ; j6 = (j6 + 1) {
								if (j6 < 0) {
									break
								}
								if (j6 >= len(src2)) {
									break
								}
								var c18 int = int(src2[j6])
								if ((c18 >= 97) && (c18 <= 122)) {
									continue
								}
								break
							}
							t40 = j6
						}
						t38 = t40
					}
					var ni2 int = t38
					nodes7[((4 * nn2) + 0)] = tg2
					nodes7[((4 * nn2) + 1)] = (ni2 - i2)
					nodes9 := nodes7
					var t41 []int
					if (sp3 < 1) {
						t41 = nodes9
					} else {
						var lc4 int = stk5[((2 * (sp3 - 1)) + 1)]
						var t42 []int
						if (lc4 == 0) {
							nodes9[((4 * stk5[((2 * (sp3 - 1)) + 0)]) + 2)] = nn2
							t42 = nodes9
						} else {
							nodes9[((4 * lc4) + 3)] = nn2
							t42 = nodes9
						}
						t41 = t42
					}
					var t43 []int
					if (sp3 < 1) {
						t43 = stk5
					} else {
						stk5[((2 * (sp3 - 1)) + 1)] = nn2
						t43 = stk5
					}
					nodes7, stk5, i2, nn2 = t41, t43, ni2, (nn2 + 1)
					continue
				}
				i2, ok2 = (i2 + 1), 0
				continue
			}
			nodes10 := r26
			wl3 := make([]int, (2 * 512))
			wl3[0] = 1
			wl3[1] = 1
			wl4 := wl3
			var sp4 int = 1
			var seen2 int = 0
			var acc2 int = 0
			var steps2 int = 0
			var r44 int
			for ; ; seen2, steps2 = (seen2 + 1), (steps2 + 1) {
				if (steps2 >= (2 * 512)) {
					r44 = ((seen2 * 1000) + acc2)
					break
				}
				if (sp4 < 1) {
					r44 = ((seen2 * 1000) + acc2)
					break
				}
				if (sp4 >= 512) {
					r44 = ((seen2 * 1000) + acc2)
					break
				}
				var n2 int = wl4[((2 * (sp4 - 1)) + 0)]
				var d2 int = wl4[((2 * (sp4 - 1)) + 1)]
				var sb2 int = nodes10[((4 * n2) + 3)]
				var kd2 int = nodes10[((4 * n2) + 2)]
				var s12 int = (sp4 - 1)
				var t45 []int
				if (sb2 == 0) {
					t45 = wl4
				} else {
					wl4[((2 * s12) + 0)] = sb2
					wl4[((2 * s12) + 1)] = d2
					t45 = wl4
				}
				w12 := t45
				var t46 int
				if (sb2 == 0) {
					t46 = s12
				} else {
					t46 = (s12 + 1)
				}
				var s22 int = t46
				var t47 []int
				if (kd2 == 0) {
					t47 = w12
				} else {
					w12[((2 * s22) + 0)] = kd2
					w12[((2 * s22) + 1)] = (d2 + 1)
					t47 = w12
				}
				w22 := t47
				var t48 int
				if (kd2 == 0) {
					t48 = s22
				} else {
					t48 = (s22 + 1)
				}
				wl4, sp4, acc2 = w22, t48, (acc2 + (nodes10[((4 * n2) + 0)] * d2))
				continue
			}
			t25 = (((nodes10[0] - 1) * 1000000) + ((r44 * 10) + nodes10[1]))
		} else {
			var t49 int
			if (k == 2) {
				src3 := []byte{91, 91, 49, 93, 44, 50, 93}
				nodes11 := make([]int, (4 * 512))
				stk7 := make([]int, (2 * 32))
				nodes12 := nodes11
				stk8 := stk7
				var i3 int = 0
				var nn3 int = 1
				var sp5 int = 0
				var ok3 int = 1
				var r50 []int
				for {
					if (i3 < 0) {
						nodes12[0] = nn3
						nodes12[1] = 0
						r50 = nodes12
						break
					}
					if (i3 >= len(src3)) {
						nodes12[0] = nn3
						var t51 int
						if (sp5 == 0) {
							t51 = ok3
						} else {
							t51 = 0
						}
						nodes12[1] = t51
						r50 = nodes12
						break
					}
					if (nn3 >= 512) {
						nodes12[0] = nn3
						nodes12[1] = 0
						r50 = nodes12
						break
					}
					if (sp5 >= 32) {
						nodes12[0] = nn3
						nodes12[1] = 0
						r50 = nodes12
						break
					}
					var c19 int = int(src3[i3])
					if ((c19 == 32) || ((c19 == 9) || ((c19 == 10) || (c19 == 13)))) {
						i3 = (i3 + 1)
						continue
					}
					var c20 int = int(src3[i3])
					if ((c20 == 58) || (c20 == 44)) {
						i3 = (i3 + 1)
						continue
					}
					var c21 int = int(src3[i3])
					if ((c21 == 123) || (c21 == 91)) {
						var t52 int
						if (int(src3[i3]) == 123) {
							t52 = 5
						} else {
							t52 = 4
						}
						nodes12[((4 * nn3) + 0)] = t52
						nodes12[((4 * nn3) + 1)] = 0
						nodes13 := nodes12
						var t53 []int
						if (sp5 < 1) {
							t53 = nodes13
						} else {
							var lc5 int = stk8[((2 * (sp5 - 1)) + 1)]
							var t54 []int
							if (lc5 == 0) {
								nodes13[((4 * stk8[((2 * (sp5 - 1)) + 0)]) + 2)] = nn3
								t54 = nodes13
							} else {
								nodes13[((4 * lc5) + 3)] = nn3
								t54 = nodes13
							}
							t53 = t54
						}
						var t55 []int
						if (sp5 < 1) {
							t55 = stk8
						} else {
							stk8[((2 * (sp5 - 1)) + 1)] = nn3
							t55 = stk8
						}
						stk9 := t55
						stk9[((2 * sp5) + 0)] = nn3
						stk9[((2 * sp5) + 1)] = 0
						nodes12, stk8, i3, nn3, sp5 = t53, stk9, (i3 + 1), (nn3 + 1), (sp5 + 1)
						continue
					}
					var c22 int = int(src3[i3])
					if ((c22 == 125) || (c22 == 93)) {
						var t56 int
						if (sp5 < 1) {
							t56 = 0
						} else {
							t56 = (sp5 - 1)
						}
						var t57 int
						if (sp5 < 1) {
							t57 = 0
						} else {
							var t58 int
							if (int(src3[i3]) == 125) {
								t58 = 5
							} else {
								t58 = 4
							}
							var t59 int
							if (nodes12[((4 * stk8[((2 * (sp5 - 1)) + 0)]) + 0)] == t58) {
								t59 = ok3
							} else {
								t59 = 0
							}
							t57 = t59
						}
						i3, sp5, ok3 = (i3 + 1), t56, t57
						continue
					}
					var c23 int = int(src3[i3])
					if ((c23 == 34) || ((((c23 >= 48) && (c23 <= 57)) || ((c23 == 45) || ((c23 == 43) || ((c23 == 46) || ((c23 == 101) || (c23 == 69)))))) || ((c23 >= 97) && (c23 <= 122)))) {
						var t60 int
						if (int(src3[i3]) == 34) {
							t60 = 2
						} else {
							var c24 int = int(src3[i3])
							var t61 int
							if (((c24 >= 48) && (c24 <= 57)) || ((c24 == 45) || ((c24 == 43) || ((c24 == 46) || ((c24 == 101) || (c24 == 69)))))) {
								t61 = 1
							} else {
								t61 = 3
							}
							t60 = t61
						}
						var tg3 int = t60
						var t62 int
						if (int(src3[i3]) == 34) {
							var j7 int = (i3 + 1)
							var r63 int
							for {
								if (j7 < 0) {
									r63 = j7
									break
								}
								if (j7 >= len(src3)) {
									r63 = j7
									break
								}
								if (int(src3[j7]) == 92) {
									j7 = (j7 + 2)
									continue
								}
								if (int(src3[j7]) == 34) {
									r63 = (j7 + 1)
									break
								}
								j7 = (j7 + 1)
								continue
							}
							t62 = r63
						} else {
							var c25 int = int(src3[i3])
							var t64 int
							if (((c25 >= 48) && (c25 <= 57)) || ((c25 == 45) || ((c25 == 43) || ((c25 == 46) || ((c25 == 101) || (c25 == 69)))))) {
								var j8 int = (i3 + 1)
								for ; ; j8 = (j8 + 1) {
									if (j8 < 0) {
										break
									}
									if (j8 >= len(src3)) {
										break
									}
									var c26 int = int(src3[j8])
									if (((c26 >= 48) && (c26 <= 57)) || ((c26 == 45) || ((c26 == 43) || ((c26 == 46) || ((c26 == 101) || (c26 == 69)))))) {
										continue
									}
									break
								}
								t64 = j8
							} else {
								var j9 int = (i3 + 1)
								for ; ; j9 = (j9 + 1) {
									if (j9 < 0) {
										break
									}
									if (j9 >= len(src3)) {
										break
									}
									var c27 int = int(src3[j9])
									if ((c27 >= 97) && (c27 <= 122)) {
										continue
									}
									break
								}
								t64 = j9
							}
							t62 = t64
						}
						var ni3 int = t62
						nodes12[((4 * nn3) + 0)] = tg3
						nodes12[((4 * nn3) + 1)] = (ni3 - i3)
						nodes14 := nodes12
						var t65 []int
						if (sp5 < 1) {
							t65 = nodes14
						} else {
							var lc6 int = stk8[((2 * (sp5 - 1)) + 1)]
							var t66 []int
							if (lc6 == 0) {
								nodes14[((4 * stk8[((2 * (sp5 - 1)) + 0)]) + 2)] = nn3
								t66 = nodes14
							} else {
								nodes14[((4 * lc6) + 3)] = nn3
								t66 = nodes14
							}
							t65 = t66
						}
						var t67 []int
						if (sp5 < 1) {
							t67 = stk8
						} else {
							stk8[((2 * (sp5 - 1)) + 1)] = nn3
							t67 = stk8
						}
						nodes12, stk8, i3, nn3 = t65, t67, ni3, (nn3 + 1)
						continue
					}
					i3, ok3 = (i3 + 1), 0
					continue
				}
				nodes15 := r50
				wl5 := make([]int, (2 * 512))
				wl5[0] = 1
				wl5[1] = 1
				wl6 := wl5
				var sp6 int = 1
				var seen3 int = 0
				var acc3 int = 0
				var steps3 int = 0
				var r68 int
				for ; ; seen3, steps3 = (seen3 + 1), (steps3 + 1) {
					if (steps3 >= (2 * 512)) {
						r68 = ((seen3 * 1000) + acc3)
						break
					}
					if (sp6 < 1) {
						r68 = ((seen3 * 1000) + acc3)
						break
					}
					if (sp6 >= 512) {
						r68 = ((seen3 * 1000) + acc3)
						break
					}
					var n3 int = wl6[((2 * (sp6 - 1)) + 0)]
					var d3 int = wl6[((2 * (sp6 - 1)) + 1)]
					var sb3 int = nodes15[((4 * n3) + 3)]
					var kd3 int = nodes15[((4 * n3) + 2)]
					var s13 int = (sp6 - 1)
					var t69 []int
					if (sb3 == 0) {
						t69 = wl6
					} else {
						wl6[((2 * s13) + 0)] = sb3
						wl6[((2 * s13) + 1)] = d3
						t69 = wl6
					}
					w13 := t69
					var t70 int
					if (sb3 == 0) {
						t70 = s13
					} else {
						t70 = (s13 + 1)
					}
					var s23 int = t70
					var t71 []int
					if (kd3 == 0) {
						t71 = w13
					} else {
						w13[((2 * s23) + 0)] = kd3
						w13[((2 * s23) + 1)] = (d3 + 1)
						t71 = w13
					}
					w23 := t71
					var t72 int
					if (kd3 == 0) {
						t72 = s23
					} else {
						t72 = (s23 + 1)
					}
					wl6, sp6, acc3 = w23, t72, (acc3 + (nodes15[((4 * n3) + 0)] * d3))
					continue
				}
				t49 = (((nodes15[0] - 1) * 1000000) + ((r68 * 10) + nodes15[1]))
			} else {
				src4 := []byte{123, 34, 97, 34, 58, 91, 49, 44, 50, 93, 44, 34, 98, 34, 58, 116, 114, 117, 101, 125}
				nodes16 := make([]int, (4 * 512))
				stk10 := make([]int, (2 * 32))
				nodes17 := nodes16
				stk11 := stk10
				var i4 int = 0
				var nn4 int = 1
				var sp7 int = 0
				var ok4 int = 1
				var r73 []int
				for {
					if (i4 < 0) {
						nodes17[0] = nn4
						nodes17[1] = 0
						r73 = nodes17
						break
					}
					if (i4 >= len(src4)) {
						nodes17[0] = nn4
						var t74 int
						if (sp7 == 0) {
							t74 = ok4
						} else {
							t74 = 0
						}
						nodes17[1] = t74
						r73 = nodes17
						break
					}
					if (nn4 >= 512) {
						nodes17[0] = nn4
						nodes17[1] = 0
						r73 = nodes17
						break
					}
					if (sp7 >= 32) {
						nodes17[0] = nn4
						nodes17[1] = 0
						r73 = nodes17
						break
					}
					var c28 int = int(src4[i4])
					if ((c28 == 32) || ((c28 == 9) || ((c28 == 10) || (c28 == 13)))) {
						i4 = (i4 + 1)
						continue
					}
					var c29 int = int(src4[i4])
					if ((c29 == 58) || (c29 == 44)) {
						i4 = (i4 + 1)
						continue
					}
					var c30 int = int(src4[i4])
					if ((c30 == 123) || (c30 == 91)) {
						var t75 int
						if (int(src4[i4]) == 123) {
							t75 = 5
						} else {
							t75 = 4
						}
						nodes17[((4 * nn4) + 0)] = t75
						nodes17[((4 * nn4) + 1)] = 0
						nodes18 := nodes17
						var t76 []int
						if (sp7 < 1) {
							t76 = nodes18
						} else {
							var lc7 int = stk11[((2 * (sp7 - 1)) + 1)]
							var t77 []int
							if (lc7 == 0) {
								nodes18[((4 * stk11[((2 * (sp7 - 1)) + 0)]) + 2)] = nn4
								t77 = nodes18
							} else {
								nodes18[((4 * lc7) + 3)] = nn4
								t77 = nodes18
							}
							t76 = t77
						}
						var t78 []int
						if (sp7 < 1) {
							t78 = stk11
						} else {
							stk11[((2 * (sp7 - 1)) + 1)] = nn4
							t78 = stk11
						}
						stk12 := t78
						stk12[((2 * sp7) + 0)] = nn4
						stk12[((2 * sp7) + 1)] = 0
						nodes17, stk11, i4, nn4, sp7 = t76, stk12, (i4 + 1), (nn4 + 1), (sp7 + 1)
						continue
					}
					var c31 int = int(src4[i4])
					if ((c31 == 125) || (c31 == 93)) {
						var t79 int
						if (sp7 < 1) {
							t79 = 0
						} else {
							t79 = (sp7 - 1)
						}
						var t80 int
						if (sp7 < 1) {
							t80 = 0
						} else {
							var t81 int
							if (int(src4[i4]) == 125) {
								t81 = 5
							} else {
								t81 = 4
							}
							var t82 int
							if (nodes17[((4 * stk11[((2 * (sp7 - 1)) + 0)]) + 0)] == t81) {
								t82 = ok4
							} else {
								t82 = 0
							}
							t80 = t82
						}
						i4, sp7, ok4 = (i4 + 1), t79, t80
						continue
					}
					var c32 int = int(src4[i4])
					if ((c32 == 34) || ((((c32 >= 48) && (c32 <= 57)) || ((c32 == 45) || ((c32 == 43) || ((c32 == 46) || ((c32 == 101) || (c32 == 69)))))) || ((c32 >= 97) && (c32 <= 122)))) {
						var t83 int
						if (int(src4[i4]) == 34) {
							t83 = 2
						} else {
							var c33 int = int(src4[i4])
							var t84 int
							if (((c33 >= 48) && (c33 <= 57)) || ((c33 == 45) || ((c33 == 43) || ((c33 == 46) || ((c33 == 101) || (c33 == 69)))))) {
								t84 = 1
							} else {
								t84 = 3
							}
							t83 = t84
						}
						var tg4 int = t83
						var t85 int
						if (int(src4[i4]) == 34) {
							var j10 int = (i4 + 1)
							var r86 int
							for {
								if (j10 < 0) {
									r86 = j10
									break
								}
								if (j10 >= len(src4)) {
									r86 = j10
									break
								}
								if (int(src4[j10]) == 92) {
									j10 = (j10 + 2)
									continue
								}
								if (int(src4[j10]) == 34) {
									r86 = (j10 + 1)
									break
								}
								j10 = (j10 + 1)
								continue
							}
							t85 = r86
						} else {
							var c34 int = int(src4[i4])
							var t87 int
							if (((c34 >= 48) && (c34 <= 57)) || ((c34 == 45) || ((c34 == 43) || ((c34 == 46) || ((c34 == 101) || (c34 == 69)))))) {
								var j11 int = (i4 + 1)
								for ; ; j11 = (j11 + 1) {
									if (j11 < 0) {
										break
									}
									if (j11 >= len(src4)) {
										break
									}
									var c35 int = int(src4[j11])
									if (((c35 >= 48) && (c35 <= 57)) || ((c35 == 45) || ((c35 == 43) || ((c35 == 46) || ((c35 == 101) || (c35 == 69)))))) {
										continue
									}
									break
								}
								t87 = j11
							} else {
								var j12 int = (i4 + 1)
								for ; ; j12 = (j12 + 1) {
									if (j12 < 0) {
										break
									}
									if (j12 >= len(src4)) {
										break
									}
									var c36 int = int(src4[j12])
									if ((c36 >= 97) && (c36 <= 122)) {
										continue
									}
									break
								}
								t87 = j12
							}
							t85 = t87
						}
						var ni4 int = t85
						nodes17[((4 * nn4) + 0)] = tg4
						nodes17[((4 * nn4) + 1)] = (ni4 - i4)
						nodes19 := nodes17
						var t88 []int
						if (sp7 < 1) {
							t88 = nodes19
						} else {
							var lc8 int = stk11[((2 * (sp7 - 1)) + 1)]
							var t89 []int
							if (lc8 == 0) {
								nodes19[((4 * stk11[((2 * (sp7 - 1)) + 0)]) + 2)] = nn4
								t89 = nodes19
							} else {
								nodes19[((4 * lc8) + 3)] = nn4
								t89 = nodes19
							}
							t88 = t89
						}
						var t90 []int
						if (sp7 < 1) {
							t90 = stk11
						} else {
							stk11[((2 * (sp7 - 1)) + 1)] = nn4
							t90 = stk11
						}
						nodes17, stk11, i4, nn4 = t88, t90, ni4, (nn4 + 1)
						continue
					}
					i4, ok4 = (i4 + 1), 0
					continue
				}
				nodes20 := r73
				wl7 := make([]int, (2 * 512))
				wl7[0] = 1
				wl7[1] = 1
				wl8 := wl7
				var sp8 int = 1
				var seen4 int = 0
				var acc4 int = 0
				var steps4 int = 0
				var r91 int
				for ; ; seen4, steps4 = (seen4 + 1), (steps4 + 1) {
					if (steps4 >= (2 * 512)) {
						r91 = ((seen4 * 1000) + acc4)
						break
					}
					if (sp8 < 1) {
						r91 = ((seen4 * 1000) + acc4)
						break
					}
					if (sp8 >= 512) {
						r91 = ((seen4 * 1000) + acc4)
						break
					}
					var n4 int = wl8[((2 * (sp8 - 1)) + 0)]
					var d4 int = wl8[((2 * (sp8 - 1)) + 1)]
					var sb4 int = nodes20[((4 * n4) + 3)]
					var kd4 int = nodes20[((4 * n4) + 2)]
					var s14 int = (sp8 - 1)
					var t92 []int
					if (sb4 == 0) {
						t92 = wl8
					} else {
						wl8[((2 * s14) + 0)] = sb4
						wl8[((2 * s14) + 1)] = d4
						t92 = wl8
					}
					w14 := t92
					var t93 int
					if (sb4 == 0) {
						t93 = s14
					} else {
						t93 = (s14 + 1)
					}
					var s24 int = t93
					var t94 []int
					if (kd4 == 0) {
						t94 = w14
					} else {
						w14[((2 * s24) + 0)] = kd4
						w14[((2 * s24) + 1)] = (d4 + 1)
						t94 = w14
					}
					w24 := t94
					var t95 int
					if (kd4 == 0) {
						t95 = s24
					} else {
						t95 = (s24 + 1)
					}
					wl8, sp8, acc4 = w24, t95, (acc4 + (nodes20[((4 * n4) + 0)] * d4))
					continue
				}
				t49 = (((nodes20[0] - 1) * 1000000) + ((r91 * 10) + nodes20[1]))
			}
			t25 = t49
		}
		t1 = t25
	}
	return t1
}

