// Code generated by oroboros. DO NOT EDIT.

public final class examples_big_fact.java {
	public static java.math.BigInteger genFact(int v0) {
		final java.math.BigInteger v10 = (java.math.BigInteger.valueOf(1));
		java.math.BigInteger v13 = v10;
		int v14 = 2;
		for (;; v14 = (v14 + 1)) {
			final boolean v15 = (v14 > v0);
			if (v15) {
				break;
			}
			final java.math.BigInteger v20 = (java.math.BigInteger.valueOf(v14));
			final java.math.BigInteger v21 = (v13.multiply(v20));
			v13 = v21;
			continue;
		}
		return v13;
	}

}
