// Code generated by oroboros. DO NOT EDIT.

package gauntlet

import "fmt"
import "os"
import "unicode/utf8"

func GenMain() int {
	v0 := (func() []string { d := func(s string) string { b := make([]byte, 0, len(s)+8); for i := 0; i < len(s); { c := s[i]; if c < 0x80 { b = append(b, c); i++; continue }; n, lo, hi := 0, byte(0x80), byte(0xBF); switch { case c >= 0xC2 && c <= 0xDF: n = 1; case c == 0xE0: n, lo = 2, 0xA0; case c == 0xED: n, hi = 2, 0x9F; case c >= 0xE1 && c <= 0xEF: n = 2; case c == 0xF0: n, lo = 3, 0x90; case c == 0xF4: n, hi = 3, 0x8F; case c >= 0xF1 && c <= 0xF3: n = 3 }; j := i + 1; ok := n > 0; for k := 0; ok && k < n; k++ { if j >= len(s) || s[j] < lo || s[j] > hi { ok = false; break }; j++; lo, hi = 0x80, 0xBF }; if ok { b = append(b, s[i:j]...) } else { b = append(b, "\uFFFD"...) }; i = j }; return string(b) }; a := make([]string, len(os.Args)); for i, s := range os.Args { a[i] = d(s) }; return a }())
	v1 := len(v0)
	v3 := (v1 < 2)
	if v3 {
		fmt.Println("usage: roundtrip FILE")
		return 1
	}
	v10 := v0[1]
	v18 := []byte{104, 105, 32, 226, 130, 172, 10}
	v19 := (os.WriteFile(v10, v18, 0o666))
	v20 := (v19 == nil)
	if v20 {
		v21, v22 := os.ReadFile(v10)
		v23 := (v22 == nil)
		if v23 {
			v24 := (func(s string) string { if utf8.ValidString(s) { return s }; b := make([]byte, 0, len(s)+8); for i := 0; i < len(s); { c := s[i]; if c < 0x80 { b = append(b, c); i++; continue }; n, lo, hi := 0, byte(0x80), byte(0xBF); switch { case c >= 0xC2 && c <= 0xDF: n = 1; case c == 0xE0: n, lo = 2, 0xA0; case c == 0xED: n, hi = 2, 0x9F; case c >= 0xE1 && c <= 0xEF: n = 2; case c == 0xF0: n, lo = 3, 0x90; case c == 0xF4: n, hi = 3, 0x8F; case c >= 0xF1 && c <= 0xF3: n = 3 }; j := i + 1; ok := n > 0; for k := 0; ok && k < n; k++ { if j >= len(s) || s[j] < lo || s[j] > hi { ok = false; break }; j++; lo, hi = 0x80, 0xBF }; if ok { b = append(b, s[i:j]...) } else { b = append(b, "\uFFFD"...) }; i = j }; return string(b) }(string(v21)))
			fmt.Print(v24)
			v27 := (func(s string) string { b := make([]byte, 0, len(s)+8); for i := 0; i < len(s); { c := s[i]; if c < 0x80 { b = append(b, c); i++; continue }; n, lo, hi := 0, byte(0x80), byte(0xBF); switch { case c >= 0xC2 && c <= 0xDF: n = 1; case c == 0xE0: n, lo = 2, 0xA0; case c == 0xED: n, hi = 2, 0x9F; case c >= 0xE1 && c <= 0xEF: n = 2; case c == 0xF0: n, lo = 3, 0x90; case c == 0xF4: n, hi = 3, 0x8F; case c >= 0xF1 && c <= 0xF3: n = 3 }; j := i + 1; ok := n > 0; for k := 0; ok && k < n; k++ { if j >= len(s) || s[j] < lo || s[j] > hi { ok = false; break }; j++; lo, hi = 0x80, 0xBF }; if ok { b = append(b, s[i:j]...) } else { b = append(b, "\uFFFD"...) }; i = j }; return string(b) }(os.Getenv("ORO_ROUNDTRIP")))
			fmt.Println(v27)
			v29 := len(v21)
			fmt.Println(v29)
			v32 := (v10 + ".missing")
			_, v34 := os.ReadFile(v32)
			v35 := (v34 == nil)
			var v36 string
			if v35 {
				v36 = "found"
			} else {
				v38 := (os.IsNotExist(v34))
				if v38 {
					v36 = "not-found"
				} else {
					v40 := (os.IsExist(v34))
					if v40 {
						v36 = "exists"
					} else {
						v42 := (os.IsPermission(v34))
						if v42 {
							v36 = "permission"
						} else {
							v36 = "other"
						}
					}
				}
			}
			fmt.Println(v36)
			return 0
		}
		v48 := (os.IsNotExist(v22))
		var v49 string
		if v48 {
			v49 = "not-found"
		} else {
			v51 := (os.IsExist(v22))
			if v51 {
				v49 = "exists"
			} else {
				v53 := (os.IsPermission(v22))
				if v53 {
					v49 = "permission"
				} else {
					v49 = "other"
				}
			}
		}
		v56 := ("roundtrip: cannot read that file: " + v49)
		fmt.Println(v56)
		return 1
	}
	v60 := (os.IsNotExist(v19))
	var v61 string
	if v60 {
		v61 = "not-found"
	} else {
		v63 := (os.IsExist(v19))
		if v63 {
			v61 = "exists"
		} else {
			v65 := (os.IsPermission(v19))
			if v65 {
				v61 = "permission"
			} else {
				v61 = "other"
			}
		}
	}
	v68 := ("roundtrip: cannot write that file: " + v61)
	fmt.Println(v68)
	return 1
}

