// Code generated by oroboros. DO NOT EDIT.

export function genLimb(k) {
	const b = new Array(64).fill(0);
	let b2 = b;
	let i = 0;
	let r = 1;
	for (;; i = (i + 1), r = (r >> 24)) {
		if ((i >= 64)) {
			break;
		}
		b2[i] = (r & 16777215);
		continue;
	}
	let acc = b2;
	let i2 = 2;
	let sp1 = new Array(64).fill(0);
	for (;; i2 = (i2 + 1)) {
		if ((i2 > 200)) {
			break;
		}
		sp1.fill(0);
		const o = sp1;
		let o3 = o;
		let i1 = 0;
		let c = 0;
		for (;; i1 = (i1 + 1)) {
			if ((i1 >= 64)) {
				break;
			}
			const t145 = ((((i1 < 0) ? 0 : ((i1 >= acc.length) ? 0 : acc[i1])) * i2) + c);
			o3[i1] = (((t145 % 16777216) + 0));
			c = ((Math.trunc(t145 / 16777216) + 0));
			continue;
		}
		const sw2 = acc;
		acc = o3;
		sp1 = sw2;
		continue;
	}
	const t1452 = acc;
	return ((k < 0) ? 0 : ((k >= t1452.length) ? 0 : t1452[k]));
}

