// Code generated by oroboros. DO NOT EDIT.

export function genMain() {
	const v0 = (process.argv.slice(1));
	if ((v0.length < 2)) {
		console.log("usage: roundtrip FILE");
		return 1;
	}
	const v10 = v0[1];
	const v18 = [104, 105, 32, 226, 130, 172, 10];
	let v19;
	try { fs.writeFileSync(v10, Buffer.from(v18)); v19 = null; } catch (e) { v19 = e; }
	if ((v19 === null)) {
		let v21, v22;
		try { v21 = fs.readFileSync(v10); v22 = null; } catch (e) { v21 = null; v22 = e; }
		if ((v22 === null)) {
			process.stdout.write((new TextDecoder().decode(Uint8Array.from(v21))));
			const v27 = ((process.env["ORO_ROUNDTRIP"] ?? ""));
			console.log(v27);
			console.log(v21.length);
			return 0;
		}
		console.log("roundtrip: cannot read that file");
		return 1;
	}
	console.log("roundtrip: cannot write that file");
	return 1;
}

