// Code generated by oroboros. DO NOT EDIT.

package gauntlet

import "fmt"
import "os"

func GenMain() int {
	v0 := (func() []string { d := func(s string) string { b := make([]byte, 0, len(s)+8); for i := 0; i < len(s); { c := s[i]; if c < 0x80 { b = append(b, c); i++; continue }; n, lo, hi := 0, byte(0x80), byte(0xBF); switch { case c >= 0xC2 && c <= 0xDF: n = 1; case c == 0xE0: n, lo = 2, 0xA0; case c == 0xED: n, hi = 2, 0x9F; case c >= 0xE1 && c <= 0xEF: n = 2; case c == 0xF0: n, lo = 3, 0x90; case c == 0xF4: n, hi = 3, 0x8F; case c >= 0xF1 && c <= 0xF3: n = 3 }; j := i + 1; ok := n > 0; for k := 0; ok && k < n; k++ { if j >= len(s) || s[j] < lo || s[j] > hi { ok = false; break }; j++; lo, hi = 0x80, 0xBF }; if ok { b = append(b, s[i:j]...) } else { b = append(b, "\uFFFD"...) }; i = j }; return string(b) }; a := make([]string, len(os.Args)); for i, s := range os.Args { a[i] = d(s) }; return a }())
	v1 := len(v0)
	v3 := (v1 < 2)
	if v3 {
		fmt.Println("usage: count FILE")
		return 0
	}
	v10 := v0[1]
	v11, v12 := os.ReadFile(v10)
	v13 := (v12 == nil)
	if v13 {
		v14 := len(v11)
		v16 := (v14 >= 16777216)
		if v16 {
			fmt.Println("count: file is larger than this tool accepts")
			return 0
		}
		var v27 int = 0
		var v28 int = 0
		var v29 int = 0
		var v30 bool = false
		var v26 int
		for ; ; v27 = (v27 + 1) {
			v31 := len(v11)
			v32 := (v27 >= v31)
			if v32 {
				fmt.Println(v28)
				fmt.Println(v29)
				v37 := len(v11)
				fmt.Println(v37)
				v26 = v37
				break
			}
			v41 := int(v11[v27])
			v43 := (v41 == 10)
			if v43 {
				v46 := (v28 < 16777216)
				if v46 {
					v49 := (v28 + 1)
					v54 := (v41 == 32)
					v55 := (v54 || ((v41 >= 9) && (v41 <= 13)))
					if v55 {
						v28, v30 = v49, false
						continue
					}
					if v30 {
						v28 = v49
						continue
					}
					v73 := (v29 < 16777216)
					if v73 {
						v78 := (v29 + 1)
						v28, v29, v30 = v49, v78, true
						continue
					}
					v28 = v49
					continue
				}
				v88 := (v41 == 32)
				v89 := (v88 || ((v41 >= 9) && (v41 <= 13)))
				if v89 {
					v30 = false
					continue
				}
				if v30 {
					continue
				}
				v107 := (v29 < 16777216)
				if v107 {
					v112 := (v29 + 1)
					v29, v30 = v112, true
					continue
				}
				continue
			}
			v122 := (v41 == 32)
			v123 := (v122 || ((v41 >= 9) && (v41 <= 13)))
			if v123 {
				v30 = false
				continue
			}
			if v30 {
				continue
			}
			v141 := (v29 < 16777216)
			if v141 {
				v146 := (v29 + 1)
				v29, v30 = v146, true
				continue
			}
			continue
		}
		return v26
	}
	fmt.Println("count: cannot read that file")
	return 0
}

