// Code generated by oroboros. DO NOT EDIT.

public final class examples_native_smooth-java.java {
	public static double[] genSmoothAlloc(double[] v0) {
		final int v4 = v0.length;
		final int v6 = (v4 - 2);
		final int n1 = v6;
		final double[] v7 = new double[n1];
		for (int v8 = 0; v8 < n1; v8++) {
			double e2 = 0.0;
			final double v9 = v0[v8];
			final int v11 = (v8 + 1);
			final double v12 = v0[v11];
			final double v13 = (v9 + v12);
			final int v15 = (v8 + 2);
			final double v16 = v0[v15];
			final double v17 = (v13 + v16);
			final double v19 = (v17 / 3.0);
			e2 = v19;
			v7[v8] = e2;
		}
		return v7;
	}

	public static double[] genSmoothBuild(double[] v0) {
		final int v4 = v0.length;
		final int v6 = (v4 - 2);
		final double[] v8 = new double[v6];
		double[] v7 = null;
		double[] v11 = v8;
		int v12 = 0;
		for (;; v12 = (v12 + 1)) {
			final int v13 = v0.length;
			final int v15 = (v13 - 2);
			final boolean v16 = (v12 >= v15);
			if (v16) {
				break;
			}
			final double v19 = v0[v12];
			final int v21 = (v12 + 1);
			final double v22 = v0[v21];
			final double v23 = (v19 + v22);
			final int v25 = (v12 + 2);
			final double v26 = v0[v25];
			final double v27 = (v23 + v26);
			final double v29 = (v27 / 3.0);
			v11[v12] = v29;
			continue;
		}
		v7 = v11;
		return v7;
	}

	public static double[] genSmoothInto(double[] v0, double[] v1) {
		double[] v16 = v0;
		int v17 = 0;
		for (;; v17 = (v17 + 1)) {
			final int v18 = v1.length;
			final int v20 = (v18 - 2);
			final boolean v21 = (v17 >= v20);
			if (v21) {
				break;
			}
			final double v24 = v1[v17];
			final int v26 = (v17 + 1);
			final double v27 = v1[v26];
			final double v28 = (v24 + v27);
			final int v30 = (v17 + 2);
			final double v31 = v1[v30];
			final double v32 = (v28 + v31);
			final double v34 = (v32 / 3.0);
			v16[(int) v17] = v34;
			continue;
		}
		return v16;
	}

}
