// Code generated by oroboros. DO NOT EDIT.

package gauntlet

import "bufio"
import "fmt"
import "os"
import "strconv"
import "strings"

func GenMain() int {
	v0 := (os.Args)
	v1 := len(v0)
	v3 := (v1 < 2)
	var v4 string
	if v3 {
		v4 = "1"
	} else {
		v9 := v0[1]
		v4 = v9
	}
	v10, v11 := strconv.Atoi(v4)
	v14 := (v11 == nil)
	v15 := (v14 && ((v10 >= 1) && (v10 <= 65536)))
	var v24 int
	if v15 {
		v27 := (os.Stdin)
		v28 := (bufio.NewScanner(v27))
		v29 := (os.Stdout)
		v30 := (bufio.NewWriter(v29))
		var v35 int = 0
		var v36 int = 0
		var v37 int = 0
		var v34 int
		for ; ; v35 = (v35 + 1) {
			v38 := (v28.Scan())
			if v38 {
				v40 := (v35 >= 16777216)
				if v40 {
					v30.Flush()
					v43 := (os.Stderr)
					fmt.Fprintln(v43, "lines: more than 16777216 lines")
					v34 = 1
					break
				}
				v49 := (v28.Text())
				v50 := (strings.Fields(v49))
				v53 := (v35 + 1)
				fmt.Fprintf(v30, "%6d\t%s\n", v53, v49)
				v56 := len(v50)
				v57 := (v56 < v10)
				var v58 string
				if v57 {
					v58 = ""
				} else {
					v65 := (v10 - 1)
					v66 := v50[v65]
					v58 = v66
				}
				v69h, v70 := func(s string, b, n int) (int, error) { x, err := strconv.ParseInt(s, b, n); return int(x), err }(v58, 10, 64)
				v69 := int(v69h)
				v75 := (v70 == nil)
				v76 := (v75 && ((v69 >= -100000000000) && (v69 <= 100000000000)))
				var v85 int
				if v76 {
					v88 := (v36 + v69)
					v85 = v88
				} else {
					v85 = v36
				}
				v91 := (v70 == nil)
				v92 := (v91 && ((v69 >= -100000000000) && (v69 <= 100000000000)))
				var v101 int
				if v92 {
					v105 := (v37 + 1)
					v101 = v105
				} else {
					v101 = v37
				}
				v36, v37 = v85, v101
				continue
			}
			v106 := (v28.Err())
			v107 := (v106 == nil)
			if v107 {
				fmt.Fprintf(v30, "%d lines; column %d: %d values, sum ", v35, v10, v37)
				fmt.Fprintln(v30, v36)
				v113 := (v30.Flush())
				v114 := (v113 == nil)
				if v114 {
					v34 = 0
					break
				}
				v116 := (os.Stderr)
				fmt.Fprintln(v116, "lines: cannot write standard output")
				v34 = 1
				break
			}
			v30.Flush()
			v122 := (os.Stderr)
			fmt.Fprintln(v122, "lines: cannot read standard input")
			v34 = 1
			break
		}
		v24 = v34
	} else {
		v127 := (os.Stderr)
		fmt.Fprintln(v127, "usage: lines [COLUMN] < FILE    (COLUMN is 1 to 65536)")
		v24 = 1
	}
	os.Exit(v24)
	return v24
}

