// Code generated by oroboros. DO NOT EDIT.

public final class examples_big_limbs.java {
	public static long genLimb(long v0) {
		final int[] v3 = new int[64];
		int[] v2 = null;
		int[] v7 = v3;
		int v8 = 0;
		long v9 = 1;
		for (;; v8 = (v8 + 1)) {
			final boolean v11 = (v8 >= 64);
			if (v11) {
				break;
			}
			final long v15 = (v9 & 16777215);
			v7[v8] = (int) (v15);
			final long v20 = (v9 >> 24);
			v9 = v20;
			continue;
		}
		v2 = v7;
		int[] v23 = v2;
		int v24 = 2;
		int[] sp23 = new int[64];
		for (;; v24 = (v24 + 1)) {
			final boolean v26 = (v24 > 200);
			if (v26) {
				break;
			}
			java.util.Arrays.fill(sp23, (int) 0);
			final int[] v31 = sp23;
			int[] v30 = null;
			int[] v35 = v31;
			int v36 = 0;
			long v37 = 0;
			for (;; v36 = (v36 + 1)) {
				final boolean v39 = (v36 >= 64);
				if (v39) {
					break;
				}
				final boolean v43 = (v36 < 0);
				long v44 = 0;
				if (v43) {
					v44 = 0;
				} else {
					final int v48 = v23.length;
					final boolean v49 = (v36 >= v48);
					if (v49) {
						v44 = 0;
					} else {
						final long v55 = v23[v36];
						v44 = v55;
					}
				}
				final long v56 = (v44 * v24);
				final long v57 = (v56 + v37);
				final long v59 = (v57 & 16777215);
				v35[v36] = (int) (v59);
				final long v64 = (v57 >> 24);
				v37 = v64;
				continue;
			}
			v30 = v35;
			sp23 = v23;
			v23 = v30;
			continue;
		}
		final boolean v68 = (v0 < 0);
		if (v68) {
			return 0;
		}
		final int v72 = v23.length;
		final boolean v73 = (v0 >= v72);
		if (v73) {
			return 0;
		}
		final long v79 = v23[(int) v0];
		return v79;
	}

}
