// Code generated by oroboros. DO NOT EDIT.

package gauntlet

func GenSumRange(v0 int) int {
	var v12 int = 0
	var v13 int = 0
	for ; ; v12 = (v12 + 1) {
		v14 := (v12 >= v0)
		if v14 {
			break
		}
		v21 := (v13 + v12)
		v13 = v21
		continue
	}
	return v13
}

