// Code generated by oroboros. DO NOT EDIT.

package gauntlet

import "math/big"

func GenRender(x *big.Int) string {
	var t1 string
	if (x.Cmp((big.NewInt(int64(0)))) == 0) {
		t1 = "0"
	} else {
		s := ""
		v := x
		var i int = 0
		for ; ; i = (i + 1) {
			if (v.Cmp((big.NewInt(int64(0)))) == 0) {
				break
			}
			if (i >= 32) {
				break
			}
			nv19 := (func(oroZ *big.Int, oroK int) *big.Int { if oroZ.Sign() < 0 || oroZ.BitLen() > oroK { panic("bignum overflow: the declared range is too small") }; return oroZ }((new(big.Int).Quo(v, (big.NewInt(int64(100000000))))), 201))
			s2 := ""
			var k int = 0
			var r int = (int(new(big.Int).Rem(v, big.NewInt(int64(100000000))).Int64()))
			for ; ; k, r = (k + 1), (r / 10) {
				if (k >= 8) {
					break
				}
				if ((!(nv19.Cmp((big.NewInt(int64(0)))) > 0)) && ((r == 0) && (k > 0))) {
					break
				}
				s2 = ((string(rune((48 + (r % 10))))) + s2)
				continue
			}
			s, v = (s2 + s), nv19
			continue
		}
		t1 = s
	}
	return t1
}

