// Code generated by oroboros. DO NOT EDIT.

package gauntlet

func GenSumPositive(v0 []float64) float64 {
	var v4 float64 = 0.0
	var v5 int = 0
	for ; ; v5 = (v5 + 1) {
		v6 := len(v0)
		v7 := (v5 >= v6)
		if v7 {
			break
		}
		v12 := v0[v5]
		v14 := (v12 > 0.0)
		var v15 float64
		if v14 {
			v16 := (v4 + v12)
			v15 = v16
		} else {
			v15 = v4
		}
		v4 = v15
		continue
	}
	return v4
}

