// Code generated by oroboros. DO NOT EDIT.

export function genSmooth(a) {
	const dst = (new Float64Array(((a.length) - 2)));
	let d = dst;
	let i = 0;
	for (;; i = (i + 1)) {
		if ((i >= ((a.length) - 2))) {
			return d;
		}
		d[i] = ((((a[i]) + (a[(i + 1)])) + (a[(i + 2)])) / 3);
		continue;
	}
}

export function genSmoothInto(dst, a) {
	let d = dst;
	let i = 0;
	for (;; i = (i + 1)) {
		if ((i >= ((a.length) - 2))) {
			return d;
		}
		d[i] = ((((a[i]) + (a[(i + 1)])) + (a[(i + 2)])) / 3);
		continue;
	}
}

