; Code generated by oroboros. DO NOT EDIT.

option casemap:none


.data
LS3 db 062h,069h,067h,0
LS3_len equ 3
LS4 db 0
LS4_len equ 0
LS8 db 074h,06Fh,06Fh,020h,06Ch,061h,072h,067h,065h,0
LS8_len equ 9

.code
gen_label proc
        push rbx
        sub rsp, 48
        mov rbx, rcx
        cmp rbx, 5
        jle Lelse2
        mov rax, 0
        lea rdx, LS3
        jmp Lret1
Lelse2:
        mov rax, 1
        lea rdx, LS4
Lret1:
        add rsp, 48
        pop rbx
        ret
gen_label endp

gen_parse proc
        push rbx
        sub rsp, 48
        mov rbx, rcx
        cmp rbx, 50
        jge Lelse6
        imul rbx, 2
        mov rax, 0
        mov rdx, rbx
        lea r8, LS4
        jmp Lret5
Lelse6:
        mov rax, 1
        mov rdx, 0
        lea r8, LS8
Lret5:
        add rsp, 48
        pop rbx
        ret
gen_parse endp

gen_save proc
        push rbx
        push rsi
        sub rsp, 56
        mov rbx, rcx
        mov rsi, rbx
        and rsi, 1
        cmp rsi, 0
        jne Lelse11
        mov rax, 0
        mov rdx, 0
        mov r8, 0
        jmp Lret9
Lelse11:
        mov rax, 1
        mov rdx, 0
        mov r8, rbx
Lret9:
        add rsp, 56
        pop rsi
        pop rbx
        ret
gen_save endp


end
