// Code generated by oroboros. DO NOT EDIT.

package gauntlet

import "strings"

func GenSumOf(a []float64) float64 {
	acc := 0.0
	var i int = 0
	for ; ; i = (i + 1) {
		if (i >= (len(a))) {
			break
		}
		acc = (acc + (a[i]))
		continue
	}
	return acc
}

func GenWordTally(text string) map[string]int {
	ws := (strings.Fields(text))
	init := (make(map[string]int))
	acc := init
	var i int = 0
	for ; ; i = (i + 1) {
		if (i >= (len(ws))) {
			break
		}
		acc[(ws[i])]++
		continue
	}
	return acc
}

