// Code generated by oroboros. DO NOT EDIT.

package gauntlet

import "fmt"
import "math/bits"
import "strconv"

func GenMain() int {
	v4 := (uint64(0))
	v5 := (uint64(1))
	var v7 int = 0
	v8 := v4
	v9 := v5
	var v10 int = 0
	var v6 int
	for ; ; v7 = (v7 + 1) {
		v12 := (v10 == 1)
		if v12 {
			fmt.Println(v7, "overflows 128 bits")
			v6 = v7
			break
		}
		v20 := (v7 > 40)
		if v20 {
			v6 = 0
			break
		}
		v26 := v8
		v27 := v9
		var v28 string = ""
		var v25 string
		for {
			v32 := (uint64(0))
			v33 := ((v26 == v32))
			v34 := (v33 && ((v27 < (uint64(1000000000000000000)))))
			if v34 {
				v44 := (strconv.FormatUint(uint64(v27), 10))
				v45 := (v44 + v28)
				v25 = v45
				break
			}
			v47 := (uint64(1000000000000000000))
			v48 := ((v26 / v47))
			v51 := (uint64(1000000000000000000))
			v52 := ((v26 % v51))
			v55 := (uint64(1000000000000000000))
			v56, _ := bits.Div64(uint64(v52), uint64(v27), uint64(v55))
			v60 := (uint64(1000000000000000000))
			v61 := (bits.Rem64(uint64(v26), uint64(v27), uint64(v60)))
			v63 := (int(v61))
			var v65 int = 0
			var v66 int = v63
			var v67 string = ""
			for ; ; v65 = (v65 + 1) {
				v69 := (v65 >= 18)
				if v69 {
					break
				}
				v75 := (v66 / 10)
				v78 := (v66 % 10)
				v79 := (48 + v78)
				v80 := (string(rune(v79)))
				v81 := (v80 + v67)
				v66, v67 = v75, v81
				continue
			}
			v82 := (v67 + v28)
			v26, v27, v28 = v48, v56, v82
			continue
		}
		fmt.Println(v7, v25)
		v87 := (v7 + 1)
		v88 := (uint64(v87))
		v89, v90 := bits.Mul64(uint64(v9), uint64(v88))
		v91 := (uint64(v87))
		v92, v93 := bits.Mul64(uint64(v8), uint64(v91))
		v95 := (uint64(0))
		v96, v97h := func(x, y, c uint64) (uint64, int) { s, o := bits.Add64(x, y, c); return s, int(o) }(uint64(v93), uint64(v89), uint64(v95))
		v97 := int(v97h)
		v103 := (uint64(0))
		v104 := ((v92 == v103))
		v105 := (v104 && (v97 == 0))
		var v111 int
		if v105 {
			v111 = 0
		} else {
			v111 = 1
		}
		v8, v9, v10 = v96, v90, v111
		continue
	}
	return v6
}

