// Code generated by oroboros. DO NOT EDIT.

package gauntlet

import "fmt"
import "os"
import "unicode/utf8"

func GenMain() string {
	av := (func() []string { d := func(s string) string { b := make([]byte, 0, len(s)+8); for i := 0; i < len(s); { c := s[i]; if c < 0x80 { b = append(b, c); i++; continue }; n, lo, hi := 0, byte(0x80), byte(0xBF); switch { case c >= 0xC2 && c <= 0xDF: n = 1; case c == 0xE0: n, lo = 2, 0xA0; case c == 0xED: n, hi = 2, 0x9F; case c >= 0xE1 && c <= 0xEF: n = 2; case c == 0xF0: n, lo = 3, 0x90; case c == 0xF4: n, hi = 3, 0x8F; case c >= 0xF1 && c <= 0xF3: n = 3 }; j := i + 1; ok := n > 0; for k := 0; ok && k < n; k++ { if j >= len(s) || s[j] < lo || s[j] > hi { ok = false; break }; j++; lo, hi = 0x80, 0xBF }; if ok { b = append(b, s[i:j]...) } else { b = append(b, "\uFFFD"...) }; i = j }; return string(b) }; a := make([]string, len(os.Args)); for i, s := range os.Args { a[i] = d(s) }; return a }())
	var t1 string
	if (len(av) < 2) {
		fmt.Println("usage: freq FILE")
		t1 = "usage: freq FILE"
	} else {
		src, err := os.ReadFile(av[1])
		var t2 string
		if (err == nil) {
			var t3 string
			if (len(src) >= 65536) {
				fmt.Println("freq: file is larger than this tool accepts")
				t3 = "freq: file is larger than this tool accepts"
			} else {
				var n int = 0
				var i int = 0
				for {
					if (i >= len(src)) {
						break
					}
					if (n >= 32768) {
						break
					}
					var c int = int(src[i])
					if (((c >= 65) && (c <= 90)) || ((c >= 97) && (c <= 122))) {
						var j int = (i + 1)
						for ; ; j = (j + 1) {
							if (j < 0) {
								break
							}
							if (j >= len(src)) {
								break
							}
							var c2 int = int(src[j])
							if (((c2 >= 65) && (c2 <= 90)) || ((c2 >= 97) && (c2 <= 122))) {
								continue
							}
							break
						}
						n, i = (n + 1), j
						continue
					}
					i = (i + 1)
					continue
				}
				var nw int = n
				sp := make([]int, (2 * nw))
				sp2 := sp
				var i2 int = 0
				var w int = 0
				for {
					if (i2 >= len(src)) {
						break
					}
					if (w >= nw) {
						break
					}
					var c3 int = int(src[i2])
					if (((c3 >= 65) && (c3 <= 90)) || ((c3 >= 97) && (c3 <= 122))) {
						var j2 int = (i2 + 1)
						for ; ; j2 = (j2 + 1) {
							if (j2 < 0) {
								break
							}
							if (j2 >= len(src)) {
								break
							}
							var c4 int = int(src[j2])
							if (((c4 >= 65) && (c4 <= 90)) || ((c4 >= 97) && (c4 <= 122))) {
								continue
							}
							break
						}
						var ni17 int = j2
						sp2[(2 * w)] = i2
						sp2[((2 * w) + 1)] = ni17
						i2, w = ni17, (w + 1)
						continue
					}
					i2 = (i2 + 1)
					continue
				}
				sp3 := sp2
				a := make([]int, nw)
				b := make([]int, nw)
				a32 := a
				var k int = 0
				for ; ; k = (k + 1) {
					if (k >= nw) {
						break
					}
					var t4 int
					if (k < 0) {
						t4 = 0
					} else {
						var t5 int
						if (k >= nw) {
							t5 = 0
						} else {
							t5 = k
						}
						t4 = t5
					}
					a32[t4] = k
					continue
				}
				a3 := a32
				b2 := b
				var w2 int = 1
				for ; ; w2 = (2 * w2) {
					if (w2 >= nw) {
						break
					}
					if (w2 >= 32768) {
						break
					}
					b22 := b2
					var lo int = 0
					for {
						if (lo >= nw) {
							break
						}
						var b3 int = (lo + w2)
						var t6 int
						if (nw < b3) {
							t6 = nw
						} else {
							t6 = b3
						}
						var mid163 int = t6
						var b32 int = (lo + (2 * w2))
						var t7 int
						if (nw < b32) {
							t7 = nw
						} else {
							t7 = b32
						}
						var hi163 int = t7
						b33 := b22
						var i3 int = lo
						var j3 int = mid163
						var k2 int = lo
						for {
							if (k2 >= hi163) {
								break
							}
							if (i3 >= mid163) {
								var t8 int
								if (k2 < 0) {
									t8 = 0
								} else {
									var t9 int
									if (k2 >= nw) {
										t9 = 0
									} else {
										t9 = k2
									}
									t8 = t9
								}
								var t10 int
								if (j3 < 0) {
									t10 = 0
								} else {
									var t11 int
									if (j3 >= nw) {
										t11 = 0
									} else {
										t11 = j3
									}
									t10 = t11
								}
								b33[t8] = a3[t10]
								j3, k2 = (j3 + 1), (k2 + 1)
								continue
							}
							if (j3 >= hi163) {
								var t12 int
								if (k2 < 0) {
									t12 = 0
								} else {
									var t13 int
									if (k2 >= nw) {
										t13 = 0
									} else {
										t13 = k2
									}
									t12 = t13
								}
								var t14 int
								if (i3 < 0) {
									t14 = 0
								} else {
									var t15 int
									if (i3 >= nw) {
										t15 = 0
									} else {
										t15 = i3
									}
									t14 = t15
								}
								b33[t12] = a3[t14]
								i3, k2 = (i3 + 1), (k2 + 1)
								continue
							}
							var t16 int
							if (j3 < 0) {
								t16 = 0
							} else {
								var t17 int
								if (j3 >= nw) {
									t17 = 0
								} else {
									t17 = j3
								}
								t16 = t17
							}
							var u int = a3[t16]
							var t18 int
							if (i3 < 0) {
								t18 = 0
							} else {
								var t19 int
								if (i3 >= nw) {
									t19 = 0
								} else {
									t19 = i3
								}
								t18 = t19
							}
							var v int = a3[t18]
							var k22 int = 0
							var r20 int
							for ; ; k22 = (k22 + 1) {
								var d9 int = (sp3[((2 * u) + 1)] - sp3[(2 * u)])
								var t21 int
								if (d9 < 0) {
									t21 = 0
								} else {
									var t22 int
									if (d9 >= 65536) {
										t22 = 0
									} else {
										t22 = d9
									}
									t21 = t22
								}
								if (k22 >= t21) {
									var d92 int = (sp3[((2 * v) + 1)] - sp3[(2 * v)])
									var t23 int
									if (d92 < 0) {
										t23 = 0
									} else {
										var t24 int
										if (d92 >= 65536) {
											t24 = 0
										} else {
											t24 = d92
										}
										t23 = t24
									}
									if (k22 >= t23) {
										r20 = 0
										break
									}
									r20 = -1
									break
								}
								var d93 int = (sp3[((2 * v) + 1)] - sp3[(2 * v)])
								var t25 int
								if (d93 < 0) {
									t25 = 0
								} else {
									var t26 int
									if (d93 >= 65536) {
										t26 = 0
									} else {
										t26 = d93
									}
									t25 = t26
								}
								if (k22 >= t25) {
									r20 = 1
									break
								}
								var i22 int = (sp3[(2 * u)] + k22)
								var t27 int
								if (i22 < 0) {
									t27 = 0
								} else {
									var t28 int
									if (i22 >= len(src)) {
										t28 = 0
									} else {
										t28 = i22
									}
									t27 = t28
								}
								var c5 int = int(src[t27])
								var t29 int
								if ((c5 >= 65) && (c5 <= 90)) {
									t29 = (c5 + 32)
								} else {
									t29 = c5
								}
								var i23 int = (sp3[(2 * v)] + k22)
								var t30 int
								if (i23 < 0) {
									t30 = 0
								} else {
									var t31 int
									if (i23 >= len(src)) {
										t31 = 0
									} else {
										t31 = i23
									}
									t30 = t31
								}
								var c6 int = int(src[t30])
								var t32 int
								if ((c6 >= 65) && (c6 <= 90)) {
									t32 = (c6 + 32)
								} else {
									t32 = c6
								}
								if (t29 == t32) {
									continue
								}
								var i24 int = (sp3[(2 * u)] + k22)
								var t33 int
								if (i24 < 0) {
									t33 = 0
								} else {
									var t34 int
									if (i24 >= len(src)) {
										t34 = 0
									} else {
										t34 = i24
									}
									t33 = t34
								}
								var c7 int = int(src[t33])
								var t35 int
								if ((c7 >= 65) && (c7 <= 90)) {
									t35 = (c7 + 32)
								} else {
									t35 = c7
								}
								var i25 int = (sp3[(2 * v)] + k22)
								var t36 int
								if (i25 < 0) {
									t36 = 0
								} else {
									var t37 int
									if (i25 >= len(src)) {
										t37 = 0
									} else {
										t37 = i25
									}
									t36 = t37
								}
								var c8 int = int(src[t36])
								var t38 int
								if ((c8 >= 65) && (c8 <= 90)) {
									t38 = (c8 + 32)
								} else {
									t38 = c8
								}
								if (t35 < t38) {
									r20 = -1
									break
								}
								r20 = 1
								break
							}
							if (((0 <= u) && ((u < nw) && ((0 <= v) && (v < nw)))) && (r20 < 0)) {
								var t39 int
								if (k2 < 0) {
									t39 = 0
								} else {
									var t40 int
									if (k2 >= nw) {
										t40 = 0
									} else {
										t40 = k2
									}
									t39 = t40
								}
								var t41 int
								if (j3 < 0) {
									t41 = 0
								} else {
									var t42 int
									if (j3 >= nw) {
										t42 = 0
									} else {
										t42 = j3
									}
									t41 = t42
								}
								b33[t39] = a3[t41]
								j3, k2 = (j3 + 1), (k2 + 1)
								continue
							}
							var t43 int
							if (k2 < 0) {
								t43 = 0
							} else {
								var t44 int
								if (k2 >= nw) {
									t44 = 0
								} else {
									t44 = k2
								}
								t43 = t44
							}
							var t45 int
							if (i3 < 0) {
								t45 = 0
							} else {
								var t46 int
								if (i3 >= nw) {
									t46 = 0
								} else {
									t46 = i3
								}
								t45 = t46
							}
							b33[t43] = a3[t45]
							i3, k2 = (i3 + 1), (k2 + 1)
							continue
						}
						b22, lo = b33, hi163
						continue
					}
					a3, b2 = b22, a3
					continue
				}
				ord := a3
				var n2 int = 0
				var k3 int = 0
				for {
					if (k3 >= nw) {
						break
					}
					if (n2 >= 32768) {
						break
					}
					var t47 int
					if (k3 < 0) {
						t47 = 0
					} else {
						var t48 int
						if (k3 >= nw) {
							t48 = 0
						} else {
							t48 = k3
						}
						t47 = t48
					}
					var u2 int = ord[t47]
					var i4 int = (k3 - 1)
					var t49 int
					if (i4 < 0) {
						t49 = 0
					} else {
						var t50 int
						if (i4 >= nw) {
							t50 = 0
						} else {
							t50 = i4
						}
						t49 = t50
					}
					var v2 int = ord[t49]
					var k23 int = 0
					var r51 int
					for ; ; k23 = (k23 + 1) {
						var d94 int = (sp3[((2 * u2) + 1)] - sp3[(2 * u2)])
						var t52 int
						if (d94 < 0) {
							t52 = 0
						} else {
							var t53 int
							if (d94 >= 65536) {
								t53 = 0
							} else {
								t53 = d94
							}
							t52 = t53
						}
						if (k23 >= t52) {
							var d95 int = (sp3[((2 * v2) + 1)] - sp3[(2 * v2)])
							var t54 int
							if (d95 < 0) {
								t54 = 0
							} else {
								var t55 int
								if (d95 >= 65536) {
									t55 = 0
								} else {
									t55 = d95
								}
								t54 = t55
							}
							if (k23 >= t54) {
								r51 = 0
								break
							}
							r51 = -1
							break
						}
						var d96 int = (sp3[((2 * v2) + 1)] - sp3[(2 * v2)])
						var t56 int
						if (d96 < 0) {
							t56 = 0
						} else {
							var t57 int
							if (d96 >= 65536) {
								t57 = 0
							} else {
								t57 = d96
							}
							t56 = t57
						}
						if (k23 >= t56) {
							r51 = 1
							break
						}
						var i5 int = (sp3[(2 * u2)] + k23)
						var t58 int
						if (i5 < 0) {
							t58 = 0
						} else {
							var t59 int
							if (i5 >= len(src)) {
								t59 = 0
							} else {
								t59 = i5
							}
							t58 = t59
						}
						var c9 int = int(src[t58])
						var t60 int
						if ((c9 >= 65) && (c9 <= 90)) {
							t60 = (c9 + 32)
						} else {
							t60 = c9
						}
						var i6 int = (sp3[(2 * v2)] + k23)
						var t61 int
						if (i6 < 0) {
							t61 = 0
						} else {
							var t62 int
							if (i6 >= len(src)) {
								t62 = 0
							} else {
								t62 = i6
							}
							t61 = t62
						}
						var c10 int = int(src[t61])
						var t63 int
						if ((c10 >= 65) && (c10 <= 90)) {
							t63 = (c10 + 32)
						} else {
							t63 = c10
						}
						if (t60 == t63) {
							continue
						}
						var i7 int = (sp3[(2 * u2)] + k23)
						var t64 int
						if (i7 < 0) {
							t64 = 0
						} else {
							var t65 int
							if (i7 >= len(src)) {
								t65 = 0
							} else {
								t65 = i7
							}
							t64 = t65
						}
						var c11 int = int(src[t64])
						var t66 int
						if ((c11 >= 65) && (c11 <= 90)) {
							t66 = (c11 + 32)
						} else {
							t66 = c11
						}
						var i8 int = (sp3[(2 * v2)] + k23)
						var t67 int
						if (i8 < 0) {
							t67 = 0
						} else {
							var t68 int
							if (i8 >= len(src)) {
								t68 = 0
							} else {
								t68 = i8
							}
							t67 = t68
						}
						var c12 int = int(src[t67])
						var t69 int
						if ((c12 >= 65) && (c12 <= 90)) {
							t69 = (c12 + 32)
						} else {
							t69 = c12
						}
						if (t66 < t69) {
							r51 = -1
							break
						}
						r51 = 1
						break
					}
					if ((k3 == 0) || (!(r51 == 0))) {
						n2, k3 = (n2 + 1), (k3 + 1)
						continue
					}
					k3 = (k3 + 1)
					continue
				}
				var nd int = n2
				dt := make([]int, (2 * nd))
				dt2 := dt
				var k4 int = 0
				var d97 int = 0
				for {
					if (k4 >= nw) {
						break
					}
					if (nd < 1) {
						break
					}
					var t70 int
					if (k4 < 0) {
						t70 = 0
					} else {
						var t71 int
						if (k4 >= nw) {
							t71 = 0
						} else {
							t71 = k4
						}
						t70 = t71
					}
					var u3 int = ord[t70]
					var i9 int = (k4 - 1)
					var t72 int
					if (i9 < 0) {
						t72 = 0
					} else {
						var t73 int
						if (i9 >= nw) {
							t73 = 0
						} else {
							t73 = i9
						}
						t72 = t73
					}
					var v3 int = ord[t72]
					var k24 int = 0
					var r74 int
					for ; ; k24 = (k24 + 1) {
						var d10 int = (sp3[((2 * u3) + 1)] - sp3[(2 * u3)])
						var t75 int
						if (d10 < 0) {
							t75 = 0
						} else {
							var t76 int
							if (d10 >= 65536) {
								t76 = 0
							} else {
								t76 = d10
							}
							t75 = t76
						}
						if (k24 >= t75) {
							var d102 int = (sp3[((2 * v3) + 1)] - sp3[(2 * v3)])
							var t77 int
							if (d102 < 0) {
								t77 = 0
							} else {
								var t78 int
								if (d102 >= 65536) {
									t78 = 0
								} else {
									t78 = d102
								}
								t77 = t78
							}
							if (k24 >= t77) {
								r74 = 0
								break
							}
							r74 = -1
							break
						}
						var d103 int = (sp3[((2 * v3) + 1)] - sp3[(2 * v3)])
						var t79 int
						if (d103 < 0) {
							t79 = 0
						} else {
							var t80 int
							if (d103 >= 65536) {
								t80 = 0
							} else {
								t80 = d103
							}
							t79 = t80
						}
						if (k24 >= t79) {
							r74 = 1
							break
						}
						var i10 int = (sp3[(2 * u3)] + k24)
						var t81 int
						if (i10 < 0) {
							t81 = 0
						} else {
							var t82 int
							if (i10 >= len(src)) {
								t82 = 0
							} else {
								t82 = i10
							}
							t81 = t82
						}
						var c13 int = int(src[t81])
						var t83 int
						if ((c13 >= 65) && (c13 <= 90)) {
							t83 = (c13 + 32)
						} else {
							t83 = c13
						}
						var i11 int = (sp3[(2 * v3)] + k24)
						var t84 int
						if (i11 < 0) {
							t84 = 0
						} else {
							var t85 int
							if (i11 >= len(src)) {
								t85 = 0
							} else {
								t85 = i11
							}
							t84 = t85
						}
						var c14 int = int(src[t84])
						var t86 int
						if ((c14 >= 65) && (c14 <= 90)) {
							t86 = (c14 + 32)
						} else {
							t86 = c14
						}
						if (t83 == t86) {
							continue
						}
						var i12 int = (sp3[(2 * u3)] + k24)
						var t87 int
						if (i12 < 0) {
							t87 = 0
						} else {
							var t88 int
							if (i12 >= len(src)) {
								t88 = 0
							} else {
								t88 = i12
							}
							t87 = t88
						}
						var c15 int = int(src[t87])
						var t89 int
						if ((c15 >= 65) && (c15 <= 90)) {
							t89 = (c15 + 32)
						} else {
							t89 = c15
						}
						var i13 int = (sp3[(2 * v3)] + k24)
						var t90 int
						if (i13 < 0) {
							t90 = 0
						} else {
							var t91 int
							if (i13 >= len(src)) {
								t91 = 0
							} else {
								t91 = i13
							}
							t90 = t91
						}
						var c16 int = int(src[t90])
						var t92 int
						if ((c16 >= 65) && (c16 <= 90)) {
							t92 = (c16 + 32)
						} else {
							t92 = c16
						}
						if (t89 < t92) {
							r74 = -1
							break
						}
						r74 = 1
						break
					}
					if (((k4 == 0) || (!(r74 == 0))) && (d97 >= nd)) {
						break
					}
					var t93 int
					if (k4 < 0) {
						t93 = 0
					} else {
						var t94 int
						if (k4 >= nw) {
							t94 = 0
						} else {
							t94 = k4
						}
						t93 = t94
					}
					var u4 int = ord[t93]
					var i14 int = (k4 - 1)
					var t95 int
					if (i14 < 0) {
						t95 = 0
					} else {
						var t96 int
						if (i14 >= nw) {
							t96 = 0
						} else {
							t96 = i14
						}
						t95 = t96
					}
					var v4 int = ord[t95]
					var k25 int = 0
					var r97 int
					for ; ; k25 = (k25 + 1) {
						var d104 int = (sp3[((2 * u4) + 1)] - sp3[(2 * u4)])
						var t98 int
						if (d104 < 0) {
							t98 = 0
						} else {
							var t99 int
							if (d104 >= 65536) {
								t99 = 0
							} else {
								t99 = d104
							}
							t98 = t99
						}
						if (k25 >= t98) {
							var d105 int = (sp3[((2 * v4) + 1)] - sp3[(2 * v4)])
							var t100 int
							if (d105 < 0) {
								t100 = 0
							} else {
								var t101 int
								if (d105 >= 65536) {
									t101 = 0
								} else {
									t101 = d105
								}
								t100 = t101
							}
							if (k25 >= t100) {
								r97 = 0
								break
							}
							r97 = -1
							break
						}
						var d106 int = (sp3[((2 * v4) + 1)] - sp3[(2 * v4)])
						var t102 int
						if (d106 < 0) {
							t102 = 0
						} else {
							var t103 int
							if (d106 >= 65536) {
								t103 = 0
							} else {
								t103 = d106
							}
							t102 = t103
						}
						if (k25 >= t102) {
							r97 = 1
							break
						}
						var i15 int = (sp3[(2 * u4)] + k25)
						var t104 int
						if (i15 < 0) {
							t104 = 0
						} else {
							var t105 int
							if (i15 >= len(src)) {
								t105 = 0
							} else {
								t105 = i15
							}
							t104 = t105
						}
						var c17 int = int(src[t104])
						var t106 int
						if ((c17 >= 65) && (c17 <= 90)) {
							t106 = (c17 + 32)
						} else {
							t106 = c17
						}
						var i16 int = (sp3[(2 * v4)] + k25)
						var t107 int
						if (i16 < 0) {
							t107 = 0
						} else {
							var t108 int
							if (i16 >= len(src)) {
								t108 = 0
							} else {
								t108 = i16
							}
							t107 = t108
						}
						var c18 int = int(src[t107])
						var t109 int
						if ((c18 >= 65) && (c18 <= 90)) {
							t109 = (c18 + 32)
						} else {
							t109 = c18
						}
						if (t106 == t109) {
							continue
						}
						var i17 int = (sp3[(2 * u4)] + k25)
						var t110 int
						if (i17 < 0) {
							t110 = 0
						} else {
							var t111 int
							if (i17 >= len(src)) {
								t111 = 0
							} else {
								t111 = i17
							}
							t110 = t111
						}
						var c19 int = int(src[t110])
						var t112 int
						if ((c19 >= 65) && (c19 <= 90)) {
							t112 = (c19 + 32)
						} else {
							t112 = c19
						}
						var i18 int = (sp3[(2 * v4)] + k25)
						var t113 int
						if (i18 < 0) {
							t113 = 0
						} else {
							var t114 int
							if (i18 >= len(src)) {
								t114 = 0
							} else {
								t114 = i18
							}
							t113 = t114
						}
						var c20 int = int(src[t113])
						var t115 int
						if ((c20 >= 65) && (c20 <= 90)) {
							t115 = (c20 + 32)
						} else {
							t115 = c20
						}
						if (t112 < t115) {
							r97 = -1
							break
						}
						r97 = 1
						break
					}
					if ((k4 == 0) || (!(r97 == 0))) {
						var t116 int
						if (d97 < 0) {
							t116 = 0
						} else {
							var t117 int
							if (d97 >= nd) {
								t117 = 0
							} else {
								t117 = d97
							}
							t116 = t117
						}
						var t118 int
						if (k4 < 0) {
							t118 = 0
						} else {
							var t119 int
							if (k4 >= nw) {
								t119 = 0
							} else {
								t119 = k4
							}
							t118 = t119
						}
						dt2[(2 * t116)] = ord[t118]
						var t120 int
						if (d97 < 0) {
							t120 = 0
						} else {
							var t121 int
							if (d97 >= nd) {
								t121 = 0
							} else {
								t121 = d97
							}
							t120 = t121
						}
						dt2[((2 * t120) + 1)] = 1
						k4, d97 = (k4 + 1), (d97 + 1)
						continue
					}
					var i19 int = (d97 - 1)
					var t122 int
					if (i19 < 0) {
						t122 = 0
					} else {
						var t123 int
						if (i19 >= nd) {
							t123 = 0
						} else {
							t123 = i19
						}
						t122 = t123
					}
					var s19 int = t122
					dt2[((2 * s19) + 1)] = (dt2[((2 * s19) + 1)] + 1)
					k4 = (k4 + 1)
					continue
				}
				dt3 := dt2
				a2 := make([]int, nd)
				b4 := make([]int, nd)
				a42 := a2
				var k5 int = 0
				for ; ; k5 = (k5 + 1) {
					if (k5 >= nd) {
						break
					}
					var t124 int
					if (k5 < 0) {
						t124 = 0
					} else {
						var t125 int
						if (k5 >= nd) {
							t125 = 0
						} else {
							t125 = k5
						}
						t124 = t125
					}
					a42[t124] = k5
					continue
				}
				a4 := a42
				b5 := b4
				var w3 int = 1
				for ; ; w3 = (2 * w3) {
					if (w3 >= nd) {
						break
					}
					if (w3 >= 32768) {
						break
					}
					b23 := b5
					var lo2 int = 0
					for {
						if (lo2 >= nd) {
							break
						}
						var b34 int = (lo2 + w3)
						var t126 int
						if (nd < b34) {
							t126 = nd
						} else {
							t126 = b34
						}
						var mid217 int = t126
						var b35 int = (lo2 + (2 * w3))
						var t127 int
						if (nd < b35) {
							t127 = nd
						} else {
							t127 = b35
						}
						var hi217 int = t127
						b36 := b23
						var i20 int = lo2
						var j4 int = mid217
						var k6 int = lo2
						for ; ; k6 = (k6 + 1) {
							if (k6 >= hi217) {
								break
							}
							if (i20 >= mid217) {
								var t128 int
								if (k6 < 0) {
									t128 = 0
								} else {
									var t129 int
									if (k6 >= nd) {
										t129 = 0
									} else {
										t129 = k6
									}
									t128 = t129
								}
								var t130 int
								if (j4 < 0) {
									t130 = 0
								} else {
									var t131 int
									if (j4 >= nd) {
										t131 = 0
									} else {
										t131 = j4
									}
									t130 = t131
								}
								b36[t128] = a4[t130]
								j4 = (j4 + 1)
								continue
							}
							if (j4 >= hi217) {
								var t132 int
								if (k6 < 0) {
									t132 = 0
								} else {
									var t133 int
									if (k6 >= nd) {
										t133 = 0
									} else {
										t133 = k6
									}
									t132 = t133
								}
								var t134 int
								if (i20 < 0) {
									t134 = 0
								} else {
									var t135 int
									if (i20 >= nd) {
										t135 = 0
									} else {
										t135 = i20
									}
									t134 = t135
								}
								b36[t132] = a4[t134]
								i20 = (i20 + 1)
								continue
							}
							var t136 int
							if (j4 < 0) {
								t136 = 0
							} else {
								var t137 int
								if (j4 >= nd) {
									t137 = 0
								} else {
									t137 = j4
								}
								t136 = t137
							}
							var t138 int
							if (i20 < 0) {
								t138 = 0
							} else {
								var t139 int
								if (i20 >= nd) {
									t139 = 0
								} else {
									t139 = i20
								}
								t138 = t139
							}
							if (dt3[((2 * a4[t136]) + 1)] > dt3[((2 * a4[t138]) + 1)]) {
								var t140 int
								if (k6 < 0) {
									t140 = 0
								} else {
									var t141 int
									if (k6 >= nd) {
										t141 = 0
									} else {
										t141 = k6
									}
									t140 = t141
								}
								var t142 int
								if (j4 < 0) {
									t142 = 0
								} else {
									var t143 int
									if (j4 >= nd) {
										t143 = 0
									} else {
										t143 = j4
									}
									t142 = t143
								}
								b36[t140] = a4[t142]
								j4 = (j4 + 1)
								continue
							}
							var t144 int
							if (k6 < 0) {
								t144 = 0
							} else {
								var t145 int
								if (k6 >= nd) {
									t145 = 0
								} else {
									t145 = k6
								}
								t144 = t145
							}
							var t146 int
							if (i20 < 0) {
								t146 = 0
							} else {
								var t147 int
								if (i20 >= nd) {
									t147 = 0
								} else {
									t147 = i20
								}
								t146 = t147
							}
							b36[t144] = a4[t146]
							i20 = (i20 + 1)
							continue
						}
						b23, lo2 = b36, hi217
						continue
					}
					a4, b5 = b23, a4
					continue
				}
				ord2 := a4
				var n3 int = 0
				var r int = 0
				for ; ; r = (r + 1) {
					if (r >= nd) {
						break
					}
					if (r >= 20) {
						break
					}
					if ((len(sp3) >> 1) < 1) {
						break
					}
					var t148 int
					if (r < 0) {
						t148 = 0
					} else {
						var t149 int
						if (r >= nd) {
							t149 = 0
						} else {
							t149 = r
						}
						t148 = t149
					}
					var d98 int = ord2[t148]
					var d107 int = 1
					var x int = dt3[((2 * d98) + 1)]
					for ; ; d107, x = (d107 + 1), (x / 10) {
						if (x < 10) {
							break
						}
						if (d107 >= 8) {
							break
						}
						continue
					}
					var i21 int = dt3[(2 * d98)]
					var t150 int
					if (i21 < 0) {
						t150 = 0
					} else {
						var t151 int
						if (i21 >= (len(sp3) >> 1)) {
							t151 = 0
						} else {
							t151 = i21
						}
						t150 = t151
					}
					var w4 int = t150
					var d108 int = (sp3[((2 * w4) + 1)] - sp3[(2 * w4)])
					var t152 int
					if (d108 < 0) {
						t152 = 0
					} else {
						var t153 int
						if (d108 >= 65536) {
							t153 = 0
						} else {
							t153 = d108
						}
						t152 = t153
					}
					n3 = (n3 + (d107 + (2 + t152)))
					continue
				}
				var m int = n3
				out := make([]byte, m)
				out2 := out
				var o int = 0
				var r2 int = 0
				for ; ; r2 = (r2 + 1) {
					if (r2 >= nd) {
						break
					}
					if (r2 >= 20) {
						break
					}
					if ((len(sp3) >> 1) < 1) {
						break
					}
					var t154 int
					if (r2 < 0) {
						t154 = 0
					} else {
						var t155 int
						if (r2 >= nd) {
							t155 = 0
						} else {
							t155 = r2
						}
						t154 = t155
					}
					var d17 int = ord2[t154]
					var c21 int = dt3[((2 * d17) + 1)]
					var i26 int = dt3[(2 * d17)]
					var t156 int
					if (i26 < 0) {
						t156 = 0
					} else {
						var t157 int
						if (i26 >= (len(sp3) >> 1)) {
							t157 = 0
						} else {
							t157 = i26
						}
						t156 = t157
					}
					var w5 int = t156
					var p2 int = 1
					var k7 int = 1
					for {
						var d18 int = 1
						var x3 int = c21
						for ; ; d18, x3 = (d18 + 1), (x3 / 10) {
							if (x3 < 10) {
								break
							}
							if (d18 >= 8) {
								break
							}
							continue
						}
						if (k7 >= d18) {
							break
						}
						if (k7 >= 8) {
							break
						}
						if (p2 >= 100000000) {
							break
						}
						p2, k7 = (p2 * 10), (k7 + 1)
						continue
					}
					out22 := out2
					var o2 int = o
					var p int = p2
					var x2 int = c21
					for ; ; p = (p / 10) {
						if (p < 1) {
							break
						}
						var t158 int
						if (o2 < 0) {
							t158 = 0
						} else {
							var t159 int
							if (o2 >= m) {
								t159 = 0
							} else {
								t159 = o2
							}
							t158 = t159
						}
						out22[t158] = byte((48 + ((x2 / p) % 10)))
						var i27 int = (o2 + 1)
						var t160 int
						if (i27 < 0) {
							t160 = 0
						} else {
							var t161 int
							if (i27 >= m) {
								t161 = 0
							} else {
								t161 = i27
							}
							t160 = t161
						}
						o2 = t160
						continue
					}
					var d182 int = 1
					var x4 int = c21
					for ; ; d182, x4 = (d182 + 1), (x4 / 10) {
						if (x4 < 10) {
							break
						}
						if (d182 >= 8) {
							break
						}
						continue
					}
					var i28 int = (o + d182)
					var t162 int
					if (i28 < 0) {
						t162 = 0
					} else {
						var t163 int
						if (i28 >= m) {
							t163 = 0
						} else {
							t163 = i28
						}
						t162 = t163
					}
					out22[t162] = 32
					out23 := out22
					var d183 int = 1
					var x5 int = c21
					for ; ; d183, x5 = (d183 + 1), (x5 / 10) {
						if (x5 < 10) {
							break
						}
						if (d183 >= 8) {
							break
						}
						continue
					}
					out3 := out23
					var o22 int = (o + (d183 + 1))
					var k8 int = 0
					for ; ; k8 = (k8 + 1) {
						var d184 int = (sp3[((2 * w5) + 1)] - sp3[(2 * w5)])
						var t164 int
						if (d184 < 0) {
							t164 = 0
						} else {
							var t165 int
							if (d184 >= 65536) {
								t165 = 0
							} else {
								t165 = d184
							}
							t164 = t165
						}
						if (k8 >= t164) {
							break
						}
						var t166 int
						if (o22 < 0) {
							t166 = 0
						} else {
							var t167 int
							if (o22 >= m) {
								t167 = 0
							} else {
								t167 = o22
							}
							t166 = t167
						}
						var i29 int = (sp3[(2 * w5)] + k8)
						var t168 int
						if (i29 < 0) {
							t168 = 0
						} else {
							var t169 int
							if (i29 >= len(src)) {
								t169 = 0
							} else {
								t169 = i29
							}
							t168 = t169
						}
						out3[t166] = byte(int(src[t168]))
						var i30 int = (o22 + 1)
						var t170 int
						if (i30 < 0) {
							t170 = 0
						} else {
							var t171 int
							if (i30 >= m) {
								t171 = 0
							} else {
								t171 = i30
							}
							t170 = t171
						}
						o22 = t170
						continue
					}
					var d185 int = 1
					var x6 int = dt3[((2 * d17) + 1)]
					for ; ; d185, x6 = (d185 + 1), (x6 / 10) {
						if (x6 < 10) {
							break
						}
						if (d185 >= 8) {
							break
						}
						continue
					}
					var i31 int = dt3[(2 * d17)]
					var t172 int
					if (i31 < 0) {
						t172 = 0
					} else {
						var t173 int
						if (i31 >= (len(sp3) >> 1)) {
							t173 = 0
						} else {
							t173 = i31
						}
						t172 = t173
					}
					var w22 int = t172
					var d186 int = (sp3[((2 * w22) + 1)] - sp3[(2 * w22)])
					var t174 int
					if (d186 < 0) {
						t174 = 0
					} else {
						var t175 int
						if (d186 >= 65536) {
							t175 = 0
						} else {
							t175 = d186
						}
						t174 = t175
					}
					var i32 int = (o + ((d185 + (2 + t174)) - 1))
					var t176 int
					if (i32 < 0) {
						t176 = 0
					} else {
						var t177 int
						if (i32 >= m) {
							t177 = 0
						} else {
							t177 = i32
						}
						t176 = t177
					}
					out3[t176] = 10
					var d187 int = 1
					var x7 int = dt3[((2 * d17) + 1)]
					for ; ; d187, x7 = (d187 + 1), (x7 / 10) {
						if (x7 < 10) {
							break
						}
						if (d187 >= 8) {
							break
						}
						continue
					}
					var i33 int = dt3[(2 * d17)]
					var t178 int
					if (i33 < 0) {
						t178 = 0
					} else {
						var t179 int
						if (i33 >= (len(sp3) >> 1)) {
							t179 = 0
						} else {
							t179 = i33
						}
						t178 = t179
					}
					var w6 int = t178
					var d188 int = (sp3[((2 * w6) + 1)] - sp3[(2 * w6)])
					var t180 int
					if (d188 < 0) {
						t180 = 0
					} else {
						var t181 int
						if (d188 >= 65536) {
							t181 = 0
						} else {
							t181 = d188
						}
						t180 = t181
					}
					out2, o = out3, (o + (d187 + (2 + t180)))
					continue
				}
				var v182 string = (func(s string) string { if utf8.ValidString(s) { return s }; b := make([]byte, 0, len(s)+8); for i := 0; i < len(s); { c := s[i]; if c < 0x80 { b = append(b, c); i++; continue }; n, lo, hi := 0, byte(0x80), byte(0xBF); switch { case c >= 0xC2 && c <= 0xDF: n = 1; case c == 0xE0: n, lo = 2, 0xA0; case c == 0xED: n, hi = 2, 0x9F; case c >= 0xE1 && c <= 0xEF: n = 2; case c == 0xF0: n, lo = 3, 0x90; case c == 0xF4: n, hi = 3, 0x8F; case c >= 0xF1 && c <= 0xF3: n = 3 }; j := i + 1; ok := n > 0; for k := 0; ok && k < n; k++ { if j >= len(s) || s[j] < lo || s[j] > hi { ok = false; break }; j++; lo, hi = 0x80, 0xBF }; if ok { b = append(b, s[i:j]...) } else { b = append(b, "\uFFFD"...) }; i = j }; return string(b) }(string(out2)))
				fmt.Print(v182)
				t3 = v182
			}
			t2 = t3
		} else {
			fmt.Println("freq: cannot read that file")
			t2 = "freq: cannot read that file"
		}
		t1 = t2
	}
	return t1
}

