// Code generated by oroboros. DO NOT EDIT.

import java.nio.charset.StandardCharsets;
import java.nio.file.*;

public final class examples_io_wc.java {
	public static long genMain() {
		final String[] av = (oroArgs);
		long t8;
		if ((av.length < 2)) {
			((java.util.function.Consumer<String>) ($oroS) -> { final byte[] $oroB = $oroS.getBytes(StandardCharsets.UTF_8); System.out.write($oroB, 0, $oroB.length); System.out.flush(); }).accept("usage: wc FILE" + "\n");
			t8 = 0;
		} else {
			short[] src2;
			Exception err2;
			try { final byte[] $oroB = Files.readAllBytes(Path.of(av[1])); src2 = new short[$oroB.length]; for (int $oroI = 0; $oroI < $oroB.length; $oroI++) src2[$oroI] = (short) ($oroB[$oroI] & 0xFF); err2 = null; } catch (Exception $oroE) { src2 = null; err2 = $oroE; }
			long t12;
			if ((err2 == null)) {
				long t14;
				if ((src2.length >= 16777216)) {
					((java.util.function.Consumer<String>) ($oroS) -> { final byte[] $oroB = $oroS.getBytes(StandardCharsets.UTF_8); System.out.write($oroB, 0, $oroB.length); System.out.flush(); }).accept("wc: file is larger than this tool accepts" + "\n");
					t14 = 0;
				} else {
					int i8 = 0;
					int lines8 = 0;
					long r15 = 0;
					for (;; i8 = (i8 + 1)) {
						if ((i8 >= src2.length)) {
							((java.util.function.Consumer<String>) ($oroS) -> { final byte[] $oroB = $oroS.getBytes(StandardCharsets.UTF_8); System.out.write($oroB, 0, $oroB.length); System.out.flush(); }).accept(lines8 + "\n");
							r15 = lines8;
							break;
						}
						lines8 = (int) (((lines8 < 16777216) ? (((long) src2[i8] == 10) ? (lines8 + 1) : lines8) : lines8));
						continue;
					}
					t14 = r15;
				}
				t12 = t14;
			} else {
				((java.util.function.Consumer<String>) ($oroS) -> { final byte[] $oroB = $oroS.getBytes(StandardCharsets.UTF_8); System.out.write($oroB, 0, $oroB.length); System.out.flush(); }).accept("wc: cannot read that file" + "\n");
				t12 = 0;
			}
			t8 = t12;
		}
		return t8;
	}

}
