; Code generated by oroboros. DO NOT EDIT.

option casemap:none

extern VirtualAlloc: proc

.data

.code
gen_limb proc
        push rbx
        push rsi
        push rdi
        push r12
        push r13
        push r14
        push r15
        sub rsp, 64
        mov qword ptr [rsp+48], rcx
        mov r10, 64
        add r10, 1
        shl r10, 3
        xor ecx, ecx
        mov rdx, r10
        mov r8, 3000h
        mov r9, 4
        call VirtualAlloc
        mov rsi, rax
        mov qword ptr [rsi], 64
        mov rdi, 0
        mov r12, 1
Ltop4:
        cmp rdi, 64
        jge Lexit5
Lelse6:
        mov r13, r12
        and r13, 16777215
        mov qword ptr [rsi+rdi*8+8], r13
        add rdi, 1
        mov rcx, 24
        shr r12, cl
        jmp Ltop4
Lexit5:
Lbuilt3:
        mov r10, 64
        add r10, 1
        shl r10, 3
        xor ecx, ecx
        mov rdx, r10
        mov r8, 3000h
        mov r9, 4
        call VirtualAlloc
        mov rdi, rax
        mov qword ptr [rdi], 64
        mov r12, 2
Ltop11:
        cmp r12, 200
        jle Lelse13
        mov rbx, rsi
        jmp Lexit12
Lelse13:
        xor r11d, r11d
Lzc14:
        cmp r11, 64
        jge Lzd14
        mov qword ptr [rdi+r11*8+8], 0
        inc r11
        jmp Lzc14
Lzd14:
        mov r13, rdi
        mov r14, 0
        mov r15, 0
Ltop16:
        cmp r14, 64
        jl Lelse18
        mov rbx, r13
        jmp Lexit17
Lelse18:
        cmp r14, 0
        jge Lelse19
        mov rbx, 0
        jmp Ldone20
Lelse19:
        mov rbx, qword ptr [rsi]
        cmp r14, rbx
        jl Lelse21
        mov rbx, 0
        jmp Ldone20
Lelse21:
        mov rbx, qword ptr [rsi+r14*8+8]
Ldone20:
        imul rbx, r12
        add rbx, r15
        mov r15, rbx
        and r15, 16777215
        mov qword ptr [r13+r14*8+8], r15
        add r14, 1
        mov rcx, 24
        shr rbx, cl
        mov r15, rbx
        jmp Ltop16
Lexit17:
Lbuilt15:
        add r12, 1
        mov rdi, rsi
        mov rsi, rbx
        jmp Ltop11
Lexit12:
        mov rax, qword ptr [rsp+48]
        cmp rax, 0
        jge Lelse28
        mov rax, 0
        jmp Lret1
Lelse28:
        mov rsi, qword ptr [rbx]
        mov rax, qword ptr [rsp+48]
        cmp rax, rsi
        jl Lelse29
        mov rax, 0
        jmp Lret1
Lelse29:
        mov r11, qword ptr [rsp+48]
        mov rsi, qword ptr [rbx+r11*8+8]
        mov rax, rsi
Lret1:
        add rsp, 64
        pop r15
        pop r14
        pop r13
        pop r12
        pop rdi
        pop rsi
        pop rbx
        ret
gen_limb endp


end
