// Code generated by oroboros. DO NOT EDIT.

export function genMain() {
	const v0 = (process.argv.slice(1));
	if ((v0.length < 2)) {
		console.log("usage: roundtrip FILE");
		return 1;
	}
	const v10 = v0[1];
	const v18 = [104, 105, 32, 226, 130, 172, 10];
	let v19;
	try { fs.writeFileSync(v10, Buffer.from(v18)); v19 = null; } catch (e) { v19 = e; }
	if ((v19 === null)) {
		let v21, v22;
		try { v21 = fs.readFileSync(v10); v22 = null; } catch (e) { v21 = null; v22 = e; }
		if ((v22 === null)) {
			process.stdout.write((new TextDecoder().decode(Uint8Array.from(v21))));
			const v27 = ((process.env["ORO_ROUNDTRIP"] ?? ""));
			console.log(v27);
			console.log(v21.length);
			let v33, v34;
			try { v33 = fs.readFileSync((v10 + ".missing")); v34 = null; } catch (e) { v33 = null; v34 = e; }
			console.log(((v34 === null) ? "found" : (((v34.code === "ENOENT")) ? "not-found" : (((v34.code === "EEXIST")) ? "exists" : ((["EACCES", "EPERM"].includes(v34.code)) ? "permission" : "other")))));
			return 0;
		}
		console.log(("roundtrip: cannot read that file: " + (((v22.code === "ENOENT")) ? "not-found" : (((v22.code === "EEXIST")) ? "exists" : ((["EACCES", "EPERM"].includes(v22.code)) ? "permission" : "other")))));
		return 1;
	}
	console.log(("roundtrip: cannot write that file: " + (((v19.code === "ENOENT")) ? "not-found" : (((v19.code === "EEXIST")) ? "exists" : ((["EACCES", "EPERM"].includes(v19.code)) ? "permission" : "other")))));
	return 1;
}

