// Code generated by oroboros. DO NOT EDIT.

public final class examples_errors_expect.java {
	public static long genAlwaysCrashes(int v0) {
		throw new IllegalStateException("the value is never a success");
	}

	public static long genQuarter(int v0) {
		final int v10 = (int) (v0 & 1);
		final boolean v12 = (v10 == 0);
		if (v12) {
			final int v14 = (int) (v0 >> 1);
			final int v16 = (int) (v14 & 1);
			final boolean v18 = (v16 == 0);
			if (v18) {
				final int v20 = (int) (v14 >> 1);
				return v20;
			}
			throw new IllegalStateException("a multiple of four is expected");
		}
		throw new IllegalStateException("an even number is expected");
	}

}
