// Code generated by oroboros. DO NOT EDIT.

package gauntlet

func GenCountPrimes(v0 int) int {
	v10 := make([]bool, v0)
	var v9 []bool
	v13 := v10
	var v14 int = 2
	for ; ; v14 = (v14 + 1) {
		v15 := (v14 * v14)
		v16 := (v15 >= v0)
		if v16 {
			break
		}
		v19 := v13[v14]
		if v19 {
			continue
		}
		v22 := (v14 * v14)
		v24 := v13
		var v25 int = v22
		for {
			v26 := (v25 < v0)
			if v26 {
				v24[v25] = true
				v31 := (v25 + v14)
				v25 = v31
				continue
			}
			break
		}
		v13 = v24
		continue
	}
	v9 = v13
	var v39 int = 0
	var v40 int = 2
	for ; ; v40 = (v40 + 1) {
		v41 := (v40 >= v0)
		if v41 {
			break
		}
		v46 := v9[v40]
		if v46 {
			continue
		}
		v50 := (v39 + 1)
		v39 = v50
		continue
	}
	return v39
}

