// Code generated by oroboros. DO NOT EDIT.

package gauntlet

import "math/big"

func GenPair(n int) *big.Int {
	a := (big.NewInt(int64(2)))
	b := (big.NewInt(int64(1)))
	var i int = 0
	for ; ; i = (i + 1) {
		if (i >= n) {
			break
		}
		a, b = (new(big.Int).Mul(a, b)), (new(big.Int).Add(b, a))
		continue
	}
	return b
}

