// Code generated by oroboros. DO NOT EDIT.

import java.nio.charset.StandardCharsets;
import java.nio.file.*;

public final class examples_io_count.java {
	public static long genMain() {
		final String[] v0 = (oroArgs);
		final int v1 = v0.length;
		final boolean v3 = (v1 < 2);
		if (v3) {
			((java.util.function.Consumer<String>) ($oroS) -> { final byte[] $oroB = $oroS.getBytes(StandardCharsets.UTF_8); System.out.write($oroB, 0, $oroB.length); System.out.flush(); }).accept("usage: count FILE" + "\n");
			return 0;
		}
		final String v10 = v0[1];
		short[] v11;
		Exception v12;
		try { final byte[] $oroB = Files.readAllBytes(Path.of(v10)); v11 = new short[$oroB.length]; for (int $oroI = 0; $oroI < $oroB.length; $oroI++) v11[$oroI] = (short) ($oroB[$oroI] & 0xFF); v12 = null; } catch (Exception $oroE) { v11 = null; v12 = $oroE; }
		final boolean v13 = (v12 == null);
		if (v13) {
			final int v14 = v11.length;
			final boolean v16 = (v14 >= 16777216);
			if (v16) {
				((java.util.function.Consumer<String>) ($oroS) -> { final byte[] $oroB = $oroS.getBytes(StandardCharsets.UTF_8); System.out.write($oroB, 0, $oroB.length); System.out.flush(); }).accept("count: file is larger than this tool accepts" + "\n");
				return 0;
			}
			int v27 = 0;
			int v28 = 0;
			int v29 = 0;
			boolean v30 = false;
			int v26 = 0;
			for (;; v27 = (v27 + 1)) {
				final int v31 = v11.length;
				final boolean v32 = (v27 >= v31);
				if (v32) {
					((java.util.function.Consumer<String>) ($oroS) -> { final byte[] $oroB = $oroS.getBytes(StandardCharsets.UTF_8); System.out.write($oroB, 0, $oroB.length); System.out.flush(); }).accept(v28 + "\n");
					((java.util.function.Consumer<String>) ($oroS) -> { final byte[] $oroB = $oroS.getBytes(StandardCharsets.UTF_8); System.out.write($oroB, 0, $oroB.length); System.out.flush(); }).accept(v29 + "\n");
					final int v37 = v11.length;
					((java.util.function.Consumer<String>) ($oroS) -> { final byte[] $oroB = $oroS.getBytes(StandardCharsets.UTF_8); System.out.write($oroB, 0, $oroB.length); System.out.flush(); }).accept(v37 + "\n");
					v26 = v37;
					break;
				}
				final int v41 = v11[v27];
				final boolean v43 = (v41 == 10);
				if (v43) {
					final boolean v46 = (v28 < 16777216);
					if (v46) {
						final int v49 = (v28 + 1);
						final boolean v54 = (v41 == 32);
						final boolean v55 = (v54 || ((v41 >= 9) && (v41 <= 13)));
						if (v55) {
							v28 = v49;
							v30 = false;
							continue;
						}
						if (v30) {
							v28 = v49;
							continue;
						}
						final boolean v73 = (v29 < 16777216);
						if (v73) {
							final long v78 = (v29 + 1);
							v28 = v49;
							v29 = (int) (v78);
							v30 = true;
							continue;
						}
						v28 = v49;
						continue;
					}
					final boolean v88 = (v41 == 32);
					final boolean v89 = (v88 || ((v41 >= 9) && (v41 <= 13)));
					if (v89) {
						v30 = false;
						continue;
					}
					if (v30) {
						continue;
					}
					final boolean v107 = (v29 < 16777216);
					if (v107) {
						final long v112 = (v29 + 1);
						v29 = (int) (v112);
						v30 = true;
						continue;
					}
					continue;
				}
				final boolean v122 = (v41 == 32);
				final boolean v123 = (v122 || ((v41 >= 9) && (v41 <= 13)));
				if (v123) {
					v30 = false;
					continue;
				}
				if (v30) {
					continue;
				}
				final boolean v141 = (v29 < 16777216);
				if (v141) {
					final int v146 = (v29 + 1);
					v29 = v146;
					v30 = true;
					continue;
				}
				continue;
			}
			return v26;
		}
		((java.util.function.Consumer<String>) ($oroS) -> { final byte[] $oroB = $oroS.getBytes(StandardCharsets.UTF_8); System.out.write($oroB, 0, $oroB.length); System.out.flush(); }).accept("count: cannot read that file" + "\n");
		return 0;
	}

}
