// Code generated by oroboros. DO NOT EDIT.

export function genMain() {
	const v0 = (process.argv.slice(1));
	if ((v0.length < 2)) {
		console.log("usage: jsonfmt FILE");
		return "usage: jsonfmt FILE";
	}
	let v10, v11;
	try { v10 = fs.readFileSync(v0[1]); v11 = null; } catch (e) { v10 = null; v11 = e; }
	if ((v11 === null)) {
		if ((v10.length >= 65536)) {
			console.log("jsonfmt: file is larger than this tool accepts");
			return "jsonfmt: file is larger than this tool accepts";
		}
		let v25 = 0;
		let v26 = 0;
		let v27 = 0;
		let v28 = 0;
		let v24;
		for (;;) {
			if ((v26 >= v10.length)) {
				v24 = (v25 + 1);
				break;
			}
			if ((v27 >= 64)) {
				v24 = (v25 + 1);
				break;
			}
			const v43 = v10[v26];
			if (((v43 === 32) || ((v43 === 9) || ((v43 === 10) || (v43 === 13))))) {
				v26 = (v26 + 1);
				continue;
			}
			const v64 = v10[v26];
			if (((v64 === 123) || (v64 === 91))) {
				v25 = (v25 + (((v28 === 1) ? (1 + (2 * v27)) : 0) + 1));
				v26 = (v26 + 1);
				v27 = (v27 + 1);
				v28 = 1;
				continue;
			}
			const v91 = v10[v26];
			if (((v91 === 125) || (v91 === 93))) {
				const v102 = ((v27 < 1) ? 0 : (v27 - 1));
				v25 = (v25 + (((v28 === 0) ? (1 + (2 * v102)) : 0) + 1));
				v26 = (v26 + 1);
				v27 = v102;
				v28 = 0;
				continue;
			}
			if ((v10[v26] === 44)) {
				v25 = (v25 + (2 + (2 * v27)));
				v26 = (v26 + 1);
				v28 = 0;
				continue;
			}
			if ((v10[v26] === 58)) {
				v25 = (v25 + 2);
				v26 = (v26 + 1);
				continue;
			}
			const v142 = v10[v26];
			if (((v142 === 34) || ((((v142 >= 48) && (v142 <= 57)) || ((v142 === 45) || ((v142 === 43) || ((v142 === 46) || ((v142 === 101) || (v142 === 69)))))) || ((v142 >= 97) && (v142 <= 122))))) {
				let v208;
				if ((v10[v26] === 34)) {
					let v212 = (v26 + 1);
					let v211;
					for (;;) {
						if ((v212 < 0)) {
							v211 = v212;
							break;
						}
						if ((v212 >= v10.length)) {
							v211 = v212;
							break;
						}
						if (((v10[v212] === 92) && ((v212 + 1) >= v10.length))) {
							v211 = (v212 + 1);
							break;
						}
						if ((v10[v212] === 92)) {
							v212 = (v212 + 2);
							continue;
						}
						if ((v10[v212] === 34)) {
							v211 = (v212 + 1);
							break;
						}
						v212 = (v212 + 1);
						continue;
					}
					v208 = v211;
				} else {
					const v247 = v10[v26];
					if ((((v247 >= 48) && (v247 <= 57)) || ((v247 === 45) || ((v247 === 43) || ((v247 === 46) || ((v247 === 101) || (v247 === 69))))))) {
						let v287 = (v26 + 1);
						for (;; v287 = (v287 + 1)) {
							if ((v287 < 0)) {
								break;
							}
							if ((v287 >= v10.length)) {
								break;
							}
							const v298 = v10[v287];
							if ((((v298 >= 48) && (v298 <= 57)) || ((v298 === 45) || ((v298 === 43) || ((v298 === 46) || ((v298 === 101) || (v298 === 69))))))) {
								continue;
							}
							break;
						}
						v208 = v287;
					} else {
						let v340 = (v26 + 1);
						for (;; v340 = (v340 + 1)) {
							if ((v340 < 0)) {
								break;
							}
							if ((v340 >= v10.length)) {
								break;
							}
							const v351 = v10[v340];
							if (((v351 >= 97) && (v351 <= 122))) {
								continue;
							}
							break;
						}
						v208 = v340;
					}
				}
				v25 = (v25 + (((v28 === 1) ? (1 + (2 * v27)) : 0) + (v208 - v26)));
				v26 = v208;
				v28 = 0;
				continue;
			}
			v26 = (v26 + 1);
			continue;
		}
		const v379 = new Array(v24).fill(0);
		let v378;
		let v385 = v379;
		let v386 = 0;
		let v387 = 0;
		let v388 = 0;
		let v389 = 0;
		for (;;) {
			if ((v387 >= v10.length)) {
				v385[v386] = 10;
				break;
			}
			if ((v388 >= 64)) {
				v385[v386] = 10;
				break;
			}
			const v404 = v10[v387];
			if (((v404 === 32) || ((v404 === 9) || ((v404 === 10) || (v404 === 13))))) {
				v387 = (v387 + 1);
				continue;
			}
			const v425 = v10[v387];
			if (((v425 === 123) || (v425 === 91))) {
				const v436 = ((v389 === 1) ? (1 + (2 * v388)) : 0);
				let v446;
				if ((v389 === 1)) {
					v385[v386] = 10;
					let v454 = v385;
					let v455 = 0;
					let v456 = (v386 + 1);
					for (;; v455 = (v455 + 1), v456 = (v456 + 1)) {
						if ((v455 >= (2 * v388))) {
							break;
						}
						v454[v456] = 32;
						continue;
					}
					v446 = v454;
				} else {
					v446 = v385;
				}
				v446[(v386 + v436)] = ((v10[v387] === 123) ? 123 : 91);
				v385 = v446;
				v386 = (v386 + (v436 + 1));
				v387 = (v387 + 1);
				v388 = (v388 + 1);
				v389 = 1;
				continue;
			}
			const v485 = v10[v387];
			if (((v485 === 125) || (v485 === 93))) {
				const v496 = ((v388 < 1) ? 0 : (v388 - 1));
				const v504 = ((v389 === 0) ? (1 + (2 * v496)) : 0);
				let v514;
				if ((v389 === 0)) {
					v385[v386] = 10;
					let v522 = v385;
					let v523 = 0;
					let v524 = (v386 + 1);
					for (;; v523 = (v523 + 1), v524 = (v524 + 1)) {
						if ((v523 >= (2 * v496))) {
							break;
						}
						v522[v524] = 32;
						continue;
					}
					v514 = v522;
				} else {
					v514 = v385;
				}
				v514[(v386 + v504)] = ((v10[v387] === 125) ? 125 : 93);
				v385 = v514;
				v386 = (v386 + (v504 + 1));
				v387 = (v387 + 1);
				v388 = v496;
				v389 = 0;
				continue;
			}
			if ((v10[v387] === 44)) {
				v385[v386] = 44;
				const v557 = (v386 + 1);
				v385[v557] = 10;
				let v564 = v385;
				let v565 = 0;
				let v566 = (v557 + 1);
				for (;; v565 = (v565 + 1), v566 = (v566 + 1)) {
					if ((v565 >= (2 * v388))) {
						break;
					}
					v564[v566] = 32;
					continue;
				}
				v385 = v564;
				v386 = (v386 + (2 + (2 * v388)));
				v387 = (v387 + 1);
				v389 = 0;
				continue;
			}
			if ((v10[v387] === 58)) {
				v385[v386] = 58;
				v385[(v386 + 1)] = 32;
				v386 = (v386 + 2);
				v387 = (v387 + 1);
				continue;
			}
			const v599 = v10[v387];
			if (((v599 === 34) || ((((v599 >= 48) && (v599 <= 57)) || ((v599 === 45) || ((v599 === 43) || ((v599 === 46) || ((v599 === 101) || (v599 === 69)))))) || ((v599 >= 97) && (v599 <= 122))))) {
				let v665;
				if ((v10[v387] === 34)) {
					let v669 = (v387 + 1);
					let v668;
					for (;;) {
						if ((v669 < 0)) {
							v668 = v669;
							break;
						}
						if ((v669 >= v10.length)) {
							v668 = v669;
							break;
						}
						if (((v10[v669] === 92) && ((v669 + 1) >= v10.length))) {
							v668 = (v669 + 1);
							break;
						}
						if ((v10[v669] === 92)) {
							v669 = (v669 + 2);
							continue;
						}
						if ((v10[v669] === 34)) {
							v668 = (v669 + 1);
							break;
						}
						v669 = (v669 + 1);
						continue;
					}
					v665 = v668;
				} else {
					const v704 = v10[v387];
					if ((((v704 >= 48) && (v704 <= 57)) || ((v704 === 45) || ((v704 === 43) || ((v704 === 46) || ((v704 === 101) || (v704 === 69))))))) {
						let v744 = (v387 + 1);
						for (;; v744 = (v744 + 1)) {
							if ((v744 < 0)) {
								break;
							}
							if ((v744 >= v10.length)) {
								break;
							}
							const v755 = v10[v744];
							if ((((v755 >= 48) && (v755 <= 57)) || ((v755 === 45) || ((v755 === 43) || ((v755 === 46) || ((v755 === 101) || (v755 === 69))))))) {
								continue;
							}
							break;
						}
						v665 = v744;
					} else {
						let v797 = (v387 + 1);
						for (;; v797 = (v797 + 1)) {
							if ((v797 < 0)) {
								break;
							}
							if ((v797 >= v10.length)) {
								break;
							}
							const v808 = v10[v797];
							if (((v808 >= 97) && (v808 <= 122))) {
								continue;
							}
							break;
						}
						v665 = v797;
					}
				}
				const v821 = ((v389 === 1) ? (1 + (2 * v388)) : 0);
				let v831;
				if ((v389 === 1)) {
					v385[v386] = 10;
					let v839 = v385;
					let v840 = 0;
					let v841 = (v386 + 1);
					for (;; v840 = (v840 + 1), v841 = (v841 + 1)) {
						if ((v840 >= (2 * v388))) {
							break;
						}
						v839[v841] = 32;
						continue;
					}
					v831 = v839;
				} else {
					v831 = v385;
				}
				let v856 = v831;
				let v857 = v387;
				let v858 = (v386 + v821);
				for (;; v857 = (v857 + 1), v858 = (v858 + 1)) {
					if ((v857 >= v665)) {
						break;
					}
					if ((v857 >= v10.length)) {
						break;
					}
					v856[v858] = v10[v857];
					continue;
				}
				v385 = v856;
				v386 = (v386 + (v821 + (v665 - v387)));
				v387 = v665;
				v389 = 0;
				continue;
			}
			v387 = (v387 + 1);
			continue;
		}
		v378 = v385;
		const v882 = (new TextDecoder().decode(Uint8Array.from(v378)));
		process.stdout.write(v882);
		return v882;
	}
	console.log("jsonfmt: cannot read that file");
	return "jsonfmt: cannot read that file";
}

