// Code generated by oroboros. DO NOT EDIT.

public final class gauntlet_differential_cases_big-divmod.java {
	public static long genRun(int v0) {
		final int v10 = (v0 + 7);
		final java.math.BigInteger v11 = (java.math.BigInteger.valueOf(v10));
		java.math.BigInteger v14 = v11;
		int v15 = 0;
		for (;; v15 = (v15 + 1)) {
			final boolean v17 = (v15 >= 6);
			if (v17) {
				break;
			}
			final java.math.BigInteger v21 = (java.math.BigInteger.valueOf(999983));
			final java.math.BigInteger v22 = (v14.multiply(v21));
			final java.math.BigInteger v24 = (((java.util.function.BiFunction<java.math.BigInteger,Long,java.math.BigInteger>)((oro$z, oro$k) -> { if (oro$z.signum() < 0 || oro$z.bitLength() > oro$k) throw new ArithmeticException("bignum overflow: the declared range is too small"); return oro$z; })).apply(v22, (long)(201)));
			v14 = v24;
			continue;
		}
		final java.math.BigInteger v28 = (java.math.BigInteger.valueOf(100000000));
		final java.math.BigInteger v29 = (v14.divide(v28));
		final java.math.BigInteger v31 = (((java.util.function.BiFunction<java.math.BigInteger,Long,java.math.BigInteger>)((oro$z, oro$k) -> { if (oro$z.signum() < 0 || oro$z.bitLength() > oro$k) throw new ArithmeticException("bignum overflow: the declared range is too small"); return oro$z; })).apply(v29, (long)(201)));
		final int v33 = (int) (v31.remainder(java.math.BigInteger.valueOf(100000000)).longValue());
		final java.math.BigInteger v35 = (java.math.BigInteger.valueOf(11));
		java.math.BigInteger v38 = v35;
		int v39 = 0;
		for (;; v39 = (v39 + 1)) {
			final boolean v41 = (v39 >= 6);
			if (v41) {
				break;
			}
			final java.math.BigInteger v45 = (java.math.BigInteger.valueOf(999983));
			final java.math.BigInteger v46 = (v38.multiply(v45));
			final java.math.BigInteger v48 = (((java.util.function.BiFunction<java.math.BigInteger,Long,java.math.BigInteger>)((oro$z, oro$k) -> { if (oro$z.signum() < 0 || oro$z.bitLength() > oro$k) throw new ArithmeticException("bignum overflow: the declared range is too small"); return oro$z; })).apply(v46, (long)(201)));
			v38 = v48;
			continue;
		}
		final boolean v51 = (v14.compareTo(v38) > 0);
		long v52 = 0;
		if (v51) {
			v52 = 1000000000000L;
		} else {
			v52 = 0;
		}
		final long v55 = (v33 + v52);
		return v55;
	}

}
