; Code generated by oroboros. DO NOT EDIT.

option casemap:none

extern VirtualAlloc: proc

.data

.code
gen_run proc
        push rbx
        push rsi
        push rdi
        push r12
        push r13
        push r14
        push r15
        sub rsp, 64
        mov rbx, rcx
        add rbx, 7
        mov r10, 9
        add r10, 1
        shl r10, 3
        xor ecx, ecx
        mov rdx, r10
        mov r8, 3000h
        mov r9, 4
        call VirtualAlloc
        mov rsi, rax
        mov qword ptr [rsi], 9
        mov rdi, rbx
        mov rbx, 0
Ltop5:
        cmp rbx, 9
        jl Lelse7
        mov rbx, rsi
        jmp Lbuilt4
Lelse7:
        mov r12, rdi
        and r12, 16777215
        mov qword ptr [rsi+rbx*8+8], r12
        add rbx, 1
        mov rcx, 24
        shr rdi, cl
        jmp Ltop5
Lbuilt4:
        mov r10, 9
        add r10, 1
        shl r10, 3
        xor ecx, ecx
        mov rdx, r10
        mov r8, 3000h
        mov r9, 4
        call VirtualAlloc
        mov rsi, rax
        mov qword ptr [rsi], 9
        mov rdi, 0
Ltop12:
        cmp rdi, 6
        jge Lexit13
        xor r11d, r11d
Lzc15:
        cmp r11, 9
        jge Lzd15
        mov qword ptr [rsi+r11*8+8], 0
        inc r11
        jmp Lzc15
Lzd15:
        mov r12, rsi
        mov r13, 0
        mov r14, 0
Ltop17:
        cmp r13, 9
        jl Lelse19
        mov r13, qword ptr [r12]
        mov rax, 8
        cmp rax, r13
        jl Lelse20
        mov r13, 0
        jmp Ldone21
Lelse20:
        mov r13, qword ptr [r12+8*8+8]
Ldone21:
        cmp r13, 0
        jge Lelse22
        mov r13, 0
        jmp Ldone23
Lelse22:
        and r13, 16777215
Ldone23:
        cmp r13, 512
        jge Lelse25
        mov r13, 0
        jmp Ldone26
Lelse25:
        mov r13, 1
Ldone26:
        add r14, r13
        test r14, r14
        jz Ltz28
        ud2
        Ltz28:
        xor r14, r14
        cmp r14, 0
        jne Lbuilt16
        jmp Lbuilt16
Lelse19:
        cmp r13, 0
        jge Lelse30
        mov r15, 0
        jmp Ldone31
Lelse30:
        mov r15, qword ptr [rbx]
        cmp r13, r15
        jl Lelse32
        mov r15, 0
        jmp Ldone31
Lelse32:
        mov r15, qword ptr [rbx+r13*8+8]
Ldone31:
        cmp r15, 0
        jge Lelse33
        mov r15, 0
        jmp Ldone34
Lelse33:
        and r15, 16777215
Ldone34:
        imul r15, 999983
        add r15, r14
        mov r14, r15
        and r14, 16777215
        mov qword ptr [r12+r13*8+8], r14
        add r13, 1
        mov rcx, 24
        shr r15, cl
        mov r14, r15
        jmp Ltop17
Lbuilt16:
        add rdi, 1
        mov rsi, rbx
        mov rbx, r12
        jmp Ltop12
Lexit13:
        mov r10, 9
        add r10, 1
        shl r10, 3
        xor ecx, ecx
        mov rdx, r10
        mov r8, 3000h
        mov r9, 4
        call VirtualAlloc
        mov rsi, rax
        mov qword ptr [rsi], 9
        mov rdi, 8
        mov r12, 0
Ltop44:
        cmp rdi, 0
        jl Lbuilt43
        imul r12, 16777216
        cmp rdi, 0
        jge Lelse48
        mov r13, 0
        jmp Ldone49
Lelse48:
        mov r13, qword ptr [rbx]
        cmp rdi, r13
        jl Lelse50
        mov r13, 0
        jmp Ldone49
Lelse50:
        mov r13, qword ptr [rbx+rdi*8+8]
Ldone49:
        cmp r13, 0
        jge Lelse51
        mov r13, 0
        jmp Ldone52
Lelse51:
        and r13, 16777215
Ldone52:
        add r12, r13
        mov rax, r12
        cqo
        mov rcx, 100000000
        idiv rcx
        mov r13, rax
        mov qword ptr [rsi+rdi*8+8], r13
        sub rdi, 1
        mov rax, r12
        cqo
        mov rcx, 100000000
        idiv rcx
        mov r13, rdx
        mov r12, r13
        jmp Ltop44
Lbuilt43:
        mov rdi, 8
        mov r12, 0
Ltop58:
        cmp rdi, 0
        jge Lelse60
        mov qword ptr [rsp+48], r12
        jmp Lexit59
Lelse60:
        imul r12, 16777216
        cmp rdi, 0
        jge Lelse62
        mov r13, 0
        jmp Ldone63
Lelse62:
        mov r13, qword ptr [rsi]
        cmp rdi, r13
        jl Lelse64
        mov r13, 0
        jmp Ldone63
Lelse64:
        mov r13, qword ptr [rsi+rdi*8+8]
Ldone63:
        sub rdi, 1
        cmp r13, 0
        jge Lelse66
        mov r13, 0
        jmp Ldone67
Lelse66:
        and r13, 16777215
Ldone67:
        add r12, r13
        mov rax, r12
        cqo
        mov rcx, 100000000
        idiv rcx
        mov r13, rdx
        mov r12, r13
        jmp Ltop58
Lexit59:
        mov r10, 9
        add r10, 1
        shl r10, 3
        xor ecx, ecx
        mov rdx, r10
        mov r8, 3000h
        mov r9, 4
        call VirtualAlloc
        mov rsi, rax
        mov qword ptr [rsi], 9
        mov r12, 0
        mov r13, 11
Ltop73:
        cmp r12, 9
        jge Lbuilt72
        mov r14, r13
        and r14, 16777215
        mov qword ptr [rsi+r12*8+8], r14
        add r12, 1
        mov rcx, 24
        shr r13, cl
        jmp Ltop73
Lbuilt72:
        mov r10, 9
        add r10, 1
        shl r10, 3
        xor ecx, ecx
        mov rdx, r10
        mov r8, 3000h
        mov r9, 4
        call VirtualAlloc
        mov r12, rax
        mov qword ptr [r12], 9
        mov qword ptr [rsp+56], 0
Ltop80:
        mov rax, qword ptr [rsp+56]
        cmp rax, 6
        jge Lexit81
        xor r11d, r11d
Lzc83:
        cmp r11, 9
        jge Lzd83
        mov qword ptr [r12+r11*8+8], 0
        inc r11
        jmp Lzc83
Lzd83:
        mov r14, r12
        mov r15, 0
        mov rdi, 0
Ltop85:
        cmp r15, 9
        jl Lelse87
        mov r15, qword ptr [r14]
        mov rax, 8
        cmp rax, r15
        jl Lelse88
        mov r15, 0
        jmp Ldone89
Lelse88:
        mov r15, qword ptr [r14+8*8+8]
Ldone89:
        cmp r15, 0
        jge Lelse90
        mov r15, 0
        jmp Ldone91
Lelse90:
        and r15, 16777215
Ldone91:
        cmp r15, 512
        jge Lelse93
        mov r15, 0
        jmp Ldone94
Lelse93:
        mov r15, 1
Ldone94:
        add rdi, r15
        test rdi, rdi
        jz Ltz96
        ud2
        Ltz96:
        xor rdi, rdi
        cmp rdi, 0
        jne Lelse97
        mov rdi, r14
        jmp Lbuilt84
Lelse97:
        mov rdi, r14
        jmp Lbuilt84
Lelse87:
        cmp r15, 0
        jge Lelse98
        mov r13, 0
        jmp Ldone99
Lelse98:
        mov r13, qword ptr [rsi]
        cmp r15, r13
        jl Lelse100
        mov r13, 0
        jmp Ldone99
Lelse100:
        mov r13, qword ptr [rsi+r15*8+8]
Ldone99:
        cmp r13, 0
        jge Lelse101
        mov r13, 0
        jmp Ldone102
Lelse101:
        and r13, 16777215
Ldone102:
        imul r13, 999983
        add r13, rdi
        mov rdi, r13
        and rdi, 16777215
        mov qword ptr [r14+r15*8+8], rdi
        add r15, 1
        mov rcx, 24
        shr r13, cl
        mov rdi, r13
        jmp Ltop85
Lbuilt84:
        mov r10, qword ptr [rsp+56]
        mov r13, r10
        add r13, 1
        mov qword ptr [rsp+56], r13
        mov r12, rsi
        mov rsi, rdi
        jmp Ltop80
Lexit81:
        mov rdi, 8
Ltop110:
        cmp rdi, 0
        jge Lelse112
        mov rdi, 0
        jmp Lexit111
Lelse112:
        cmp rdi, 0
        jge Lelse113
        mov r12, 0
        jmp Ldone114
Lelse113:
        mov r12, qword ptr [rbx]
        cmp rdi, r12
        jl Lelse115
        mov r12, 0
        jmp Ldone114
Lelse115:
        mov r12, qword ptr [rbx+rdi*8+8]
Ldone114:
        cmp r12, 0
        jge Lelse116
        mov r12, 0
        jmp Ldone117
Lelse116:
        and r12, 16777215
Ldone117:
        cmp rdi, 0
        jge Lelse119
        mov r13, 0
        jmp Ldone120
Lelse119:
        mov r13, qword ptr [rsi]
        cmp rdi, r13
        jl Lelse121
        mov r13, 0
        jmp Ldone120
Lelse121:
        mov r13, qword ptr [rsi+rdi*8+8]
Ldone120:
        cmp r13, 0
        jge Lelse122
        mov r13, 0
        jmp Ldone123
Lelse122:
        and r13, 16777215
Ldone123:
        cmp r12, r13
        jle Lelse125
        mov rdi, 1
        jmp Lexit111
Lelse125:
        cmp rdi, 0
        jge Lelse126
        mov r12, 0
        jmp Ldone127
Lelse126:
        mov r12, qword ptr [rbx]
        cmp rdi, r12
        jl Lelse128
        mov r12, 0
        jmp Ldone127
Lelse128:
        mov r12, qword ptr [rbx+rdi*8+8]
Ldone127:
        cmp r12, 0
        jge Lelse129
        mov r12, 0
        jmp Ldone130
Lelse129:
        and r12, 16777215
Ldone130:
        cmp rdi, 0
        jge Lelse132
        mov r13, 0
        jmp Ldone133
Lelse132:
        mov r13, qword ptr [rsi]
        cmp rdi, r13
        jl Lelse134
        mov r13, 0
        jmp Ldone133
Lelse134:
        mov r13, qword ptr [rsi+rdi*8+8]
Ldone133:
        cmp r13, 0
        jge Lelse135
        mov r13, 0
        jmp Ldone136
Lelse135:
        and r13, 16777215
Ldone136:
        cmp r12, r13
        jge Lelse138
        mov rdi, -1
        jmp Lexit111
Lelse138:
        sub rdi, 1
        jmp Ltop110
Lexit111:
        cmp rdi, 0
        jle Lelse140
        mov rbx, 1000000000000
        jmp Ldone141
Lelse140:
        mov rbx, 0
Ldone141:
        mov r10, qword ptr [rsp+48]
        mov rsi, r10
        add rsi, rbx
        mov rax, rsi
Lret1:
        add rsp, 64
        pop r15
        pop r14
        pop r13
        pop r12
        pop rdi
        pop rsi
        pop rbx
        ret
gen_run endp


end
