// Code generated by oroboros. DO NOT EDIT.

export function genRun(v0) {
	const v3 = new Array(3).fill(0);
	let v2;
	let v7 = v3;
	let v8 = 0;
	let v9 = 999999999999999;
	for (;; v8 = (v8 + 1)) {
		if ((v8 >= 3)) {
			break;
		}
		v7[v8] = (((v9 % 16777216) + 0));
		v9 = ((Math.trunc(v9 / 16777216) + 0));
		continue;
	}
	v2 = v7;
	const v23 = new Array(3).fill(0);
	let v22;
	let v27 = v23;
	let v28 = 0;
	let v29 = 14000000;
	for (;; v28 = (v28 + 1)) {
		if ((v28 >= 3)) {
			break;
		}
		v27[v28] = (v29 & 16777215);
		v29 = (v29 >> 24);
		continue;
	}
	v22 = v27;
	const v43 = new Array(3).fill(0);
	let v42;
	let v47 = v43;
	let v48 = 0;
	let v49 = 0;
	for (;; v48 = (v48 + 1)) {
		if ((v48 >= 3)) {
			break;
		}
		const v83 = ((((v48 < 0) ? 0 : ((v48 >= v2.length) ? 0 : v2[v48])) - ((v48 < 0) ? 0 : ((v48 >= v22.length) ? 0 : v22[v48]))) - v49);
		v47[v48] = ((v83 < 0) ? (v83 + 16777216) : v83);
		v49 = ((v83 < 0) ? 1 : 0);
		continue;
	}
	v42 = v47;
	const v103 = new Array(3).fill(0);
	let v102;
	let v107 = v103;
	let v108 = 2;
	let v109 = 0;
	for (;;) {
		if ((v108 < 0)) {
			break;
		}
		const v130 = ((v109 * 16777216) + ((v108 < 0) ? 0 : ((v108 >= v42.length) ? 0 : v42[v108])));
		v107[v108] = ((Math.trunc(v130 / 7) + 0));
		v108 = (v108 - 1);
		v109 = (((v130 % 7) + 0));
		continue;
	}
	v102 = v107;
	const v153 = (v0 + 1);
	return (((v0 < 0) ? 0 : ((v0 >= v102.length) ? 0 : v102[v0])) + (((v153 < 0) ? 0 : ((v153 >= v102.length) ? 0 : v102[v153])) * 100000000));
}

