; Code generated by oroboros. DO NOT EDIT.

option casemap:none


.data

.code
gen_run proc
        push rbx
        push rsi
        push rdi
        push r12
        sub rsp, 56
        mov rbx, rcx
        mov rsi, rbx
        add rsi, 1
        jno Lok2
        ud2
        Lok2:
        mov rdi, 0
        sub rdi, rsi
        jno Lok3
        ud2
        Lok3:
        mov rax, rdi
        cqo
        mov rcx, 2
        idiv rcx
        mov rsi, rax
        imul rsi, 100
        jno Lok5
        ud2
        Lok5:
        mov rax, rdi
        cqo
        mov rcx, 8
        idiv rcx
        mov r12, rdx
        add rsi, r12
        jno Lok7
        ud2
        Lok7:
        imul rbx, 300000000
        jno Lok8
        ud2
        Lok8:
        mov rax, rbx
        cqo
        mov rcx, 4
        idiv rcx
        mov rdi, rax
        add rsi, rdi
        jno Lok10
        ud2
        Lok10:
        mov rbx, 1000000
        add rbx, rsi
        jno Lok11
        ud2
        Lok11:
        mov rax, rbx
Lret1:
        add rsp, 56
        pop r12
        pop rdi
        pop rsi
        pop rbx
        ret
gen_run endp


end
