// Code generated by oroboros. DO NOT EDIT.

export function genRun(v0) {
	let v13 = (BigInt(1));
	let v14 = 2;
	for (;; v14 = (v14 + 1)) {
		if ((v14 > (25 + v0))) {
			break;
		}
		const v23 = ((function(oroZ, oroK){ if ((oroZ >> BigInt(oroK)) !== 0n) throw new Error("bignum overflow: the declared range is too small"); return oroZ; })(((v13 * (BigInt(v14)))), 201));
		v13 = v23;
		continue;
	}
	if (((v13 === (BigInt(0))))) {
		return "0";
	}
	let v33 = "";
	let v34 = v13;
	let v35 = 0;
	for (;; v35 = (v35 + 1)) {
		if (((v34 === (BigInt(0))))) {
			break;
		}
		if ((v35 >= 32)) {
			break;
		}
		const v47 = ((function(oroZ, oroK){ if ((oroZ >> BigInt(oroK)) !== 0n) throw new Error("bignum overflow: the declared range is too small"); return oroZ; })(((v34 / (BigInt(100000000)))), 201));
		let v53 = "";
		let v54 = 0;
		let v55 = (Number(v34 % BigInt(100000000)));
		for (;; v54 = (v54 + 1)) {
			if ((v54 >= 8)) {
				break;
			}
			if (((!((v47 > (BigInt(0))))) && ((v55 === 0) && (v54 > 0)))) {
				break;
			}
			v53 = ((String.fromCodePoint((48 + (((v55 % 10) + 0))))) + v53);
			v55 = ((Math.trunc(v55 / 10) + 0));
			continue;
		}
		v33 = (v53 + v33);
		v34 = v47;
		continue;
	}
	return v33;
}

