// Code generated by oroboros. DO NOT EDIT.

public final class gauntlet_differential_cases_render.java {
	public static String genRun(long n) {
		java.math.BigInteger acc = (java.math.BigInteger.valueOf(1));
		java.math.BigInteger i = (java.math.BigInteger.valueOf(2));
		for (;;) {
			if ((i.compareTo((java.math.BigInteger.valueOf((25 + n)))) > 0)) {
				break;
			}
			final var u1 = (((java.util.function.BiFunction<java.math.BigInteger,Long,java.math.BigInteger>)((oro$z, oro$k) -> { if (oro$z.signum() < 0 || oro$z.bitLength() > oro$k) throw new ArithmeticException("bignum overflow: the declared range is too small"); return oro$z; })).apply((acc.multiply(i)), (long)(201)));
			final var u2 = (((java.util.function.BiFunction<java.math.BigInteger,Long,java.math.BigInteger>)((oro$z, oro$k) -> { if (oro$z.signum() < 0 || oro$z.bitLength() > oro$k) throw new ArithmeticException("bignum overflow: the declared range is too small"); return oro$z; })).apply((i.add((java.math.BigInteger.valueOf(1)))), (long)(201)));
			acc = u1;
			i = u2;
			continue;
		}
		final java.math.BigInteger x = acc;
		String t5;
		if ((x.compareTo((java.math.BigInteger.valueOf(0))) == 0)) {
			t5 = "0";
		} else {
			String s3 = "";
			java.math.BigInteger v2 = x;
			int i3 = 0;
			for (;; i3 = (i3 + 1)) {
				if ((v2.compareTo((java.math.BigInteger.valueOf(0))) == 0)) {
					break;
				}
				if ((i3 >= 32)) {
					break;
				}
				final java.math.BigInteger nv19172 = (((java.util.function.BiFunction<java.math.BigInteger,Long,java.math.BigInteger>)((oro$z, oro$k) -> { if (oro$z.signum() < 0 || oro$z.bitLength() > oro$k) throw new ArithmeticException("bignum overflow: the declared range is too small"); return oro$z; })).apply((v2.divide((java.math.BigInteger.valueOf(100000000)))), (long)(201)));
				String s22 = "";
				int k2 = 0;
				long r2 = (v2.remainder(java.math.BigInteger.valueOf(100000000)).longValue());
				for (;; k2 = (k2 + 1), r2 = (r2 / 10)) {
					if ((k2 >= 8)) {
						break;
					}
					if (((!(nv19172.compareTo((java.math.BigInteger.valueOf(0))) > 0)) && ((r2 == 0) && (k2 > 0)))) {
						break;
					}
					s22 = ((new String(Character.toChars((int) (48 + (r2 % 10))))).concat(s22));
					continue;
				}
				final var u6 = (s22.concat(s3));
				final var u7 = nv19172;
				s3 = u6;
				v2 = u7;
				continue;
			}
			t5 = s3;
		}
		return t5;
	}

}
