// Code generated by oroboros. DO NOT EDIT.

export function genCalc(v0) {
	const v15 = ((function(oroZ, oroK){ if (((oroZ < 0n ? -oroZ : oroZ) >> BigInt(oroK)) !== 0n) throw new Error("bignum overflow: the declared range is too small"); return oroZ; })((((BigInt(1606938044258990)) * (BigInt(1000000000000000)))), 201));
	const v20 = ((function(oroZ, oroK){ if (((oroZ < 0n ? -oroZ : oroZ) >> BigInt(oroK)) !== 0n) throw new Error("bignum overflow: the declared range is too small"); return oroZ; })(((v15 + (BigInt(275541962092341)))), 201));
	const v25 = ((function(oroZ, oroK){ if (((oroZ < 0n ? -oroZ : oroZ) >> BigInt(oroK)) !== 0n) throw new Error("bignum overflow: the declared range is too small"); return oroZ; })(((v20 * (BigInt(1000000000000000)))), 201));
	const v30 = ((function(oroZ, oroK){ if (((oroZ < 0n ? -oroZ : oroZ) >> BigInt(oroK)) !== 0n) throw new Error("bignum overflow: the declared range is too small"); return oroZ; })(((v25 + (BigInt(162602522202993)))), 201));
	const v35 = ((function(oroZ, oroK){ if (((oroZ < 0n ? -oroZ : oroZ) >> BigInt(oroK)) !== 0n) throw new Error("bignum overflow: the declared range is too small"); return oroZ; })(((v30 * (BigInt(1000000000000000)))), 201));
	const v40 = ((function(oroZ, oroK){ if (((oroZ < 0n ? -oroZ : oroZ) >> BigInt(oroK)) !== 0n) throw new Error("bignum overflow: the declared range is too small"); return oroZ; })(((v35 + (BigInt(782792835301376)))), 201));
	const v45 = ((function(oroZ, oroK){ if (((oroZ < 0n ? -oroZ : oroZ) >> BigInt(oroK)) !== 0n) throw new Error("bignum overflow: the declared range is too small"); return oroZ; })((((BigInt(0)) - v40)), 201));
	let v48;
	if ((v0 === 0)) {
		v48 = (BigInt(0));
	} else {
		if ((v0 === 1)) {
			const v60 = ((function(oroZ, oroK){ if (((oroZ < 0n ? -oroZ : oroZ) >> BigInt(oroK)) !== 0n) throw new Error("bignum overflow: the declared range is too small"); return oroZ; })(((v40 - (BigInt(1)))), 201));
			v48 = v60;
		} else {
			v48 = v40;
		}
	}
	const v64 = ((function(oroZ, oroK){ if (((oroZ < 0n ? -oroZ : oroZ) >> BigInt(oroK)) !== 0n) throw new Error("bignum overflow: the declared range is too small"); return oroZ; })(((v45 - v48)), 201));
	return v64;
}

