// Code generated by oroboros. DO NOT EDIT.

export function genRun(n) {
	let acc = (BigInt((n + 7)));
	let i = 0;
	for (;; i = (i + 1)) {
		if ((i >= 6)) {
			break;
		}
		acc = ((function(oroZ, oroK){ if ((oroZ >> BigInt(oroK)) !== 0n) throw new Error("bignum overflow: the declared range is too small"); return oroZ; })(((acc * (BigInt(999983)))), 201));
		continue;
	}
	const x = acc;
	let acc2 = (BigInt(11));
	let i2 = 0;
	for (;; i2 = (i2 + 1)) {
		if ((i2 >= 6)) {
			break;
		}
		acc2 = ((function(oroZ, oroK){ if ((oroZ >> BigInt(oroK)) !== 0n) throw new Error("bignum overflow: the declared range is too small"); return oroZ; })(((acc2 * (BigInt(999983)))), 201));
		continue;
	}
	return ((Number(((function(oroZ, oroK){ if ((oroZ >> BigInt(oroK)) !== 0n) throw new Error("bignum overflow: the declared range is too small"); return oroZ; })(((x / (BigInt(100000000)))), 201)) % BigInt(100000000))) + (((x > acc2)) ? 1000000000000 : 0));
}

