; Code generated by oroboros. DO NOT EDIT.

option casemap:none

extern VirtualAlloc: proc

.data
__sarena db 262144 dup(0)
__stop   qword 0
LS228 db 030h,0
LS228_len equ 1
LS229 db 0
LS229_len equ 0

.code
gen_run proc
        push rbx
        push rsi
        push rdi
        push r12
        push r13
        push r14
        push r15
        sub rsp, 96
        mov qword ptr [rsp+48], rcx
        mov r10, 9
        add r10, 1
        shl r10, 3
        xor ecx, ecx
        mov rdx, r10
        mov r8, 3000h
        mov r9, 4
        call VirtualAlloc
        mov rsi, rax
        mov qword ptr [rsi], 9
        mov rdi, 0
        mov r12, 1
Ltop4:
        cmp rdi, 9
        jge Lbuilt3
        mov r13, r12
        and r13, 16777215
        mov qword ptr [rsi+rdi*8+8], r13
        add rdi, 1
        mov rcx, 24
        shr r12, cl
        jmp Ltop4
Lbuilt3:
        mov r10, 9
        add r10, 1
        shl r10, 3
        xor ecx, ecx
        mov rdx, r10
        mov r8, 3000h
        mov r9, 4
        call VirtualAlloc
        mov rdi, rax
        mov qword ptr [rdi], 9
        mov r12, 0
        mov r13, 2
Ltop12:
        cmp r12, 9
        jge Lbuilt11
        mov r14, r13
        and r14, 16777215
        mov qword ptr [rdi+r12*8+8], r14
        add r12, 1
        mov rcx, 24
        shr r13, cl
        jmp Ltop12
Lbuilt11:
        mov r10, 9
        add r10, 1
        shl r10, 3
        xor ecx, ecx
        mov rdx, r10
        mov r8, 3000h
        mov r9, 4
        call VirtualAlloc
        mov qword ptr [rsp+56], rax
        mov qword ptr [rax], 9
        mov r10, 9
        add r10, 1
        shl r10, 3
        xor ecx, ecx
        mov rdx, r10
        mov r8, 3000h
        mov r9, 4
        call VirtualAlloc
        mov qword ptr [rsp+64], rax
        mov qword ptr [rax], 9
Ltop20:
        mov r10, 9
        add r10, 1
        shl r10, 3
        xor ecx, ecx
        mov rdx, r10
        mov r8, 3000h
        mov r9, 4
        call VirtualAlloc
        mov r14, rax
        mov qword ptr [r14], 9
        mov r10, qword ptr [rsp+48]
        mov r15, 25
        add r15, r10
        mov rbx, r15
        mov r15, 0
Ltop25:
        cmp r15, 9
        jl Lelse27
        mov rbx, r14
        jmp Lbuilt23
Lelse27:
        mov r12, rbx
        and r12, 16777215
        mov qword ptr [r14+r15*8+8], r12
        add r15, 1
        mov rcx, 24
        shr rbx, cl
        jmp Ltop25
Lbuilt23:
        mov r12, 8
Ltop31:
        cmp r12, 0
        jge Lelse33
        mov r12, 0
        jmp Lexit32
Lelse33:
        cmp r12, 0
        jge Lelse34
        mov r14, 0
        jmp Ldone35
Lelse34:
        mov r14, qword ptr [rdi]
        cmp r12, r14
        jl Lelse36
        mov r14, 0
        jmp Ldone35
Lelse36:
        mov r14, qword ptr [rdi+r12*8+8]
Ldone35:
        cmp r14, 0
        jge Lelse37
        mov r14, 0
        jmp Ldone38
Lelse37:
        and r14, 16777215
Ldone38:
        cmp r12, 0
        jge Lelse40
        mov r15, 0
        jmp Ldone41
Lelse40:
        mov r15, qword ptr [rbx]
        cmp r12, r15
        jl Lelse42
        mov r15, 0
        jmp Ldone41
Lelse42:
        mov r15, qword ptr [rbx+r12*8+8]
Ldone41:
        cmp r15, 0
        jge Lelse43
        mov r15, 0
        jmp Ldone44
Lelse43:
        and r15, 16777215
Ldone44:
        cmp r14, r15
        jle Lelse46
        mov r12, 1
        jmp Lexit32
Lelse46:
        cmp r12, 0
        jge Lelse47
        mov r14, 0
        jmp Ldone48
Lelse47:
        mov r14, qword ptr [rdi]
        cmp r12, r14
        jl Lelse49
        mov r14, 0
        jmp Ldone48
Lelse49:
        mov r14, qword ptr [rdi+r12*8+8]
Ldone48:
        cmp r14, 0
        jge Lelse50
        mov r14, 0
        jmp Ldone51
Lelse50:
        and r14, 16777215
Ldone51:
        cmp r12, 0
        jge Lelse53
        mov r15, 0
        jmp Ldone54
Lelse53:
        mov r15, qword ptr [rbx]
        cmp r12, r15
        jl Lelse55
        mov r15, 0
        jmp Ldone54
Lelse55:
        mov r15, qword ptr [rbx+r12*8+8]
Ldone54:
        cmp r15, 0
        jge Lelse56
        mov r15, 0
        jmp Ldone57
Lelse56:
        and r15, 16777215
Ldone57:
        cmp r14, r15
        jge Lelse59
        mov r12, -1
        jmp Lexit32
Lelse59:
        sub r12, 1
        jmp Ltop31
Lexit32:
        cmp r12, 0
        jle Lelse61
        mov rbx, rsi
        jmp Lexit21
Lelse61:
        mov r10, qword ptr [rsp+56]
        xor r11d, r11d
Lzc62:
        cmp r11, 9
        jge Lzd62
        mov qword ptr [r10+r11*8+8], 0
        inc r11
        jmp Lzc62
Lzd62:
        mov rbx, qword ptr [rsp+56]
        mov r12, 0
Ltop64:
        cmp r12, 9
        jge Lexit65
        mov r14, 0
        mov r15, 0
Ltop67:
        cmp r14, 9
        jl Lelse69
        mov rax, 8
        cmp rax, 0
        jge Lelse70
        mov r14, 0
        jmp Ldone71
Lelse70:
        mov r14, qword ptr [rbx]
        mov rax, 8
        cmp rax, r14
        jl Lelse72
        mov r14, 0
        jmp Ldone71
Lelse72:
        mov r14, qword ptr [rbx+8*8+8]
Ldone71:
        cmp r14, 0
        jge Lelse73
        mov r14, 0
        jmp Ldone74
Lelse73:
        and r14, 16777215
Ldone74:
        cmp r14, 512
        jge Lelse76
        mov r14, 0
        jmp Ldone77
Lelse76:
        mov r14, 1
Ldone77:
        add r15, r14
        test r15, r15
        jz Ltz79
        ud2
        Ltz79:
        xor r15, r15
        cmp r15, 0
        jne Lexit68
        jmp Lexit68
Lelse69:
        mov r13, r12
        add r13, r14
        cmp r13, 9
        jl Lelse82
        mov rax, 8
        cmp rax, 0
        jge Lelse83
        mov r13, 0
        jmp Ldone84
Lelse83:
        mov r13, qword ptr [rbx]
        mov rax, 8
        cmp rax, r13
        jl Lelse85
        mov r13, 0
        jmp Ldone84
Lelse85:
        mov r13, qword ptr [rbx+8*8+8]
Ldone84:
        cmp r13, 0
        jge Lelse86
        mov r13, 0
        jmp Ldone87
Lelse86:
        and r13, 16777215
Ldone87:
        cmp r13, 512
        jge Lelse89
        mov r13, 0
        jmp Ldone90
Lelse89:
        mov r13, 1
Ldone90:
        add r15, r13
        test r15, r15
        jz Ltz92
        ud2
        Ltz92:
        xor r15, r15
        cmp r15, 0
        je Ldone94
Ldone94:
        cmp r12, 0
        jge Lelse95
        mov r13, 0
        jmp Ldone96
Lelse95:
        mov r13, qword ptr [rsi]
        cmp r12, r13
        jl Lelse97
        mov r13, 0
        jmp Ldone96
Lelse97:
        mov r13, qword ptr [rsi+r12*8+8]
Ldone96:
        cmp r13, 0
        jge Lelse98
        mov r13, 0
        jmp Ldone99
Lelse98:
        and r13, 16777215
Ldone99:
        cmp r14, 0
        jge Lelse101
        mov r15, 0
        jmp Ldone102
Lelse101:
        mov r15, qword ptr [rdi]
        cmp r14, r15
        jl Lelse103
        mov r15, 0
        jmp Ldone102
Lelse103:
        mov r15, qword ptr [rdi+r14*8+8]
Ldone102:
        cmp r15, 0
        jge Lelse104
        mov r15, 0
        jmp Ldone105
Lelse104:
        and r15, 16777215
Ldone105:
        imul r13, r15
        mov rax, 8
        cmp rax, 0
        jge Lelse108
        mov r15, 0
        jmp Ldone109
Lelse108:
        mov r15, qword ptr [rbx]
        mov rax, 8
        cmp rax, r15
        jl Lelse110
        mov r15, 0
        jmp Ldone109
Lelse110:
        mov r15, qword ptr [rbx+8*8+8]
Ldone109:
        cmp r15, 0
        jge Lelse111
        mov r15, 0
        jmp Ldone112
Lelse111:
        and r15, 16777215
Ldone112:
        cmp r15, 512
        jge Lelse114
        mov r15, 0
        jmp Ldone115
Lelse114:
        mov r15, 1
Ldone115:
        add r13, r15
        test r13, r13
        jz Ltz117
        ud2
        Ltz117:
        xor r13, r13
        cmp r13, 0
        je Ldone119
Ldone119:
        add r14, 1
        mov r15, 0
        jmp Ltop67
Lelse82:
        mov r13, r12
        add r13, r14
        cmp r13, 0
        jge Lelse122
        mov r13, 0
        jmp Ldone123
Lelse122:
        mov rax, qword ptr [rbx]
        mov qword ptr [rsp+72], rax
        cmp r13, qword ptr [rsp+72]
        jl Lelse124
        mov r13, 0
        jmp Ldone123
Lelse124:
        mov rax, qword ptr [rbx+r13*8+8]
        mov qword ptr [rsp+72], rax
        mov r13, qword ptr [rsp+72]
Ldone123:
        cmp r13, 0
        jge Lelse125
        mov qword ptr [rsp+80], 0
        jmp Ldone126
Lelse125:
        and r13, 16777215
        mov qword ptr [rsp+80], r13
Ldone126:
        cmp r12, 0
        jge Lelse128
        mov r13, 0
        jmp Ldone129
Lelse128:
        mov rax, qword ptr [rsi]
        mov qword ptr [rsp+72], rax
        cmp r12, qword ptr [rsp+72]
        jl Lelse130
        mov r13, 0
        jmp Ldone129
Lelse130:
        mov rax, qword ptr [rsi+r12*8+8]
        mov qword ptr [rsp+72], rax
        mov r13, qword ptr [rsp+72]
Ldone129:
        cmp r13, 0
        jge Lelse131
        mov qword ptr [rsp+88], 0
        jmp Ldone132
Lelse131:
        and r13, 16777215
        mov qword ptr [rsp+88], r13
Ldone132:
        cmp r14, 0
        jge Lelse134
        mov r13, 0
        jmp Ldone135
Lelse134:
        mov rax, qword ptr [rdi]
        mov qword ptr [rsp+72], rax
        cmp r14, qword ptr [rsp+72]
        jl Lelse136
        mov r13, 0
        jmp Ldone135
Lelse136:
        mov rax, qword ptr [rdi+r14*8+8]
        mov qword ptr [rsp+72], rax
        mov r13, qword ptr [rsp+72]
Ldone135:
        cmp r13, 0
        jge Lelse137
        mov r13, 0
        jmp Ldone138
Lelse137:
        and r13, 16777215
Ldone138:
        mov r10, qword ptr [rsp+88]
        mov rax, r10
        imul rax, r13
        mov qword ptr [rsp+72], rax
        mov r10, qword ptr [rsp+80]
        mov r11, qword ptr [rsp+72]
        mov r13, r10
        add r13, r11
        add r13, r15
        mov r15, r12
        add r15, r14
        mov rax, r13
        and rax, 16777215
        mov qword ptr [rsp+72], rax
        mov rax, qword ptr [rsp+72]
        mov qword ptr [rbx+r15*8+8], rax
        add r14, 1
        mov rcx, 24
        shr r13, cl
        mov r15, r13
        jmp Ltop67
Lexit68:
        add r12, 1
        jmp Ltop64
Lexit65:
        mov qword ptr [rsp+72], rbx
        mov r10, 9
        add r10, 8
        xor ecx, ecx
        mov rdx, r10
        mov r8, 3000h
        mov r9, 4
        call VirtualAlloc
        mov r12, rax
        mov qword ptr [r12], 9
        mov r13, 0
        mov r14, 1
Ltop150:
        cmp r13, 9
        jge Lbuilt149
        mov r15, r14
        and r15, 16777215
        mov byte ptr [r12+r13+8], r15b
        add r13, 1
        mov rcx, 24
        shr r14, cl
        jmp Ltop150
Lbuilt149:
        mov r10, qword ptr [rsp+64]
        xor r11d, r11d
Lzc156:
        cmp r11, 9
        jge Lzd156
        mov qword ptr [r10+r11*8+8], 0
        inc r11
        jmp Lzc156
Lzd156:
        mov r13, qword ptr [rsp+64]
        mov r14, 0
        mov r15, 0
Ltop158:
        cmp r14, 9
        jl Lelse160
        mov rax, 8
        cmp rax, 0
        jge Lelse161
        mov r14, 0
        jmp Ldone162
Lelse161:
        mov r14, qword ptr [r13]
        mov rax, 8
        cmp rax, r14
        jl Lelse163
        mov r14, 0
        jmp Ldone162
Lelse163:
        mov r14, qword ptr [r13+8*8+8]
Ldone162:
        cmp r14, 0
        jge Lelse164
        mov r14, 0
        jmp Ldone165
Lelse164:
        and r14, 16777215
Ldone165:
        cmp r14, 512
        jge Lelse167
        mov r14, 0
        jmp Ldone168
Lelse167:
        mov r14, 1
Ldone168:
        add r15, r14
        test r15, r15
        jz Ltz170
        ud2
        Ltz170:
        xor r15, r15
        cmp r15, 0
        jne Lelse171
        mov rbx, r13
        jmp Lbuilt157
Lelse171:
        mov rbx, r13
        jmp Lbuilt157
Lelse160:
        cmp r14, 0
        jge Lelse172
        mov rbx, 0
        jmp Ldone173
Lelse172:
        mov rbx, qword ptr [rdi]
        cmp r14, rbx
        jl Lelse174
        mov rbx, 0
        jmp Ldone173
Lelse174:
        mov rbx, qword ptr [rdi+r14*8+8]
Ldone173:
        cmp rbx, 0
        jge Lelse175
        mov qword ptr [rsp+88], 0
        jmp Ldone176
Lelse175:
        and rbx, 16777215
        mov qword ptr [rsp+88], rbx
Ldone176:
        cmp r14, 0
        jge Lelse178
        mov rbx, 0
        jmp Ldone179
Lelse178:
        mov rax, qword ptr [r12]
        mov qword ptr [rsp+80], rax
        cmp r14, qword ptr [rsp+80]
        jl Lelse180
        mov rbx, 0
        jmp Ldone179
Lelse180:
        movzx eax, byte ptr [r12+r14+8]
        mov qword ptr [rsp+80], rax
        mov rbx, qword ptr [rsp+80]
Ldone179:
        cmp rbx, 0
        jge Lelse181
        mov rbx, 0
        jmp Ldone182
Lelse181:
        and rbx, 16777215
Ldone182:
        mov r10, qword ptr [rsp+88]
        mov rax, r10
        add rax, rbx
        mov qword ptr [rsp+80], rax
        mov r10, qword ptr [rsp+80]
        mov rbx, r10
        add rbx, r15
        mov r15, rbx
        and r15, 16777215
        mov qword ptr [r13+r14*8+8], r15
        add r14, 1
        mov rcx, 24
        shr rbx, cl
        mov r15, rbx
        jmp Ltop158
Lbuilt157:
        mov qword ptr [rsp+56], rsi
        mov rsi, qword ptr [rsp+72]
        mov qword ptr [rsp+64], rdi
        mov rdi, rbx
        jmp Ltop20
Lexit21:
        mov r10, 9
        add r10, 8
        xor ecx, ecx
        mov rdx, r10
        mov r8, 3000h
        mov r9, 4
        call VirtualAlloc
        mov rsi, rax
        mov qword ptr [rsi], 9
        mov rdi, 0
        mov r12, 0
Ltop191:
        cmp rdi, 9
        jge Lbuilt190
        mov r13, r12
        and r13, 16777215
        mov byte ptr [rsi+rdi+8], r13b
        add rdi, 1
        mov rcx, 24
        shr r12, cl
        jmp Ltop191
Lbuilt190:
        mov rdi, 8
Ltop197:
        cmp rdi, 0
        jge Lelse199
        mov rdi, 0
        jmp Lexit198
Lelse199:
        cmp rdi, 0
        jge Lelse200
        mov r12, 0
        jmp Ldone201
Lelse200:
        mov r12, qword ptr [rbx]
        cmp rdi, r12
        jl Lelse202
        mov r12, 0
        jmp Ldone201
Lelse202:
        mov r12, qword ptr [rbx+rdi*8+8]
Ldone201:
        cmp r12, 0
        jge Lelse203
        mov r12, 0
        jmp Ldone204
Lelse203:
        and r12, 16777215
Ldone204:
        cmp rdi, 0
        jge Lelse206
        mov r13, 0
        jmp Ldone207
Lelse206:
        mov r13, qword ptr [rsi]
        cmp rdi, r13
        jl Lelse208
        mov r13, 0
        jmp Ldone207
Lelse208:
        movzx r13d, byte ptr [rsi+rdi+8]
Ldone207:
        cmp r13, 0
        jge Lelse209
        mov r13, 0
        jmp Ldone210
Lelse209:
        and r13, 16777215
Ldone210:
        cmp r12, r13
        jle Lelse212
        mov rdi, 1
        jmp Lexit198
Lelse212:
        cmp rdi, 0
        jge Lelse213
        mov r12, 0
        jmp Ldone214
Lelse213:
        mov r12, qword ptr [rbx]
        cmp rdi, r12
        jl Lelse215
        mov r12, 0
        jmp Ldone214
Lelse215:
        mov r12, qword ptr [rbx+rdi*8+8]
Ldone214:
        cmp r12, 0
        jge Lelse216
        mov r12, 0
        jmp Ldone217
Lelse216:
        and r12, 16777215
Ldone217:
        cmp rdi, 0
        jge Lelse219
        mov r13, 0
        jmp Ldone220
Lelse219:
        mov r13, qword ptr [rsi]
        cmp rdi, r13
        jl Lelse221
        mov r13, 0
        jmp Ldone220
Lelse221:
        movzx r13d, byte ptr [rsi+rdi+8]
Ldone220:
        cmp r13, 0
        jge Lelse222
        mov r13, 0
        jmp Ldone223
Lelse222:
        and r13, 16777215
Ldone223:
        cmp r12, r13
        jge Lelse225
        mov rdi, -1
        jmp Lexit198
Lelse225:
        sub rdi, 1
        jmp Ltop197
Lexit198:
        cmp rdi, 0
        jne Lelse227
        lea rax, LS228
        jmp Lret1
Lelse227:
        lea rax, LS229
        mov qword ptr [rsp+56], rax
        mov rsi, rbx
        mov qword ptr [rsp+48], 0
Ltop230:
        mov r10, 9
        add r10, 8
        xor ecx, ecx
        mov rdx, r10
        mov r8, 3000h
        mov r9, 4
        call VirtualAlloc
        mov r12, rax
        mov qword ptr [r12], 9
        mov r13, 0
        mov r14, 0
Ltop234:
        cmp r13, 9
        jge Lbuilt233
        mov r15, r14
        and r15, 16777215
        mov byte ptr [r12+r13+8], r15b
        add r13, 1
        mov rcx, 24
        shr r14, cl
        jmp Ltop234
Lbuilt233:
        mov r13, 8
Ltop240:
        cmp r13, 0
        jge Lelse242
        mov r13, 0
        jmp Lexit241
Lelse242:
        cmp r13, 0
        jge Lelse243
        mov r14, 0
        jmp Ldone244
Lelse243:
        mov r14, qword ptr [rsi]
        cmp r13, r14
        jl Lelse245
        mov r14, 0
        jmp Ldone244
Lelse245:
        mov r14, qword ptr [rsi+r13*8+8]
Ldone244:
        cmp r14, 0
        jge Lelse246
        mov r14, 0
        jmp Ldone247
Lelse246:
        and r14, 16777215
Ldone247:
        cmp r13, 0
        jge Lelse249
        mov r15, 0
        jmp Ldone250
Lelse249:
        mov r15, qword ptr [r12]
        cmp r13, r15
        jl Lelse251
        mov r15, 0
        jmp Ldone250
Lelse251:
        movzx r15d, byte ptr [r12+r13+8]
Ldone250:
        cmp r15, 0
        jge Lelse252
        mov r15, 0
        jmp Ldone253
Lelse252:
        and r15, 16777215
Ldone253:
        cmp r14, r15
        jle Lelse255
        mov r13, 1
        jmp Lexit241
Lelse255:
        cmp r13, 0
        jge Lelse256
        mov r14, 0
        jmp Ldone257
Lelse256:
        mov r14, qword ptr [rsi]
        cmp r13, r14
        jl Lelse258
        mov r14, 0
        jmp Ldone257
Lelse258:
        mov r14, qword ptr [rsi+r13*8+8]
Ldone257:
        cmp r14, 0
        jge Lelse259
        mov r14, 0
        jmp Ldone260
Lelse259:
        and r14, 16777215
Ldone260:
        cmp r13, 0
        jge Lelse262
        mov r15, 0
        jmp Ldone263
Lelse262:
        mov r15, qword ptr [r12]
        cmp r13, r15
        jl Lelse264
        mov r15, 0
        jmp Ldone263
Lelse264:
        movzx r15d, byte ptr [r12+r13+8]
Ldone263:
        cmp r15, 0
        jge Lelse265
        mov r15, 0
        jmp Ldone266
Lelse265:
        and r15, 16777215
Ldone266:
        cmp r14, r15
        jge Lelse268
        mov r13, -1
        jmp Lexit241
Lelse268:
        sub r13, 1
        jmp Ltop240
Lexit241:
        cmp r13, 0
        jne Lelse270
        mov rbx, qword ptr [rsp+56]
        jmp Lexit231
Lelse270:
        mov rax, qword ptr [rsp+48]
        cmp rax, 32
        jl Lelse271
        mov rbx, qword ptr [rsp+56]
        jmp Lexit231
Lelse271:
        mov r10, 9
        add r10, 1
        shl r10, 3
        xor ecx, ecx
        mov rdx, r10
        mov r8, 3000h
        mov r9, 4
        call VirtualAlloc
        mov r12, rax
        mov qword ptr [r12], 9
        mov r13, 8
        mov r14, 0
Ltop274:
        cmp r13, 0
        jl Lbuilt273
        imul r14, 16777216
        cmp r13, 0
        jge Lelse278
        mov r15, 0
        jmp Ldone279
Lelse278:
        mov r15, qword ptr [rsi]
        cmp r13, r15
        jl Lelse280
        mov r15, 0
        jmp Ldone279
Lelse280:
        mov r15, qword ptr [rsi+r13*8+8]
Ldone279:
        cmp r15, 0
        jge Lelse281
        mov r15, 0
        jmp Ldone282
Lelse281:
        and r15, 16777215
Ldone282:
        add r14, r15
        mov rax, r14
        cqo
        mov rcx, 100000000
        idiv rcx
        mov r15, rax
        mov qword ptr [r12+r13*8+8], r15
        sub r13, 1
        mov rax, r14
        cqo
        mov rcx, 100000000
        idiv rcx
        mov r15, rdx
        mov r14, r15
        jmp Ltop274
Lbuilt273:
        mov r13, 8
        mov r14, 0
Ltop288:
        cmp r13, 0
        jge Lelse290
        mov r13, r14
        jmp Lexit289
Lelse290:
        imul r14, 16777216
        cmp r13, 0
        jge Lelse292
        mov r15, 0
        jmp Ldone293
Lelse292:
        mov r15, qword ptr [rsi]
        cmp r13, r15
        jl Lelse294
        mov r15, 0
        jmp Ldone293
Lelse294:
        mov r15, qword ptr [rsi+r13*8+8]
Ldone293:
        sub r13, 1
        cmp r15, 0
        jge Lelse296
        mov r15, 0
        jmp Ldone297
Lelse296:
        and r15, 16777215
Ldone297:
        add r14, r15
        mov rax, r14
        cqo
        mov rcx, 100000000
        idiv rcx
        mov r15, rdx
        mov r14, r15
        jmp Ltop288
Lexit289:
        lea rax, LS229
        mov qword ptr [rsp+64], rax
        mov r14, r13
        mov r13, 0
Ltop301:
        cmp r13, 8
        jl Lelse303
        mov rbx, qword ptr [rsp+64]
        jmp Lexit302
Lelse303:
        mov r10, 9
        add r10, 8
        xor ecx, ecx
        mov rdx, r10
        mov r8, 3000h
        mov r9, 4
        call VirtualAlloc
        mov r15, rax
        mov qword ptr [r15], 9
        mov rdi, 0
        mov rbx, 0
Ltop306:
        cmp rdi, 9
        jl Lelse308
        mov rbx, r15
        jmp Lbuilt305
Lelse308:
        mov rsi, rbx
        and rsi, 16777215
        mov byte ptr [r15+rdi+8], sil
        add rdi, 1
        mov rcx, 24
        shr rbx, cl
        jmp Ltop306
Lbuilt305:
        mov rsi, 8
Ltop312:
        cmp rsi, 0
        jge Lelse314
        mov rsi, 0
        jmp Lexit313
Lelse314:
        cmp rsi, 0
        jge Lelse315
        mov rdi, 0
        jmp Ldone316
Lelse315:
        mov rdi, qword ptr [r12]
        cmp rsi, rdi
        jl Lelse317
        mov rdi, 0
        jmp Ldone316
Lelse317:
        mov rdi, qword ptr [r12+rsi*8+8]
Ldone316:
        cmp rdi, 0
        jge Lelse318
        mov rdi, 0
        jmp Ldone319
Lelse318:
        and rdi, 16777215
Ldone319:
        cmp rsi, 0
        jge Lelse321
        mov r15, 0
        jmp Ldone322
Lelse321:
        mov r15, qword ptr [rbx]
        cmp rsi, r15
        jl Lelse323
        mov r15, 0
        jmp Ldone322
Lelse323:
        movzx r15d, byte ptr [rbx+rsi+8]
Ldone322:
        cmp r15, 0
        jge Lelse324
        mov r15, 0
        jmp Ldone325
Lelse324:
        and r15, 16777215
Ldone325:
        cmp rdi, r15
        jle Lelse327
        mov rsi, 1
        jmp Lexit313
Lelse327:
        cmp rsi, 0
        jge Lelse328
        mov rdi, 0
        jmp Ldone329
Lelse328:
        mov rdi, qword ptr [r12]
        cmp rsi, rdi
        jl Lelse330
        mov rdi, 0
        jmp Ldone329
Lelse330:
        mov rdi, qword ptr [r12+rsi*8+8]
Ldone329:
        cmp rdi, 0
        jge Lelse331
        mov rdi, 0
        jmp Ldone332
Lelse331:
        and rdi, 16777215
Ldone332:
        cmp rsi, 0
        jge Lelse334
        mov r15, 0
        jmp Ldone335
Lelse334:
        mov r15, qword ptr [rbx]
        cmp rsi, r15
        jl Lelse336
        mov r15, 0
        jmp Ldone335
Lelse336:
        movzx r15d, byte ptr [rbx+rsi+8]
Ldone335:
        cmp r15, 0
        jge Lelse337
        mov r15, 0
        jmp Ldone338
Lelse337:
        and r15, 16777215
Ldone338:
        cmp rdi, r15
        jge Lelse340
        mov rsi, -1
        jmp Lexit313
Lelse340:
        sub rsi, 1
        jmp Ltop312
Lexit313:
        cmp rsi, 0
        jg Lelse342
        cmp r14, 0
        jne Lelse342
        cmp r13, 0
        jle Lelse342
        mov rbx, qword ptr [rsp+64]
        jmp Lexit302
Lelse342:
        mov rax, r14
        cqo
        mov rcx, 10
        idiv rcx
        mov rbx, rdx
        mov rsi, 48
        add rsi, rbx
        mov rax, rsi
        lea rcx, __sarena
        add rcx, qword ptr [__stop]
        mov r8, rcx
        cmp rax, 128
        jl Ls1350
        cmp rax, 2048
        jl Ls2350
        cmp rax, 65536
        jl Ls3350
        mov rdx, rax
        shr rdx, 18
        or dl, 0F0h
        mov byte ptr [rcx], dl
        mov rdx, rax
        shr rdx, 12
        and dl, 3Fh
        or dl, 80h
        mov byte ptr [rcx+1], dl
        mov rdx, rax
        shr rdx, 6
        and dl, 3Fh
        or dl, 80h
        mov byte ptr [rcx+2], dl
        mov rdx, rax
        and dl, 3Fh
        or dl, 80h
        mov byte ptr [rcx+3], dl
        add rcx, 4
        jmp Lse350
        Ls3350:
        mov rdx, rax
        shr rdx, 12
        or dl, 0E0h
        mov byte ptr [rcx], dl
        mov rdx, rax
        shr rdx, 6
        and dl, 3Fh
        or dl, 80h
        mov byte ptr [rcx+1], dl
        mov rdx, rax
        and dl, 3Fh
        or dl, 80h
        mov byte ptr [rcx+2], dl
        add rcx, 3
        jmp Lse350
        Ls2350:
        mov rdx, rax
        shr rdx, 6
        or dl, 0C0h
        mov byte ptr [rcx], dl
        mov rdx, rax
        and dl, 3Fh
        or dl, 80h
        mov byte ptr [rcx+1], dl
        add rcx, 2
        jmp Lse350
        Ls1350:
        mov byte ptr [rcx], al
        inc rcx
        Lse350:
        mov byte ptr [rcx], 0
        inc rcx
        lea rdx, __sarena
        sub rcx, rdx
        mov qword ptr [__stop], rcx
        mov rbx, r8
        mov r10, qword ptr [rsp+64]
        mov qword ptr [rsp+32], r10
        mov rcx, rbx
        lea rax, __sarena
        add rax, qword ptr [__stop]
        mov rdx, rax
        Lca351:
        mov r8b, byte ptr [rcx]
        test r8b, r8b
        je Lcae351
        mov byte ptr [rdx], r8b
        inc rcx
        inc rdx
        jmp Lca351
        Lcae351:
        mov rcx, qword ptr [rsp+32]
        Lcb351:
        mov r8b, byte ptr [rcx]
        test r8b, r8b
        je Lcbe351
        mov byte ptr [rdx], r8b
        inc rcx
        inc rdx
        jmp Lcb351
        Lcbe351:
        mov byte ptr [rdx], 0
        inc rdx
        lea rcx, __sarena
        sub rdx, rcx
        mov qword ptr [__stop], rdx
        mov rsi, rax
        add r13, 1
        mov rax, r14
        cqo
        mov rcx, 10
        idiv rcx
        mov rbx, rax
        mov qword ptr [rsp+64], rsi
        mov r14, rbx
        jmp Ltop301
Lexit302:
        mov r10, qword ptr [rsp+56]
        mov qword ptr [rsp+32], r10
        mov rcx, rbx
        lea rax, __sarena
        add rax, qword ptr [__stop]
        mov rdx, rax
        Lca354:
        mov r8b, byte ptr [rcx]
        test r8b, r8b
        je Lcae354
        mov byte ptr [rdx], r8b
        inc rcx
        inc rdx
        jmp Lca354
        Lcae354:
        mov rcx, qword ptr [rsp+32]
        Lcb354:
        mov r8b, byte ptr [rcx]
        test r8b, r8b
        je Lcbe354
        mov byte ptr [rdx], r8b
        inc rcx
        inc rdx
        jmp Lcb354
        Lcbe354:
        mov byte ptr [rdx], 0
        inc rdx
        lea rcx, __sarena
        sub rdx, rcx
        mov qword ptr [__stop], rdx
        mov rsi, rax
        mov r10, qword ptr [rsp+48]
        mov rbx, r10
        add rbx, 1
        mov qword ptr [rsp+56], rsi
        mov rsi, r12
        mov qword ptr [rsp+48], rbx
        jmp Ltop230
Lexit231:
        mov rax, rbx
Lret1:
        add rsp, 96
        pop r15
        pop r14
        pop r13
        pop r12
        pop rdi
        pop rsi
        pop rbx
        ret
gen_run endp


end
