// Code generated by oroboros. DO NOT EDIT.

export function genRun(n) {
	const m = (0 - (n + 1));
	return (1000000 + (((((Math.trunc(m / 2) + 0)) * 100) + (((m % 8) + 0))) + ((Math.trunc((n * 300000000) / 4) + 0))));
}

