// Code generated by oroboros. DO NOT EDIT.

public final class gauntlet_differential_cases_render.java {
	public static String genRun(int v0) {
		final java.math.BigInteger v10 = (java.math.BigInteger.valueOf(1));
		final java.math.BigInteger v12 = (java.math.BigInteger.valueOf(2));
		java.math.BigInteger v14 = v10;
		java.math.BigInteger v15 = v12;
		for (;;) {
			final int v17 = (25 + v0);
			final java.math.BigInteger v18 = (java.math.BigInteger.valueOf(v17));
			final boolean v19 = (v15.compareTo(v18) > 0);
			if (v19) {
				break;
			}
			final java.math.BigInteger v20 = (v14.multiply(v15));
			final java.math.BigInteger v22 = (((java.util.function.BiFunction<java.math.BigInteger,Long,java.math.BigInteger>)((oro$z, oro$k) -> { if (oro$z.signum() < 0 || oro$z.bitLength() > oro$k) throw new ArithmeticException("bignum overflow: the declared range is too small"); return oro$z; })).apply(v20, (long)(201)));
			final java.math.BigInteger v24 = (java.math.BigInteger.valueOf(1));
			final java.math.BigInteger v25 = (v15.add(v24));
			final java.math.BigInteger v27 = (((java.util.function.BiFunction<java.math.BigInteger,Long,java.math.BigInteger>)((oro$z, oro$k) -> { if (oro$z.signum() < 0 || oro$z.bitLength() > oro$k) throw new ArithmeticException("bignum overflow: the declared range is too small"); return oro$z; })).apply(v25, (long)(201)));
			v14 = v22;
			v15 = v27;
			continue;
		}
		final java.math.BigInteger v29 = (java.math.BigInteger.valueOf(0));
		final boolean v30 = (v14.compareTo(v29) == 0);
		if (v30) {
			return "0";
		}
		String v35 = "";
		java.math.BigInteger v36 = v14;
		int v37 = 0;
		for (;; v37 = (v37 + 1)) {
			final java.math.BigInteger v39 = (java.math.BigInteger.valueOf(0));
			final boolean v40 = (v36.compareTo(v39) == 0);
			if (v40) {
				break;
			}
			final boolean v42 = (v37 >= 32);
			if (v42) {
				break;
			}
			final java.math.BigInteger v46 = (java.math.BigInteger.valueOf(100000000));
			final java.math.BigInteger v47 = (v36.divide(v46));
			final java.math.BigInteger v49 = (((java.util.function.BiFunction<java.math.BigInteger,Long,java.math.BigInteger>)((oro$z, oro$k) -> { if (oro$z.signum() < 0 || oro$z.bitLength() > oro$k) throw new ArithmeticException("bignum overflow: the declared range is too small"); return oro$z; })).apply(v47, (long)(201)));
			final long v53 = (v36.remainder(java.math.BigInteger.valueOf(100000000)).longValue());
			String v55 = "";
			int v56 = 0;
			long v57 = v53;
			for (;; v56 = (v56 + 1)) {
				final boolean v59 = (v56 >= 8);
				if (v59) {
					break;
				}
				final java.math.BigInteger v65 = (java.math.BigInteger.valueOf(0));
				final boolean v66 = (v49.compareTo(v65) > 0);
				boolean v67 = false;
				if (v66) {
					v67 = false;
				} else {
					v67 = true;
				}
				final boolean v70 = (v67 && ((v57 == 0) && (v56 > 0)));
				if (v70) {
					break;
				}
				final int v83 = (int) ((v57 % 10));
				final int v84 = (48 + v83);
				final String v85 = (new String(Character.toChars((int) v84)));
				final String v86 = (v85.concat(v55));
				final long v90 = (v57 / 10);
				v55 = v86;
				v57 = v90;
				continue;
			}
			final String v91 = (v55.concat(v35));
			v35 = v91;
			v36 = v49;
			continue;
		}
		return v35;
	}

}
