// Code generated by oroboros. DO NOT EDIT.

package gauntlet

func GenRun(v0 int) int {
	v3 := make([]uint32, 3)
	var v2 []uint32
	v7 := v3
	var v8 int = 0
	var v9 int = 999999999999999
	for ; ; v8 = (v8 + 1) {
		v11 := (v8 >= 3)
		if v11 {
			break
		}
		v15 := (v9 & 16777215)
		v7[v8] = uint32(v15)
		v20 := (v9 >> 24)
		v9 = v20
		continue
	}
	v2 = v7
	v23 := make([]uint32, 3)
	var v22 []uint32
	v27 := v23
	var v28 int = 0
	var v29 int = 14000000
	for ; ; v28 = (v28 + 1) {
		v31 := (v28 >= 3)
		if v31 {
			break
		}
		v35 := (v29 & 16777215)
		v27[v28] = uint32(v35)
		v40 := (v29 >> 24)
		v29 = v40
		continue
	}
	v22 = v27
	v43 := make([]int, 3)
	var v42 []int
	v47 := v43
	var v48 int = 0
	var v49 int = 0
	for ; ; v48 = (v48 + 1) {
		v51 := (v48 >= 3)
		if v51 {
			break
		}
		v55 := (v48 < 0)
		var v56 int
		if v55 {
			v56 = 0
		} else {
			v60 := len(v2)
			v61 := (v48 >= v60)
			if v61 {
				v56 = 0
			} else {
				v67 := int(v2[v48])
				v56 = v67
			}
		}
		v69 := (v48 < 0)
		var v70 int
		if v69 {
			v70 = 0
		} else {
			v74 := len(v22)
			v75 := (v48 >= v74)
			if v75 {
				v70 = 0
			} else {
				v81 := int(v22[v48])
				v70 = v81
			}
		}
		v82 := (v56 - v70)
		v83 := (v82 - v49)
		v85 := (v83 < 0)
		var v86 int
		if v85 {
			v89 := (v83 + 16777216)
			v86 = v89
		} else {
			v86 = v83
		}
		v47[v48] = v86
		v95 := (v83 < 0)
		var v96 int
		if v95 {
			v96 = 1
		} else {
			v96 = 0
		}
		v49 = v96
		continue
	}
	v42 = v47
	v103 := make([]int, 3)
	var v102 []int
	v107 := v103
	var v108 int = 2
	var v109 int = 0
	for {
		v111 := (v108 < 0)
		if v111 {
			break
		}
		v115 := (v109 * 16777216)
		v117 := (v108 < 0)
		var v118 int
		if v117 {
			v118 = 0
		} else {
			v122 := len(v42)
			v123 := (v108 >= v122)
			if v123 {
				v118 = 0
			} else {
				v129 := v42[v108]
				v118 = v129
			}
		}
		v130 := (v115 + v118)
		v132 := (v130 / 7)
		v107[v108] = v132
		v135 := (v108 - 1)
		v137 := (v130 % 7)
		v108, v109 = v135, v137
		continue
	}
	v102 = v107
	v139 := (v0 < 0)
	var v140 int
	if v139 {
		v140 = 0
	} else {
		v144 := len(v102)
		v145 := (v0 >= v144)
		if v145 {
			v140 = 0
		} else {
			v151 := v102[v0]
			v140 = v151
		}
	}
	v153 := (func(a, b int) int { t := a + b; if (t > a) != (b > 0) { panic("int overflow") }; return t }(v0, 1))
	v155 := (v153 < 0)
	var v156 int
	if v155 {
		v156 = 0
	} else {
		v160 := len(v102)
		v161 := (v153 >= v160)
		if v161 {
			v156 = 0
		} else {
			v167 := v102[v153]
			v156 = v167
		}
	}
	v169 := (v156 * 100000000)
	v170 := (v140 + v169)
	return v170
}

