// Code generated by oroboros. DO NOT EDIT.

package gauntlet

import "math/bits"
import "strconv"

func GenAdd(ah uint64, al uint64, bh uint64, bl uint64) (uint64, uint64, int) {
	l, ch1 := func(x, y, c uint64) (uint64, int) { s, o := bits.Add64(x, y, c); return s, int(o) }(uint64(al), uint64(bl), uint64((uint64(0))))
	c := int(ch1)
	h, c2h2 := func(x, y, c uint64) (uint64, int) { s, o := bits.Add64(x, y, c); return s, int(o) }(uint64(ah), uint64(bh), uint64((uint64(c))))
	c2 := int(c2h2)
	return h, l, c2
}

func GenDecimal(h int, l int) string {
	var h2 int = h
	var l2 int = l
	s := ""
	var r1 string
	for ; ; h2 = (h2 / 1000000000000000000) {
		if ((h2 == 0) && (l2 < 1000000000000000000)) {
			r1 = ((strconv.FormatUint(uint64((uint64(l2))), 10)) + s)
			break
		}
		q, _ := bits.Div64(uint64((uint64((h2 % 1000000000000000000)))), uint64((uint64(l2))), uint64((uint64(1000000000000000000))))
		var i int = 0
		v := (bits.Rem64(uint64((uint64(h2))), uint64((uint64(l2))), uint64((uint64(1000000000000000000)))))
		s2 := ""
		for ; ; i = (i + 1) {
			if (i >= 18) {
				break
			}
			v, s2 = ((v / (uint64(10)))), ((string(rune((48 + (int(((v % (uint64(10)))))))))) + s2)
			continue
		}
		l2, s = (int(q)), (s2 + s)
		continue
	}
	return r1
}

func GenDivw(ah uint64, al uint64, y uint64) (uint64, uint64, uint64) {
	qh, _ := bits.Div64(uint64((uint64(0))), uint64(ah), uint64(y))
	ql, r := bits.Div64(uint64((bits.Rem64(uint64((uint64(0))), uint64(ah), uint64(y)))), uint64(al), uint64(y))
	return qh, ql, r
}

func GenMulw(ah uint64, al uint64, w uint64) (uint64, uint64, int) {
	p1h, p1l := bits.Mul64(uint64(al), uint64(w))
	p2h, p2l := bits.Mul64(uint64(ah), uint64(w))
	h, ch1 := func(x, y, c uint64) (uint64, int) { s, o := bits.Add64(x, y, c); return s, int(o) }(uint64(p2l), uint64(p1h), uint64((uint64(0))))
	c := int(ch1)
	var t2 int
	if (((p2h == (uint64(0)))) && (c == 0)) {
		t2 = 0
	} else {
		t2 = 1
	}
	return h, p1l, t2
}

