; Code generated by oroboros. DO NOT EDIT.

option casemap:none

extern GetStdHandle: proc
extern WriteFile: proc

.data
__written qword 0
__buf     db 256 dup(0)
LS8 db 00Ah,0
LS8_len equ 1
LS13 db 030h,0
LS13_len equ 1
LS20 db 02Dh,039h,032h,032h,033h,033h,037h,032h,030h,033h,036h,038h,035h,034h,037h,037h,035h,038h,030h,038h,0
LS20_len equ 20

.code
gen_print_int proc
        push rbx
        push rsi
        push rdi
        push r12
        push r13
        push r14
        push r15
        sub rsp, 48
        mov rbx, rcx
        cmp rbx, 0
        jne Lelse11
        mov rcx, -11
        call GetStdHandle
        mov rbx, rax
        lea r10, LS13
        mov rax, r10
        Lstr14:
        cmp byte ptr [rax], 0
        je Lstrend14
        inc rax
        jmp Lstr14
        Lstrend14:
        sub rax, r10
        mov rsi, rax
        lea r10, LS13
        mov rcx, rbx
        mov rdx, r10
        mov r8, rsi
        lea r9, __written
        mov qword ptr [rsp+32], 0
        call WriteFile
        mov rcx, -11
        call GetStdHandle
        mov rbx, rax
        lea r10, LS8
        mov rcx, rbx
        mov rdx, r10
        mov r8, 1
        lea r9, __written
        mov qword ptr [rsp+32], 0
        call WriteFile
        mov rax, rbx
        jmp Lret10
Lelse11:
        mov r11, -9223372036854775807
        cmp rbx, r11
        jge Lelse18
        mov rcx, -11
        call GetStdHandle
        mov rbx, rax
        lea r10, LS20
        mov rax, r10
        Lstr21:
        cmp byte ptr [rax], 0
        je Lstrend21
        inc rax
        jmp Lstr21
        Lstrend21:
        sub rax, r10
        mov rsi, rax
        lea r10, LS20
        mov rcx, rbx
        mov rdx, r10
        mov r8, rsi
        lea r9, __written
        mov qword ptr [rsp+32], 0
        call WriteFile
        mov rcx, -11
        call GetStdHandle
        mov rbx, rax
        lea r10, LS8
        mov rcx, rbx
        mov rdx, r10
        mov r8, 1
        lea r9, __written
        mov qword ptr [rsp+32], 0
        call WriteFile
        mov rax, rbx
        jmp Lret10
Lelse18:
        lea rsi, __buf
        mov byte ptr [rsi+24], 10
        cmp rbx, 0
        jge Lelse27
        mov rdi, 0
        sub rdi, rbx
        jmp Ldone28
Lelse27:
        mov rdi, rbx
Ldone28:
        mov r12, 24
Ltop30:
        cmp rdi, 0
        jle Lelse32
        mov r13, r12
        sub r13, 1
        mov rax, rdi
        cqo
        mov rcx, 10
        idiv rcx
        mov r14, rdx
        mov r15, 48
        add r15, r14
        mov byte ptr [rsi+r13], r15b
        mov rax, rdi
        cqo
        mov rcx, 10
        idiv rcx
        mov r13, rax
        sub r12, 1
        mov rdi, r13
        jmp Ltop30
Lelse32:
        mov rdi, r12
        cmp rbx, 0
        jge Lelse39
        mov rbx, rdi
        sub rbx, 1
        mov byte ptr [rsi+rbx], 45
        sub rdi, 1
        mov rbx, rdi
        jmp Ldone40
Lelse39:
        mov rbx, rdi
Ldone40:
        mov rcx, -11
        call GetStdHandle
        mov rdi, rax
        lea r12, [rsi+rbx]
        mov rsi, 24
        sub rsi, rbx
        add rsi, 1
        mov rcx, rdi
        mov rdx, r12
        mov r8, rsi
        lea r9, __written
        mov qword ptr [rsp+32], 0
        call WriteFile
        mov rax, rdi
Lret10:
        add rsp, 48
        pop r15
        pop r14
        pop r13
        pop r12
        pop rdi
        pop rsi
        pop rbx
        ret
gen_print_int endp

gen_print_str proc
        push rbx
        push rsi
        push rdi
        sub rsp, 48
        mov rbx, rcx
        mov rcx, -11
        call GetStdHandle
        mov rsi, rax
        mov rdi, qword ptr [rbx]
        mov rcx, rsi
        mov rdx, rbx
        mov r8, rdi
        lea r9, __written
        mov qword ptr [rsp+32], 0
        call WriteFile
        mov rcx, -11
        call GetStdHandle
        mov rbx, rax
        lea r10, LS8
        mov rcx, rbx
        mov rdx, r10
        mov r8, 1
        lea r9, __written
        mov qword ptr [rsp+32], 0
        call WriteFile
        mov rax, rbx
Lret4:
        add rsp, 48
        pop rdi
        pop rsi
        pop rbx
        ret
gen_print_str endp

gen_write_bytes proc
        push rbx
        push rsi
        push rdi
        sub rsp, 48
        mov rbx, rcx
        mov rsi, rdx
        mov rcx, -11
        call GetStdHandle
        mov rdi, rax
        mov rcx, rdi
        mov rdx, rbx
        mov r8, rsi
        lea r9, __written
        mov qword ptr [rsp+32], 0
        call WriteFile
        mov rax, rdi
Lret1:
        add rsp, 48
        pop rdi
        pop rsi
        pop rbx
        ret
gen_write_bytes endp


end
