// Code generated by oroboros. DO NOT EDIT.

export function genFactLimbs(n) {
	const b = new Array(55).fill(0);
	let b2 = b;
	let i = 0;
	let r = 1;
	for (;; i = (i + 1), r = (r >> 24)) {
		if ((i >= 55)) {
			break;
		}
		b2[i] = (r & 16777215);
		continue;
	}
	let acc = b2;
	let i2 = 2;
	let sp1 = new Array(55).fill(0);
	for (;; i2 = (i2 + 1)) {
		if ((i2 > n)) {
			return acc;
		}
		sp1.fill(0);
		const o = sp1;
		let o3 = o;
		let i22 = 0;
		let c = 0;
		for (;; i22 = (i22 + 1)) {
			if ((i22 >= 55)) {
				const i3 = 54;
				const v = ((i3 < 0) ? 0 : ((i3 >= o3.length) ? 0 : o3[i3]));
				if ((((function(oroC){ if (oroC !== 0) throw new Error("bignum overflow: the declared range is too small"); return 0; })((c + ((((v < 0) ? 0 : (((v % 16777216) + 0))) < 32) ? 0 : 1)))) === 0)) {
					break;
				}
				break;
			}
			const v2 = ((i22 < 0) ? 0 : ((i22 >= acc.length) ? 0 : acc[i22]));
			const t145 = ((((v2 < 0) ? 0 : (v2 & 16777215)) * i2) + c);
			o3[i22] = (((t145 % 16777216) + 0));
			c = ((Math.trunc(t145 / 16777216) + 0));
			continue;
		}
		const sw2 = acc;
		acc = o3;
		sp1 = sw2;
		continue;
	}
}

