// Code generated by oroboros. DO NOT EDIT.

export function genPower(b, e) {
	let acc = (BigInt(1));
	let x = (BigInt(b));
	let k = e;
	for (;; x = ((x * x)), k = ((Math.trunc(k / 2) + 0))) {
		if ((k === 0)) {
			return acc;
		}
		if (((((k % 2) + 0)) === 1)) {
			acc = ((acc * x));
			continue;
		}
		continue;
	}
}

