// Code generated by oroboros. DO NOT EDIT.

export function nativeCentroid(xs, ys) {
	let ax = 0;
	let ay = 0;
	let i = 0;
	for (;;) {
		if ((i >= (xs.length))) {
			return (ax + ay);
		}
		const u1 = (ax + (xs[i]));
		const u2 = (ay + (ys[i]));
		const u3 = (i + 1);
		ax = u1;
		ay = u2;
		i = u3;
		continue;
	}
}

