// Code generated by oroboros. DO NOT EDIT.

export function genFindFirst(a, k) {
	let i = 0;
	let r1;
	for (;;) {
		if ((i >= (a.length))) {
			r1 = -1;
			break;
		}
		if (((a[i]) > k)) {
			r1 = i;
			break;
		}
		i = (i + 1);
		continue;
	}
	return r1;
}

