// Code generated by oroboros. DO NOT EDIT.

export function genReport(label, xs) {
	console.log(label);
	const v1 = (xs.length);
	console.log(v1);
	let acc = 0;
	const n2 = (xs.length);
	for (let i = 0; i < n2; i++) {
		acc = (acc + ((xs[i]) * (xs[i])));
	}
	console.log(acc);
	return acc;
}

