// Code generated by oroboros. DO NOT EDIT.

export function genStencil(a) {
	let acc = 0;
	const n1 = ((a.length) - 2);
	for (let j = 0; j < n1; j++) {
		acc = (acc + (((a[j]) + (a[(j + 1)])) + (a[(j + 2)])));
	}
	return acc;
}

