// Code generated by oroboros. DO NOT EDIT.

export function genWordcount(text) {
	const ws = (text.split(" "));
	let acc = (Object.create(null));
	const n1 = (ws.length);
	for (let i = 0; i < n1; i++) {
		acc[(ws[i])] = (acc[(ws[i])] ?? 0) + 1;
	}
	return acc;
}

