// Code generated by oroboros. DO NOT EDIT.

export function genSmooth(a) {
	const n1 = ((a.length) - 2);
	const v2 = new Array(n1);
	for (let i = 0; i < n1; i++) {
		v2[i] = ((((a[i]) + (a[(i + 1)])) + (a[(i + 2)])) / 3);
	}
	return v2;
}

