// Code generated by oroboros. DO NOT EDIT.

export function genWordCount(text) {
	let acc = (Object.create(null));
	const n1 = ((text.split(" ")).length);
	for (let i = 0; i < n1; i++) {
		acc[((text.split(" "))[i])] = (acc[((text.split(" "))[i])] ?? 0) + 1;
	}
	return acc;
}

