// Code generated by oroboros. DO NOT EDIT.

export function genFilter(a) {
	let acc = 0;
	const n1 = (a.length);
	for (let i = 0; i < n1; i++) {
		const x = (a[i]);
		acc = ((x > 0) ? (acc + x) : acc);
	}
	return acc;
}

