// Code generated by oroboros. DO NOT EDIT.

package gauntlet

import "fmt"

func GenMain() int {
	var i int = 0
	var r1 int
	for ; ; i = (i + 1) {
		if (i >= 2) {
			r1 = 0
			break
		}
		var t2 int
		if ((i != 0) && ((10 / i) < 20)) {
			t2 = 111
		} else {
			t2 = 222
		}
		fmt.Println(t2)
		continue
	}
	return r1
}

