// Code generated by oroboros. DO NOT EDIT.

export function genMain() {
	const av = (process.argv.slice(1));
	let t64;
	if ((av.length < 2)) {
		console.log("usage: freq FILE");
		t64 = "usage: freq FILE";
	} else {
		let src2, err2;
		try { src2 = fs.readFileSync(av[1]); err2 = null; } catch (e) { src2 = null; err2 = e; }
		let t96;
		if ((err2 === null)) {
			let t112;
			if ((src2.length >= 65536)) {
				console.log("freq: file is larger than this tool accepts");
				t112 = "freq: file is larger than this tool accepts";
			} else {
				let n22 = 0;
				let i400 = 0;
				for (;;) {
					if ((i400 >= src2.length)) {
						break;
					}
					if ((n22 >= 32768)) {
						break;
					}
					const c148 = src2[i400];
					if ((((c148 >= 65) && (c148 <= 90)) || ((c148 >= 97) && (c148 <= 122)))) {
						let j29 = (i400 + 1);
						for (;; j29 = (j29 + 1)) {
							if ((j29 < 0)) {
								break;
							}
							if ((j29 >= src2.length)) {
								break;
							}
							const c149 = src2[j29];
							if ((((c149 >= 65) && (c149 <= 90)) || ((c149 >= 97) && (c149 <= 122)))) {
								continue;
							}
							break;
						}
						n22 = (n22 + 1);
						i400 = j29;
						continue;
					}
					i400 = (i400 + 1);
					continue;
				}
				const nw8 = n22;
				const sp22 = new Array((2 * nw8)).fill(0);
				let sp23 = sp22;
				let i401 = 0;
				let w50 = 0;
				for (;;) {
					if ((i401 >= src2.length)) {
						break;
					}
					if ((w50 >= nw8)) {
						break;
					}
					const c150 = src2[i401];
					if ((((c150 >= 65) && (c150 <= 90)) || ((c150 >= 97) && (c150 <= 122)))) {
						let j30 = (i401 + 1);
						for (;; j30 = (j30 + 1)) {
							if ((j30 < 0)) {
								break;
							}
							if ((j30 >= src2.length)) {
								break;
							}
							const c151 = src2[j30];
							if ((((c151 >= 65) && (c151 <= 90)) || ((c151 >= 97) && (c151 <= 122)))) {
								continue;
							}
							break;
						}
						const ni8 = j30;
						sp23[(2 * w50)] = i401;
						sp23[((2 * w50) + 1)] = ni8;
						i401 = ni8;
						w50 = (w50 + 1);
						continue;
					}
					i401 = (i401 + 1);
					continue;
				}
				const sp24 = sp23;
				const a43 = new Array(nw8).fill(0);
				const b85 = new Array(nw8).fill(0);
				let a44 = a43;
				let k85 = 0;
				for (;; k85 = (k85 + 1)) {
					if ((k85 >= nw8)) {
						break;
					}
					a44[((k85 < 0) ? 0 : ((k85 >= nw8) ? 0 : k85))] = k85;
					continue;
				}
				let a45 = a44;
				let b86 = b85;
				let w51 = 1;
				for (;; w51 = (2 * w51)) {
					if ((w51 >= nw8)) {
						break;
					}
					if ((w51 >= 32768)) {
						break;
					}
					let b87 = b86;
					let lo15 = 0;
					for (;;) {
						if ((lo15 >= nw8)) {
							break;
						}
						const b88 = (lo15 + w51);
						const mid15 = ((nw8 < b88) ? nw8 : b88);
						const b89 = (lo15 + (2 * w51));
						const hi15 = ((nw8 < b89) ? nw8 : b89);
						let b90 = b87;
						let i402 = lo15;
						let j31 = mid15;
						let k86 = lo15;
						for (;;) {
							if ((k86 >= hi15)) {
								break;
							}
							if ((i402 >= mid15)) {
								b90[((k86 < 0) ? 0 : ((k86 >= nw8) ? 0 : k86))] = a45[((j31 < 0) ? 0 : ((j31 >= nw8) ? 0 : j31))];
								j31 = (j31 + 1);
								k86 = (k86 + 1);
								continue;
							}
							if ((j31 >= hi15)) {
								b90[((k86 < 0) ? 0 : ((k86 >= nw8) ? 0 : k86))] = a45[((i402 < 0) ? 0 : ((i402 >= nw8) ? 0 : i402))];
								i402 = (i402 + 1);
								k86 = (k86 + 1);
								continue;
							}
							const i403 = a45[((j31 < 0) ? 0 : ((j31 >= nw8) ? 0 : j31))];
							const u79 = ((i403 < 0) ? 0 : ((i403 >= nw8) ? 0 : i403));
							const i404 = a45[((i402 < 0) ? 0 : ((i402 >= nw8) ? 0 : i402))];
							const v30 = ((i404 < 0) ? 0 : ((i404 >= nw8) ? 0 : i404));
							let k87 = 0;
							let r113;
							for (;; k87 = (k87 + 1)) {
								const d176 = (sp24[((2 * u79) + 1)] - sp24[(2 * u79)]);
								if ((k87 >= ((d176 < 0) ? 0 : ((d176 >= 65536) ? 0 : d176)))) {
									const d177 = (sp24[((2 * v30) + 1)] - sp24[(2 * v30)]);
									if ((k87 >= ((d177 < 0) ? 0 : ((d177 >= 65536) ? 0 : d177)))) {
										r113 = 0;
										break;
									}
									r113 = -1;
									break;
								}
								const d178 = (sp24[((2 * v30) + 1)] - sp24[(2 * v30)]);
								if ((k87 >= ((d178 < 0) ? 0 : ((d178 >= 65536) ? 0 : d178)))) {
									r113 = 1;
									break;
								}
								const i405 = (sp24[(2 * u79)] + k87);
								const c152 = src2[((i405 < 0) ? 0 : ((i405 >= src2.length) ? 0 : i405))];
								const i406 = (sp24[(2 * v30)] + k87);
								const c153 = src2[((i406 < 0) ? 0 : ((i406 >= src2.length) ? 0 : i406))];
								if (((((c152 >= 65) && (c152 <= 90)) ? (c152 + 32) : c152) === (((c153 >= 65) && (c153 <= 90)) ? (c153 + 32) : c153))) {
									continue;
								}
								const i407 = (sp24[(2 * u79)] + k87);
								const c154 = src2[((i407 < 0) ? 0 : ((i407 >= src2.length) ? 0 : i407))];
								const i408 = (sp24[(2 * v30)] + k87);
								const c155 = src2[((i408 < 0) ? 0 : ((i408 >= src2.length) ? 0 : i408))];
								if (((((c154 >= 65) && (c154 <= 90)) ? (c154 + 32) : c154) < (((c155 >= 65) && (c155 <= 90)) ? (c155 + 32) : c155))) {
									r113 = -1;
									break;
								}
								r113 = 1;
								break;
							}
							if ((((0 <= u79) && ((u79 < nw8) && ((0 <= v30) && (v30 < nw8)))) && (r113 < 0))) {
								b90[((k86 < 0) ? 0 : ((k86 >= nw8) ? 0 : k86))] = a45[((j31 < 0) ? 0 : ((j31 >= nw8) ? 0 : j31))];
								j31 = (j31 + 1);
								k86 = (k86 + 1);
								continue;
							}
							b90[((k86 < 0) ? 0 : ((k86 >= nw8) ? 0 : k86))] = a45[((i402 < 0) ? 0 : ((i402 >= nw8) ? 0 : i402))];
							i402 = (i402 + 1);
							k86 = (k86 + 1);
							continue;
						}
						const u114 = b90;
						const u115 = hi15;
						b87 = u114;
						lo15 = u115;
						continue;
					}
					const u116 = b87;
					const u117 = a45;
					a45 = u116;
					b86 = u117;
					continue;
				}
				const ord9 = a45;
				let n23 = 0;
				let k88 = 0;
				for (;;) {
					if ((k88 >= nw8)) {
						break;
					}
					if ((n23 >= 32768)) {
						break;
					}
					const i409 = ord9[((k88 < 0) ? 0 : ((k88 >= nw8) ? 0 : k88))];
					const u80 = ((i409 < 0) ? 0 : ((i409 >= nw8) ? 0 : i409));
					const i410 = (k88 - 1);
					const i411 = ord9[((i410 < 0) ? 0 : ((i410 >= nw8) ? 0 : i410))];
					const v32 = ((i411 < 0) ? 0 : ((i411 >= nw8) ? 0 : i411));
					let k89 = 0;
					let r118;
					for (;; k89 = (k89 + 1)) {
						const d179 = (sp24[((2 * u80) + 1)] - sp24[(2 * u80)]);
						if ((k89 >= ((d179 < 0) ? 0 : ((d179 >= 65536) ? 0 : d179)))) {
							const d180 = (sp24[((2 * v32) + 1)] - sp24[(2 * v32)]);
							if ((k89 >= ((d180 < 0) ? 0 : ((d180 >= 65536) ? 0 : d180)))) {
								r118 = 0;
								break;
							}
							r118 = -1;
							break;
						}
						const d181 = (sp24[((2 * v32) + 1)] - sp24[(2 * v32)]);
						if ((k89 >= ((d181 < 0) ? 0 : ((d181 >= 65536) ? 0 : d181)))) {
							r118 = 1;
							break;
						}
						const i412 = (sp24[(2 * u80)] + k89);
						const c156 = src2[((i412 < 0) ? 0 : ((i412 >= src2.length) ? 0 : i412))];
						const i413 = (sp24[(2 * v32)] + k89);
						const c157 = src2[((i413 < 0) ? 0 : ((i413 >= src2.length) ? 0 : i413))];
						if (((((c156 >= 65) && (c156 <= 90)) ? (c156 + 32) : c156) === (((c157 >= 65) && (c157 <= 90)) ? (c157 + 32) : c157))) {
							continue;
						}
						const i414 = (sp24[(2 * u80)] + k89);
						const c158 = src2[((i414 < 0) ? 0 : ((i414 >= src2.length) ? 0 : i414))];
						const i415 = (sp24[(2 * v32)] + k89);
						const c159 = src2[((i415 < 0) ? 0 : ((i415 >= src2.length) ? 0 : i415))];
						if (((((c158 >= 65) && (c158 <= 90)) ? (c158 + 32) : c158) < (((c159 >= 65) && (c159 <= 90)) ? (c159 + 32) : c159))) {
							r118 = -1;
							break;
						}
						r118 = 1;
						break;
					}
					if (((k88 === 0) || (!(r118 === 0)))) {
						n23 = (n23 + 1);
						k88 = (k88 + 1);
						continue;
					}
					k88 = (k88 + 1);
					continue;
				}
				const nd8 = n23;
				const dt22 = new Array((2 * nd8)).fill(0);
				let dt23 = dt22;
				let k90 = 0;
				let d182 = 0;
				for (;;) {
					if ((k90 >= nw8)) {
						break;
					}
					if ((nd8 < 1)) {
						break;
					}
					const i416 = ord9[((k90 < 0) ? 0 : ((k90 >= nw8) ? 0 : k90))];
					const u81 = ((i416 < 0) ? 0 : ((i416 >= nw8) ? 0 : i416));
					const i417 = (k90 - 1);
					const i418 = ord9[((i417 < 0) ? 0 : ((i417 >= nw8) ? 0 : i417))];
					const v33 = ((i418 < 0) ? 0 : ((i418 >= nw8) ? 0 : i418));
					let k91 = 0;
					let r119;
					for (;; k91 = (k91 + 1)) {
						const d183 = (sp24[((2 * u81) + 1)] - sp24[(2 * u81)]);
						if ((k91 >= ((d183 < 0) ? 0 : ((d183 >= 65536) ? 0 : d183)))) {
							const d184 = (sp24[((2 * v33) + 1)] - sp24[(2 * v33)]);
							if ((k91 >= ((d184 < 0) ? 0 : ((d184 >= 65536) ? 0 : d184)))) {
								r119 = 0;
								break;
							}
							r119 = -1;
							break;
						}
						const d185 = (sp24[((2 * v33) + 1)] - sp24[(2 * v33)]);
						if ((k91 >= ((d185 < 0) ? 0 : ((d185 >= 65536) ? 0 : d185)))) {
							r119 = 1;
							break;
						}
						const i419 = (sp24[(2 * u81)] + k91);
						const c160 = src2[((i419 < 0) ? 0 : ((i419 >= src2.length) ? 0 : i419))];
						const i420 = (sp24[(2 * v33)] + k91);
						const c161 = src2[((i420 < 0) ? 0 : ((i420 >= src2.length) ? 0 : i420))];
						if (((((c160 >= 65) && (c160 <= 90)) ? (c160 + 32) : c160) === (((c161 >= 65) && (c161 <= 90)) ? (c161 + 32) : c161))) {
							continue;
						}
						const i421 = (sp24[(2 * u81)] + k91);
						const c162 = src2[((i421 < 0) ? 0 : ((i421 >= src2.length) ? 0 : i421))];
						const i422 = (sp24[(2 * v33)] + k91);
						const c163 = src2[((i422 < 0) ? 0 : ((i422 >= src2.length) ? 0 : i422))];
						if (((((c162 >= 65) && (c162 <= 90)) ? (c162 + 32) : c162) < (((c163 >= 65) && (c163 <= 90)) ? (c163 + 32) : c163))) {
							r119 = -1;
							break;
						}
						r119 = 1;
						break;
					}
					if ((((k90 === 0) || (!(r119 === 0))) && (d182 >= nd8))) {
						break;
					}
					const i423 = ord9[((k90 < 0) ? 0 : ((k90 >= nw8) ? 0 : k90))];
					const u86 = ((i423 < 0) ? 0 : ((i423 >= nw8) ? 0 : i423));
					const i424 = (k90 - 1);
					const i425 = ord9[((i424 < 0) ? 0 : ((i424 >= nw8) ? 0 : i424))];
					const v34 = ((i425 < 0) ? 0 : ((i425 >= nw8) ? 0 : i425));
					let k92 = 0;
					let r120;
					for (;; k92 = (k92 + 1)) {
						const d186 = (sp24[((2 * u86) + 1)] - sp24[(2 * u86)]);
						if ((k92 >= ((d186 < 0) ? 0 : ((d186 >= 65536) ? 0 : d186)))) {
							const d187 = (sp24[((2 * v34) + 1)] - sp24[(2 * v34)]);
							if ((k92 >= ((d187 < 0) ? 0 : ((d187 >= 65536) ? 0 : d187)))) {
								r120 = 0;
								break;
							}
							r120 = -1;
							break;
						}
						const d188 = (sp24[((2 * v34) + 1)] - sp24[(2 * v34)]);
						if ((k92 >= ((d188 < 0) ? 0 : ((d188 >= 65536) ? 0 : d188)))) {
							r120 = 1;
							break;
						}
						const i426 = (sp24[(2 * u86)] + k92);
						const c164 = src2[((i426 < 0) ? 0 : ((i426 >= src2.length) ? 0 : i426))];
						const i427 = (sp24[(2 * v34)] + k92);
						const c165 = src2[((i427 < 0) ? 0 : ((i427 >= src2.length) ? 0 : i427))];
						if (((((c164 >= 65) && (c164 <= 90)) ? (c164 + 32) : c164) === (((c165 >= 65) && (c165 <= 90)) ? (c165 + 32) : c165))) {
							continue;
						}
						const i428 = (sp24[(2 * u86)] + k92);
						const c166 = src2[((i428 < 0) ? 0 : ((i428 >= src2.length) ? 0 : i428))];
						const i429 = (sp24[(2 * v34)] + k92);
						const c167 = src2[((i429 < 0) ? 0 : ((i429 >= src2.length) ? 0 : i429))];
						if (((((c166 >= 65) && (c166 <= 90)) ? (c166 + 32) : c166) < (((c167 >= 65) && (c167 <= 90)) ? (c167 + 32) : c167))) {
							r120 = -1;
							break;
						}
						r120 = 1;
						break;
					}
					if (((k90 === 0) || (!(r120 === 0)))) {
						const i430 = ord9[((k90 < 0) ? 0 : ((k90 >= nw8) ? 0 : k90))];
						dt23[(2 * ((d182 < 0) ? 0 : ((d182 >= nd8) ? 0 : d182)))] = ((i430 < 0) ? 0 : ((i430 >= nw8) ? 0 : i430));
						dt23[((2 * ((d182 < 0) ? 0 : ((d182 >= nd8) ? 0 : d182))) + 1)] = 1;
						k90 = (k90 + 1);
						d182 = (d182 + 1);
						continue;
					}
					const i431 = (d182 - 1);
					const s8 = ((i431 < 0) ? 0 : ((i431 >= nd8) ? 0 : i431));
					const i432 = dt23[((2 * s8) + 1)];
					dt23[((2 * s8) + 1)] = (((i432 < 0) ? 0 : ((i432 >= 32769) ? 0 : i432)) + 1);
					k90 = (k90 + 1);
					continue;
				}
				const dt24 = dt23;
				const a46 = new Array(nd8).fill(0);
				const b91 = new Array(nd8).fill(0);
				let a47 = a46;
				let k93 = 0;
				for (;; k93 = (k93 + 1)) {
					if ((k93 >= nd8)) {
						break;
					}
					a47[((k93 < 0) ? 0 : ((k93 >= nd8) ? 0 : k93))] = k93;
					continue;
				}
				let a48 = a47;
				let b92 = b91;
				let w52 = 1;
				for (;; w52 = (2 * w52)) {
					if ((w52 >= nd8)) {
						break;
					}
					if ((w52 >= 32768)) {
						break;
					}
					let b93 = b92;
					let lo16 = 0;
					for (;;) {
						if ((lo16 >= nd8)) {
							break;
						}
						const b94 = (lo16 + w52);
						const mid16 = ((nd8 < b94) ? nd8 : b94);
						const b95 = (lo16 + (2 * w52));
						const hi16 = ((nd8 < b95) ? nd8 : b95);
						let b96 = b93;
						let i433 = lo16;
						let j32 = mid16;
						let k94 = lo16;
						for (;; k94 = (k94 + 1)) {
							if ((k94 >= hi16)) {
								break;
							}
							if ((i433 >= mid16)) {
								b96[((k94 < 0) ? 0 : ((k94 >= nd8) ? 0 : k94))] = a48[((j32 < 0) ? 0 : ((j32 >= nd8) ? 0 : j32))];
								j32 = (j32 + 1);
								continue;
							}
							if ((j32 >= hi16)) {
								b96[((k94 < 0) ? 0 : ((k94 >= nd8) ? 0 : k94))] = a48[((i433 < 0) ? 0 : ((i433 >= nd8) ? 0 : i433))];
								i433 = (i433 + 1);
								continue;
							}
							const i434 = a48[((j32 < 0) ? 0 : ((j32 >= nd8) ? 0 : j32))];
							const i435 = dt24[((2 * ((i434 < 0) ? 0 : ((i434 >= nd8) ? 0 : i434))) + 1)];
							const i436 = a48[((i433 < 0) ? 0 : ((i433 >= nd8) ? 0 : i433))];
							const i437 = dt24[((2 * ((i436 < 0) ? 0 : ((i436 >= nd8) ? 0 : i436))) + 1)];
							if ((((i435 < 0) ? 0 : ((i435 >= 32769) ? 0 : i435)) > ((i437 < 0) ? 0 : ((i437 >= 32769) ? 0 : i437)))) {
								b96[((k94 < 0) ? 0 : ((k94 >= nd8) ? 0 : k94))] = a48[((j32 < 0) ? 0 : ((j32 >= nd8) ? 0 : j32))];
								j32 = (j32 + 1);
								continue;
							}
							b96[((k94 < 0) ? 0 : ((k94 >= nd8) ? 0 : k94))] = a48[((i433 < 0) ? 0 : ((i433 >= nd8) ? 0 : i433))];
							i433 = (i433 + 1);
							continue;
						}
						const u121 = b96;
						const u122 = hi16;
						b93 = u121;
						lo16 = u122;
						continue;
					}
					const u123 = b93;
					const u124 = a48;
					a48 = u123;
					b92 = u124;
					continue;
				}
				const ord28 = a48;
				let n24 = 0;
				let r19 = 0;
				for (;; r19 = (r19 + 1)) {
					if ((r19 >= nd8)) {
						break;
					}
					if ((r19 >= 20)) {
						break;
					}
					if ((((Math.trunc(sp24.length / 2) + 0)) < 1)) {
						break;
					}
					const i438 = ord28[((r19 < 0) ? 0 : ((r19 >= nd8) ? 0 : r19))];
					const d189 = ((i438 < 0) ? 0 : ((i438 >= nd8) ? 0 : i438));
					const i439 = dt24[((2 * d189) + 1)];
					let d190 = 1;
					let x50 = ((i439 < 0) ? 0 : ((i439 >= 32769) ? 0 : i439));
					for (;; d190 = (d190 + 1), x50 = ((Math.trunc(x50 / 10) + 0))) {
						if ((x50 < 10)) {
							break;
						}
						if ((d190 >= 8)) {
							break;
						}
						continue;
					}
					const i440 = dt24[(2 * d189)];
					const i441 = ((i440 < 0) ? 0 : ((i440 >= 32769) ? 0 : i440));
					const w53 = ((i441 < 0) ? 0 : ((i441 >= ((Math.trunc(sp24.length / 2) + 0))) ? 0 : i441));
					const d191 = (sp24[((2 * w53) + 1)] - sp24[(2 * w53)]);
					n24 = (n24 + (d190 + (2 + ((d191 < 0) ? 0 : ((d191 >= 65536) ? 0 : d191)))));
					continue;
				}
				const m8 = n24;
				const out36 = new Array(m8).fill(0);
				let out37 = out36;
				let o22 = 0;
				let r20 = 0;
				for (;; r20 = (r20 + 1)) {
					if ((r20 >= nd8)) {
						break;
					}
					if ((r20 >= 20)) {
						break;
					}
					if ((((Math.trunc(sp24.length / 2) + 0)) < 1)) {
						break;
					}
					const i442 = ord28[((r20 < 0) ? 0 : ((r20 >= nd8) ? 0 : r20))];
					const d192 = ((i442 < 0) ? 0 : ((i442 >= nd8) ? 0 : i442));
					const i443 = dt24[((2 * d192) + 1)];
					const c168 = ((i443 < 0) ? 0 : ((i443 >= 32769) ? 0 : i443));
					const i444 = dt24[(2 * d192)];
					const i445 = ((i444 < 0) ? 0 : ((i444 >= 32769) ? 0 : i444));
					const w54 = ((i445 < 0) ? 0 : ((i445 >= ((Math.trunc(sp24.length / 2) + 0))) ? 0 : i445));
					let p15 = 1;
					let k95 = 1;
					for (;;) {
						let d193 = 1;
						let x51 = c168;
						for (;; d193 = (d193 + 1), x51 = ((Math.trunc(x51 / 10) + 0))) {
							if ((x51 < 10)) {
								break;
							}
							if ((d193 >= 8)) {
								break;
							}
							continue;
						}
						if ((k95 >= d193)) {
							break;
						}
						if ((k95 >= 8)) {
							break;
						}
						if ((p15 >= 100000000)) {
							break;
						}
						p15 = (p15 * 10);
						k95 = (k95 + 1);
						continue;
					}
					let out38 = out37;
					let o23 = o22;
					let p16 = p15;
					let x52 = c168;
					for (;; p16 = ((Math.trunc(p16 / 10) + 0))) {
						if ((p16 < 1)) {
							break;
						}
						out38[((o23 < 0) ? 0 : ((o23 >= m8) ? 0 : o23))] = (48 + (((((Math.trunc(x52 / p16) + 0)) % 10) + 0)));
						const i446 = (o23 + 1);
						o23 = ((i446 < 0) ? 0 : ((i446 >= m8) ? 0 : i446));
						continue;
					}
					let d194 = 1;
					let x53 = c168;
					for (;; d194 = (d194 + 1), x53 = ((Math.trunc(x53 / 10) + 0))) {
						if ((x53 < 10)) {
							break;
						}
						if ((d194 >= 8)) {
							break;
						}
						continue;
					}
					const i447 = (o22 + d194);
					out38[((i447 < 0) ? 0 : ((i447 >= m8) ? 0 : i447))] = 32;
					const out39 = out38;
					let d195 = 1;
					let x54 = c168;
					for (;; d195 = (d195 + 1), x54 = ((Math.trunc(x54 / 10) + 0))) {
						if ((x54 < 10)) {
							break;
						}
						if ((d195 >= 8)) {
							break;
						}
						continue;
					}
					let out40 = out39;
					let o24 = (o22 + (d195 + 1));
					let k96 = 0;
					for (;; k96 = (k96 + 1)) {
						const d196 = (sp24[((2 * w54) + 1)] - sp24[(2 * w54)]);
						if ((k96 >= ((d196 < 0) ? 0 : ((d196 >= 65536) ? 0 : d196)))) {
							break;
						}
						const i448 = (sp24[(2 * w54)] + k96);
						out40[((o24 < 0) ? 0 : ((o24 >= m8) ? 0 : o24))] = src2[((i448 < 0) ? 0 : ((i448 >= src2.length) ? 0 : i448))];
						const i449 = (o24 + 1);
						o24 = ((i449 < 0) ? 0 : ((i449 >= m8) ? 0 : i449));
						continue;
					}
					const i450 = dt24[((2 * d192) + 1)];
					let d197 = 1;
					let x55 = ((i450 < 0) ? 0 : ((i450 >= 32769) ? 0 : i450));
					for (;; d197 = (d197 + 1), x55 = ((Math.trunc(x55 / 10) + 0))) {
						if ((x55 < 10)) {
							break;
						}
						if ((d197 >= 8)) {
							break;
						}
						continue;
					}
					const i451 = dt24[(2 * d192)];
					const i452 = ((i451 < 0) ? 0 : ((i451 >= 32769) ? 0 : i451));
					const w55 = ((i452 < 0) ? 0 : ((i452 >= ((Math.trunc(sp24.length / 2) + 0))) ? 0 : i452));
					const d198 = (sp24[((2 * w55) + 1)] - sp24[(2 * w55)]);
					const i453 = (o22 + ((d197 + (2 + ((d198 < 0) ? 0 : ((d198 >= 65536) ? 0 : d198)))) - 1));
					out40[((i453 < 0) ? 0 : ((i453 >= m8) ? 0 : i453))] = 10;
					const i454 = dt24[((2 * d192) + 1)];
					let d199 = 1;
					let x56 = ((i454 < 0) ? 0 : ((i454 >= 32769) ? 0 : i454));
					for (;; d199 = (d199 + 1), x56 = ((Math.trunc(x56 / 10) + 0))) {
						if ((x56 < 10)) {
							break;
						}
						if ((d199 >= 8)) {
							break;
						}
						continue;
					}
					const i455 = dt24[(2 * d192)];
					const i456 = ((i455 < 0) ? 0 : ((i455 >= 32769) ? 0 : i455));
					const w56 = ((i456 < 0) ? 0 : ((i456 >= ((Math.trunc(sp24.length / 2) + 0))) ? 0 : i456));
					const d200 = (sp24[((2 * w56) + 1)] - sp24[(2 * w56)]);
					const u125 = out40;
					const u126 = (o22 + (d199 + (2 + ((d200 < 0) ? 0 : ((d200 >= 65536) ? 0 : d200)))));
					out37 = u125;
					o22 = u126;
					continue;
				}
				const v127 = (new TextDecoder().decode(Uint8Array.from(out37)));
				process.stdout.write(v127);
				t112 = v127;
			}
			t96 = t112;
		} else {
			console.log("freq: cannot read that file");
			t96 = "freq: cannot read that file";
		}
		t64 = t96;
	}
	return t64;
}

