// Code generated by oroboros. DO NOT EDIT.

package gauntlet

func GenDigitSum(n int) int {
	var m int = n
	var s int = 0
	for ; ; m = (m / 10) {
		if (m <= 0) {
			break
		}
		s = (s + (m % 10))
		continue
	}
	return s
}

