// Code generated by oroboros. DO NOT EDIT.

package gauntlet

func GenDot(a []float64, b []float64) float64 {
	acc := 0.0
	var i int = 0
	var n1 int = (len(a))
	s2 := b[:n1]
	for ; ; i = (i + 1) {
		if (i >= (len(a))) {
			break
		}
		acc = (acc + ((a[i]) * (s2[i])))
		continue
	}
	return acc
}

