// Code generated by oroboros. DO NOT EDIT.

export function genMacFresh(a, b) {
	const w = new Array(65536).fill(0);
	let w2 = w;
	let i = 0;
	for (;; i = (i + 1)) {
		if ((i >= 65536)) {
			break;
		}
		w2[i] = (a[i] * b[i]);
		continue;
	}
	return w2;
}

export function genMacInto(w, a, b) {
	let w2 = w;
	let i = 0;
	for (;; i = (i + 1)) {
		if ((i >= 65536)) {
			return w2;
		}
		w2[i] = (a[i] * b[i]);
		continue;
	}
}

