// Code generated by oroboros. DO NOT EDIT.

export function genMain() {
	const c = (new Array(20000).fill(false));
	let i = 2;
	for (;;) {
		if (((i * i) >= 20000)) {
			break;
		}
		if ((c[i])) {
			i = (i + 1);
			continue;
		}
		let j = (i * i);
		for (;; j = (j + i)) {
			if ((j < 20000)) {
				c[j] = true;
				continue;
			}
			break;
		}
		c;
		i = (i + 1);
		continue;
	}
	let acc = 0;
	let k = 2;
	for (;; k = (k + 1)) {
		if ((k >= 20000)) {
			break;
		}
		if ((c[k])) {
			continue;
		}
		acc = (acc + 1);
		continue;
	}
	const v1 = ("primes: ".concat((String(acc))));
	console.log(v1);
	return v1;
}

export function genSieveCount(n) {
	const c = (new Array(n).fill(false));
	let i = 2;
	for (;;) {
		if (((i * i) >= n)) {
			break;
		}
		if ((c[i])) {
			i = (i + 1);
			continue;
		}
		let j = (i * i);
		for (;; j = (j + i)) {
			if ((j < n)) {
				c[j] = true;
				continue;
			}
			break;
		}
		c;
		i = (i + 1);
		continue;
	}
	let acc = 0;
	let k = 2;
	for (;; k = (k + 1)) {
		if ((k >= n)) {
			return acc;
		}
		if ((c[k])) {
			continue;
		}
		acc = (acc + 1);
		continue;
	}
}

