// Code generated by oroboros. DO NOT EDIT.

public final class examples_native_sieve-java.java {
	public static long genSieveCount(long n) {
		final boolean[] c = (new boolean[(int) n]);
		int i = 2;
		for (;;) {
			if (((i * i) >= n)) {
				break;
			}
			if ((c[(int) i])) {
				i = (int) ((i + 1));
				continue;
			}
			int j = (i * i);
			for (;; j = (j + i)) {
				if ((j < n)) {
					c[(int) j] = true;
					continue;
				}
				break;
			}
			i = (int) ((i + 1));
			continue;
		}
		int acc = 0;
		int k = 2;
		for (;; k = (k + 1)) {
			if ((k >= n)) {
				break;
			}
			if ((c[(int) k])) {
				continue;
			}
			acc = (int) ((acc + 1));
			continue;
		}
		return acc;
	}

}
