// Code generated by oroboros. DO NOT EDIT.

public final class examples_native_divmod-java.java {
	public record Tup_long_long(long f0, long f1) {}

	public static Tup_long_long genDivmod(long a, long b) {
		return new Tup_long_long((a / b), (a % b));
	}

	public static long genDivmodSum(long a, long b) {
		return ((a / b) + (a % b));
	}

}
