// Code generated by oroboros. DO NOT EDIT.

export function genMain() {
	const av = (process.argv.slice(1));
	let t196;
	if ((av.length < 2)) {
		console.log("usage: jsonfmt FILE");
		t196 = "usage: jsonfmt FILE";
	} else {
		let src2, err2;
		try { src2 = fs.readFileSync(av[1]); err2 = null; } catch (e) { src2 = null; err2 = e; }
		let t294;
		if ((err2 === null)) {
			let t343;
			if ((src2.length >= 65536)) {
				console.log("jsonfmt: file is larger than this tool accepts");
				t343 = "jsonfmt: file is larger than this tool accepts";
			} else {
				let n8 = 0;
				let i15 = 0;
				let d23 = 0;
				let fresh15 = 0;
				let r344;
				for (;;) {
					if ((i15 >= src2.length)) {
						r344 = (n8 + 1);
						break;
					}
					if ((d23 >= 64)) {
						r344 = (n8 + 1);
						break;
					}
					const c211 = src2[i15];
					if (((c211 === 32) || ((c211 === 9) || ((c211 === 10) || (c211 === 13))))) {
						i15 = (i15 + 1);
						continue;
					}
					const c212 = src2[i15];
					if (((c212 === 123) || (c212 === 91))) {
						const u345 = (n8 + (((fresh15 === 1) ? (1 + (2 * d23)) : 0) + 1));
						const u346 = (i15 + 1);
						const u347 = (d23 + 1);
						const u348 = 1;
						n8 = u345;
						i15 = u346;
						d23 = u347;
						fresh15 = u348;
						continue;
					}
					const c213 = src2[i15];
					if (((c213 === 125) || (c213 === 93))) {
						const d115 = ((d23 < 1) ? 0 : (d23 - 1));
						const u349 = (n8 + (((fresh15 === 0) ? (1 + (2 * d115)) : 0) + 1));
						const u350 = (i15 + 1);
						const u351 = d115;
						const u352 = 0;
						n8 = u349;
						i15 = u350;
						d23 = u351;
						fresh15 = u352;
						continue;
					}
					if ((src2[i15] === 44)) {
						n8 = (n8 + (2 + (2 * d23)));
						i15 = (i15 + 1);
						fresh15 = 0;
						continue;
					}
					if ((src2[i15] === 58)) {
						n8 = (n8 + 2);
						i15 = (i15 + 1);
						continue;
					}
					const c214 = src2[i15];
					if (((c214 === 34) || ((((c214 >= 48) && (c214 <= 57)) || ((c214 === 45) || ((c214 === 43) || ((c214 === 46) || ((c214 === 101) || (c214 === 69)))))) || ((c214 >= 97) && (c214 <= 122))))) {
						let t355;
						if ((src2[i15] === 34)) {
							let j146 = (i15 + 1);
							let r356;
							for (;;) {
								if ((j146 < 0)) {
									r356 = j146;
									break;
								}
								if ((j146 >= src2.length)) {
									r356 = j146;
									break;
								}
								if (((src2[j146] === 92) && ((j146 + 1) >= src2.length))) {
									r356 = (j146 + 1);
									break;
								}
								if ((src2[j146] === 92)) {
									j146 = (j146 + 2);
									continue;
								}
								if ((src2[j146] === 34)) {
									r356 = (j146 + 1);
									break;
								}
								j146 = (j146 + 1);
								continue;
							}
							t355 = r356;
						} else {
							const c220 = src2[i15];
							let t357;
							if ((((c220 >= 48) && (c220 <= 57)) || ((c220 === 45) || ((c220 === 43) || ((c220 === 46) || ((c220 === 101) || (c220 === 69))))))) {
								let j149 = (i15 + 1);
								for (;; j149 = (j149 + 1)) {
									if ((j149 < 0)) {
										break;
									}
									if ((j149 >= src2.length)) {
										break;
									}
									const c223 = src2[j149];
									if ((((c223 >= 48) && (c223 <= 57)) || ((c223 === 45) || ((c223 === 43) || ((c223 === 46) || ((c223 === 101) || (c223 === 69))))))) {
										continue;
									}
									break;
								}
								t357 = j149;
							} else {
								let j150 = (i15 + 1);
								for (;; j150 = (j150 + 1)) {
									if ((j150 < 0)) {
										break;
									}
									if ((j150 >= src2.length)) {
										break;
									}
									const c224 = src2[j150];
									if (((c224 >= 97) && (c224 <= 122))) {
										continue;
									}
									break;
								}
								t357 = j150;
							}
							t355 = t357;
						}
						const ni15 = t355;
						const u358 = (n8 + (((fresh15 === 1) ? (1 + (2 * d23)) : 0) + (ni15 - i15)));
						const u359 = ni15;
						const u360 = 0;
						n8 = u358;
						i15 = u359;
						fresh15 = u360;
						continue;
					}
					i15 = (i15 + 1);
					continue;
				}
				const out155 = new Array(r344).fill(0);
				let out156 = out155;
				let op15 = 0;
				let i16 = 0;
				let d24 = 0;
				let fresh16 = 0;
				let r361;
				for (;;) {
					if ((i16 >= src2.length)) {
						out156[op15] = 10;
						r361 = out156;
						break;
					}
					if ((d24 >= 64)) {
						out156[op15] = 10;
						r361 = out156;
						break;
					}
					const c225 = src2[i16];
					if (((c225 === 32) || ((c225 === 9) || ((c225 === 10) || (c225 === 13))))) {
						i16 = (i16 + 1);
						continue;
					}
					const c226 = src2[i16];
					if (((c226 === 123) || (c226 === 91))) {
						const p22 = ((fresh16 === 1) ? (1 + (2 * d24)) : 0);
						let t362;
						if ((fresh16 === 1)) {
							out156[op15] = 10;
							const out159 = out156;
							let out160 = out159;
							let k58 = 0;
							let o58 = (op15 + 1);
							for (;; k58 = (k58 + 1), o58 = (o58 + 1)) {
								if ((k58 >= (2 * d24))) {
									break;
								}
								out160[o58] = 32;
								continue;
							}
							t362 = out160;
						} else {
							t362 = out156;
						}
						const out161 = t362;
						const c227 = ((src2[i16] === 123) ? 123 : 91);
						out161[(op15 + p22)] = c227;
						const u363 = out161;
						const u364 = (op15 + (p22 + 1));
						const u365 = (i16 + 1);
						const u366 = (d24 + 1);
						const u367 = 1;
						out156 = u363;
						op15 = u364;
						i16 = u365;
						d24 = u366;
						fresh16 = u367;
						continue;
					}
					const c228 = src2[i16];
					if (((c228 === 125) || (c228 === 93))) {
						const d116 = ((d24 < 1) ? 0 : (d24 - 1));
						const p23 = ((fresh16 === 0) ? (1 + (2 * d116)) : 0);
						let t368;
						if ((fresh16 === 0)) {
							out156[op15] = 10;
							const out164 = out156;
							let out165 = out164;
							let k60 = 0;
							let o60 = (op15 + 1);
							for (;; k60 = (k60 + 1), o60 = (o60 + 1)) {
								if ((k60 >= (2 * d116))) {
									break;
								}
								out165[o60] = 32;
								continue;
							}
							t368 = out165;
						} else {
							t368 = out156;
						}
						const out166 = t368;
						const c229 = ((src2[i16] === 125) ? 125 : 93);
						out166[(op15 + p23)] = c229;
						const u369 = out166;
						const u370 = (op15 + (p23 + 1));
						const u371 = (i16 + 1);
						const u372 = d116;
						const u373 = 0;
						out156 = u369;
						op15 = u370;
						i16 = u371;
						d24 = u372;
						fresh16 = u373;
						continue;
					}
					if ((src2[i16] === 44)) {
						out156[op15] = 44;
						const out167 = out156;
						const op16 = (op15 + 1);
						out167[op16] = 10;
						const out168 = out167;
						let out169 = out168;
						let k61 = 0;
						let o61 = (op16 + 1);
						for (;; k61 = (k61 + 1), o61 = (o61 + 1)) {
							if ((k61 >= (2 * d24))) {
								break;
							}
							out169[o61] = 32;
							continue;
						}
						const u374 = out169;
						const u375 = (op15 + (2 + (2 * d24)));
						const u376 = (i16 + 1);
						const u377 = 0;
						out156 = u374;
						op15 = u375;
						i16 = u376;
						fresh16 = u377;
						continue;
					}
					if ((src2[i16] === 58)) {
						out156[op15] = 58;
						const out170 = out156;
						out170[(op15 + 1)] = 32;
						const u378 = out170;
						const u379 = (op15 + 2);
						const u380 = (i16 + 1);
						out156 = u378;
						op15 = u379;
						i16 = u380;
						continue;
					}
					const c230 = src2[i16];
					if (((c230 === 34) || ((((c230 >= 48) && (c230 <= 57)) || ((c230 === 45) || ((c230 === 43) || ((c230 === 46) || ((c230 === 101) || (c230 === 69)))))) || ((c230 >= 97) && (c230 <= 122))))) {
						let t383;
						if ((src2[i16] === 34)) {
							let j156 = (i16 + 1);
							let r384;
							for (;;) {
								if ((j156 < 0)) {
									r384 = j156;
									break;
								}
								if ((j156 >= src2.length)) {
									r384 = j156;
									break;
								}
								if (((src2[j156] === 92) && ((j156 + 1) >= src2.length))) {
									r384 = (j156 + 1);
									break;
								}
								if ((src2[j156] === 92)) {
									j156 = (j156 + 2);
									continue;
								}
								if ((src2[j156] === 34)) {
									r384 = (j156 + 1);
									break;
								}
								j156 = (j156 + 1);
								continue;
							}
							t383 = r384;
						} else {
							const c236 = src2[i16];
							let t385;
							if ((((c236 >= 48) && (c236 <= 57)) || ((c236 === 45) || ((c236 === 43) || ((c236 === 46) || ((c236 === 101) || (c236 === 69))))))) {
								let j159 = (i16 + 1);
								for (;; j159 = (j159 + 1)) {
									if ((j159 < 0)) {
										break;
									}
									if ((j159 >= src2.length)) {
										break;
									}
									const c239 = src2[j159];
									if ((((c239 >= 48) && (c239 <= 57)) || ((c239 === 45) || ((c239 === 43) || ((c239 === 46) || ((c239 === 101) || (c239 === 69))))))) {
										continue;
									}
									break;
								}
								t385 = j159;
							} else {
								let j160 = (i16 + 1);
								for (;; j160 = (j160 + 1)) {
									if ((j160 < 0)) {
										break;
									}
									if ((j160 >= src2.length)) {
										break;
									}
									const c240 = src2[j160];
									if (((c240 >= 97) && (c240 <= 122))) {
										continue;
									}
									break;
								}
								t385 = j160;
							}
							t383 = t385;
						}
						const ni16 = t383;
						const p24 = ((fresh16 === 1) ? (1 + (2 * d24)) : 0);
						let t386;
						if ((fresh16 === 1)) {
							out156[op15] = 10;
							const out173 = out156;
							let out174 = out173;
							let k63 = 0;
							let o63 = (op15 + 1);
							for (;; k63 = (k63 + 1), o63 = (o63 + 1)) {
								if ((k63 >= (2 * d24))) {
									break;
								}
								out174[o63] = 32;
								continue;
							}
							t386 = out174;
						} else {
							t386 = out156;
						}
						const out175 = t386;
						let out176 = out175;
						let k64 = i16;
						let o64 = (op15 + p24);
						for (;; k64 = (k64 + 1), o64 = (o64 + 1)) {
							if ((k64 >= ni16)) {
								break;
							}
							if ((k64 >= src2.length)) {
								break;
							}
							out176[o64] = src2[k64];
							continue;
						}
						const u387 = out176;
						const u388 = (op15 + (p24 + (ni16 - i16)));
						const u389 = ni16;
						const u390 = 0;
						out156 = u387;
						op15 = u388;
						i16 = u389;
						fresh16 = u390;
						continue;
					}
					i16 = (i16 + 1);
					continue;
				}
				const v391 = (new TextDecoder().decode(Uint8Array.from(r361)));
				process.stdout.write(v391);
				t343 = v391;
			}
			t294 = t343;
		} else {
			console.log("jsonfmt: cannot read that file");
			t294 = "jsonfmt: cannot read that file";
		}
		t196 = t294;
	}
	return t196;
}

