; Code generated by oroboros. DO NOT EDIT.

option casemap:none

extern GetStdHandle: proc
extern VirtualAlloc: proc
extern WriteFile: proc

.data
__written qword 0
__buf     db 256 dup(0)
LS24 db 030h,0
LS24_len equ 1
LS28 db 00Ah,0
LS28_len equ 1

.code
gen_main proc
        push rbx
        push rsi
        push rdi
        push r12
        push r13
        push r14
        push r15
        sub rsp, 64
        mov rbx, 0
        mov rsi, 0
Ltop1:
        cmp rsi, 100
        jge Ldone1
Lnext2:
        mov rdi, 200000
        mov r12, rdi
        add r12, 8
        xor ecx, ecx
        mov rdx, r12
        mov r8, 3000h
        mov r9, 4
        call VirtualAlloc
        mov r13, rax
        mov qword ptr [r13], rdi
        mov rdi, r13
        mov r12, 2
Ltop4:
        mov r14, r12
        imul r14, r12
        cmp r14, 200000
        jge Ldone4
Lnext5:
        movzx r14d, byte ptr [rdi+r12+8]
        cmp r14, 0
        je Lnext7
        add r12, 1
        jmp Ltop4
Lnext7:
        mov r14, r12
        imul r14, r12
        mov r15, r14
Ltop10:
        cmp r15, 200000
        jge Lnext11
        mov byte ptr [rdi+r15+8], 1
        add r15, r12
        jmp Ltop10
Lnext11:
Ldone10:
        add r12, 1
        jmp Ltop4
Ldone4:
        mov r12, 0
        mov r15, 2
Ltop14:
        cmp r15, 200000
        jge Ldone14
Lnext15:
        movzx r14d, byte ptr [rdi+r15+8]
        cmp r14, 0
        je Lnext16
        add r15, 1
        jmp Ltop14
Lnext16:
        add r12, 1
        add r15, 1
        jmp Ltop14
Ldone14:
        mov rdi, rbx
        add rdi, r12
        mov rbx, rdi
        add rsi, 1
        jmp Ltop1
Ldone1:
        cmp rbx, 0
        jne Lelse22
        mov rcx, -11
        call GetStdHandle
        mov rdi, rax
        lea r12, LS24
        lea r15, LS24
        mov rax, r15
        Lstr25:
        cmp byte ptr [rax], 0
        je Lstrend25
        inc rax
        jmp Lstr25
        Lstrend25:
        sub rax, r15
        mov r14, rax
        mov rcx, rdi
        mov rdx, r12
        mov r8, r14
        lea r9, __written
        mov qword ptr [rsp+32], 0
        call WriteFile
        mov rcx, -11
        call GetStdHandle
        mov rdi, rax
        lea r14, LS28
        mov rcx, rdi
        mov rdx, r14
        mov r8, 1
        lea r9, __written
        mov qword ptr [rsp+32], 0
        call WriteFile
        mov rsi, rdi
        jmp Lend22
Lelse22:
        lea rdi, __buf
        mov byte ptr [rdi+24], 10
        mov r14, rbx
        mov r12, 24
Ltop32:
        cmp r14, 0
        jle Lnext33
        mov r15, r12
        sub r15, 1
        mov rax, r14
        cqo
        mov rcx, 10
        idiv rcx
        mov rax, rdx
        mov qword ptr [rsp+48], rax
        mov r10, qword ptr [rsp+48]
        mov rax, 48
        add rax, r10
        mov qword ptr [rsp+56], rax
        mov r10, qword ptr [rsp+56]
        mov byte ptr [rdi+r15], r10b
        mov rax, r14
        cqo
        mov rcx, 10
        idiv rcx
        mov r15, rax
        mov r14, r15
        sub r12, 1
        jmp Ltop32
Lnext33:
Ldone32:
        mov rcx, -11
        call GetStdHandle
        mov r14, rax
        lea r15, [rdi+r12]
        mov rax, 24
        sub rax, r12
        mov qword ptr [rsp+56], rax
        mov r10, qword ptr [rsp+56]
        mov rax, r10
        add rax, 1
        mov qword ptr [rsp+48], rax
        mov r10, qword ptr [rsp+48]
        mov rcx, r14
        mov rdx, r15
        mov r8, r10
        lea r9, __written
        mov qword ptr [rsp+32], 0
        call WriteFile
        mov rsi, r14
Lend22:
        mov rax, rsi
        add rsp, 64
        pop r15
        pop r14
        pop r13
        pop r12
        pop rdi
        pop rsi
        pop rbx
        ret
gen_main endp


end
