// Code generated by oroboros. DO NOT EDIT.

package gauntlet

func GenCentroid(xs []float64, ys []float64) float64 {
	ax := 0.0
	ay := 0.0
	var i int = 0
	var n1 int = (len(xs))
	s2 := ys[:n1]
	var r3 float64
	for ; ; i = (i + 1) {
		if (i >= (len(xs))) {
			r3 = (ax + ay)
			break
		}
		ax, ay = (ax + (xs[i])), (ay + (s2[i]))
		continue
	}
	return r3
}

