; Code generated by oroboros. DO NOT EDIT.

option casemap:none

extern VirtualAlloc: proc

.data

.code
gen_limb proc
        push rbx
        push rsi
        push rdi
        push r12
        push r13
        push r14
        push r15
        sub rsp, 80
        mov rbx, rcx
        mov rsi, 64
        mov rdi, rsi
        add rdi, 1
        shl rdi, 3
        xor ecx, ecx
        mov rdx, rdi
        mov r8, 3000h
        mov r9, 4
        call VirtualAlloc
        mov r12, rax
        mov qword ptr [r12], rsi
        mov rsi, 0
        mov rdi, 1
Ltop2:
        cmp rsi, 64
        jge Ldone2
Lnext3:
        mov r13, rdi
        and r13, 16777215
        mov qword ptr [r12+rsi*8+8], r13
        add rsi, 1
        mov rcx, 24
        shr rdi, cl
        jmp Ltop2
Ldone2:
        mov rdi, r12
        mov rsi, 2
        mov r13, 64
        mov r14, r13
        add r14, 1
        shl r14, 3
        xor ecx, ecx
        mov rdx, r14
        mov r8, 3000h
        mov r9, 4
        call VirtualAlloc
        mov r15, rax
        mov qword ptr [r15], r13
Ltop8:
        cmp rsi, 200
        jg Ldone8
Lnext9:
        mov r13, rdi
        mov r14, 64
        xor r14, r14
        Lzc10:
        cmp r14, 64
        jge Lzd10
        mov qword ptr [r15+r14*8+8], 0
        inc r14
        jmp Lzc10
        Lzd10:
        mov r14, 0
        mov qword ptr [rsp+48], 0
Ltop11:
        cmp r14, 64
        jge Ldone11
Lnext12:
        cmp r14, 0
        jge Lelse13
        mov qword ptr [rsp+56], 0
        jmp Lend13
Lelse13:
        mov r10, qword ptr [rdi]
        mov qword ptr [rsp+64], r10
        mov r11, qword ptr [rsp+64]
        cmp r14, r11
        jl Lelse14
        mov qword ptr [rsp+64], 0
        jmp Lend14
Lelse14:
        mov r10, qword ptr [rdi+r14*8+8]
        mov qword ptr [rsp+72], r10
        mov r10, qword ptr [rsp+72]
        mov qword ptr [rsp+64], r10
Lend14:
        mov r10, qword ptr [rsp+64]
        mov qword ptr [rsp+56], r10
Lend13:
        mov r10, qword ptr [rsp+56]
        mov rax, r10
        imul rax, rsi
        mov qword ptr [rsp+64], rax
        mov r10, qword ptr [rsp+64]
        mov r11, qword ptr [rsp+48]
        mov rax, r10
        add rax, r11
        mov qword ptr [rsp+56], rax
        mov r10, qword ptr [rsp+56]
        mov rax, r10
        cqo
        mov rcx, 16777216
        idiv rcx
        mov rax, rdx
        mov qword ptr [rsp+64], rax
        mov r10, qword ptr [rsp+64]
        mov qword ptr [r15+r14*8+8], r10
        add r14, 1
        mov r10, qword ptr [rsp+56]
        mov rax, r10
        cqo
        mov rcx, 16777216
        idiv rcx
        mov rax, rax
        mov qword ptr [rsp+64], rax
        mov r10, qword ptr [rsp+64]
        mov qword ptr [rsp+48], r10
        jmp Ltop11
Ldone11:
        mov rdi, r15
        add rsi, 1
        mov r15, r13
        jmp Ltop8
Ldone8:
        cmp rbx, 0
        jge Lelse21
        mov rsi, 0
        jmp Lend21
Lelse21:
        mov r13, qword ptr [rdi]
        cmp rbx, r13
        jl Lelse22
        mov r13, 0
        jmp Lend22
Lelse22:
        mov r14, qword ptr [rdi+rbx*8+8]
        mov r13, r14
Lend22:
        mov rsi, r13
Lend21:
        mov rax, rsi
        add rsp, 80
        pop r15
        pop r14
        pop r13
        pop r12
        pop rdi
        pop rsi
        pop rbx
        ret
gen_limb endp


end
