; Code generated by oroboros. DO NOT EDIT.

option casemap:none

extern GetStdHandle: proc
extern VirtualAlloc: proc
extern WriteFile: proc

.data
__written qword 0
__buf     db 256 dup(0)
LS43 db 030h,0
LS43_len equ 1
LS47 db 00Ah,0
LS47_len equ 1

.code
gen_count_primes proc
        push rbx
        push rsi
        push rdi
        push r12
        push r13
        sub rsp, 48
        mov rbx, rcx
        xor ecx, ecx
        mov rdx, rbx
        mov r8, 3000h
        mov r9, 4
        call VirtualAlloc
        mov rsi, rax
        mov rdi, 2
Ltop2:
        mov r12, rdi
        imul r12, rdi
        cmp r12, rbx
        jge Ldone2
Lnext3:
        cmp byte ptr [rsi+rdi], 0
        je Lnext5
        add rdi, 1
        jmp Ltop2
Lnext5:
        mov r12, rdi
        imul r12, rdi
        mov r13, r12
Ltop9:
        cmp r13, rbx
        jge Lnext10
        mov byte ptr [rsi+r13], 1
        add r13, rdi
        jmp Ltop9
Lnext10:
Ldone9:
        add rdi, 1
        jmp Ltop2
Ldone2:
        mov rdi, 0
        mov r13, 2
Ltop14:
        cmp r13, rbx
        jge Ldone14
Lnext15:
        cmp byte ptr [rsi+r13], 0
        je Lnext16
        add r13, 1
        jmp Ltop14
Lnext16:
        add rdi, 1
        add r13, 1
        jmp Ltop14
Ldone14:
        mov rax, rdi
        add rsp, 48
        pop r13
        pop r12
        pop rdi
        pop rsi
        pop rbx
        ret
gen_count_primes endp

gen_main proc
        push rbx
        push rsi
        push rdi
        push r12
        push r13
        push r14
        push r15
        sub rsp, 64
        xor ecx, ecx
        mov rdx, 20000
        mov r8, 3000h
        mov r9, 4
        call VirtualAlloc
        mov rbx, rax
        mov rsi, 2
Ltop22:
        mov rdi, rsi
        imul rdi, rsi
        cmp rdi, 20000
        jge Ldone22
Lnext23:
        cmp byte ptr [rbx+rsi], 0
        je Lnext25
        add rsi, 1
        jmp Ltop22
Lnext25:
        mov rdi, rsi
        imul rdi, rsi
        mov r12, rdi
Ltop29:
        cmp r12, 20000
        jge Lnext30
        mov byte ptr [rbx+r12], 1
        add r12, rsi
        jmp Ltop29
Lnext30:
Ldone29:
        add rsi, 1
        jmp Ltop22
Ldone22:
        mov rsi, 0
        mov r12, 2
Ltop34:
        cmp r12, 20000
        jge Ldone34
Lnext35:
        cmp byte ptr [rbx+r12], 0
        je Lnext36
        add r12, 1
        jmp Ltop34
Lnext36:
        add rsi, 1
        add r12, 1
        jmp Ltop34
Ldone34:
        cmp rsi, 0
        jne Lelse41
        mov rcx, -11
        call GetStdHandle
        mov r12, rax
        lea rdi, LS43
        lea r13, LS43
        mov rax, r13
        Lstr44:
        cmp byte ptr [rax], 0
        je Lstrend44
        inc rax
        jmp Lstr44
        Lstrend44:
        sub rax, r13
        mov r14, rax
        mov rcx, r12
        mov rdx, rdi
        mov r8, r14
        lea r9, __written
        mov qword ptr [rsp+32], 0
        call WriteFile
        mov rcx, -11
        call GetStdHandle
        mov r12, rax
        lea r14, LS47
        mov rcx, r12
        mov rdx, r14
        mov r8, 1
        lea r9, __written
        mov qword ptr [rsp+32], 0
        call WriteFile
        mov rbx, r12
        jmp Lend41
Lelse41:
        lea r12, __buf
        mov byte ptr [r12+24], 10
        mov r14, rsi
        mov rdi, 24
Ltop51:
        cmp r14, 0
        jle Lnext52
        mov r13, rdi
        sub r13, 1
        mov rax, r14
        cqo
        mov rcx, 10
        idiv rcx
        mov r15, rdx
        mov rax, 48
        add rax, r15
        mov qword ptr [rsp+48], rax
        mov r10, qword ptr [rsp+48]
        mov byte ptr [r12+r13], r10b
        mov rax, r14
        cqo
        mov rcx, 10
        idiv rcx
        mov r13, rax
        mov r14, r13
        sub rdi, 1
        jmp Ltop51
Lnext52:
Ldone51:
        mov rcx, -11
        call GetStdHandle
        mov r14, rax
        lea r13, [r12+rdi]
        mov r15, 24
        sub r15, rdi
        mov rax, r15
        add rax, 1
        mov qword ptr [rsp+48], rax
        mov r10, qword ptr [rsp+48]
        mov rcx, r14
        mov rdx, r13
        mov r8, r10
        lea r9, __written
        mov qword ptr [rsp+32], 0
        call WriteFile
        mov rbx, r14
Lend41:
        mov rax, rbx
        add rsp, 64
        pop r15
        pop r14
        pop r13
        pop r12
        pop rdi
        pop rsi
        pop rbx
        ret
gen_main endp


end
