// Code generated by oroboros. DO NOT EDIT.

package gauntlet

func GenLimb(k int) int {
	b := make([]int32, 64)
	b2 := b
	var i2 int = 0
	var r int = 1
	for ; ; i2, r = (i2 + 1), (r >> 24) {
		if (i2 >= 64) {
			break
		}
		b2[i2] = int32((r & 16777215))
		continue
	}
	acc := b2
	var i int = 2
	sp1 := make([]int32, 64)
	for ; ; i = (i + 1) {
		if (i > 200) {
			break
		}
		clear(sp1)
		o := sp1
		o3 := o
		var i1 int = 0
		var c int = 0
		for ; ; i1 = (i1 + 1) {
			if (i1 >= 64) {
				break
			}
			var t2 int
			if (i1 < 0) {
				t2 = 0
			} else {
				var t3 int
				if (i1 >= len(acc)) {
					t3 = 0
				} else {
					t3 = int(acc[i1])
				}
				t2 = t3
			}
			var t145 int = ((t2 * i) + c)
			o3[i1] = int32((t145 % 16777216))
			c = (t145 / 16777216)
			continue
		}
		acc, sp1 = o3, acc
		continue
	}
	t1452 := acc
	var t4 int
	if (k < 0) {
		t4 = 0
	} else {
		var t5 int
		if (k >= len(t1452)) {
			t5 = 0
		} else {
			t5 = int(t1452[k])
		}
		t4 = t5
	}
	return t4
}

