// Code generated by oroboros. DO NOT EDIT.

package gauntlet

func GenRun(n int) int {
	var m int = (func(a, b int) int { t := a - b; if (t < a) != (b > 0) { panic("int overflow") }; return t }(0, (func(a, b int) int { t := a + b; if (t > a) != (b > 0) { panic("int overflow") }; return t }(n, 1))))
	return (func(a, b int) int { t := a + b; if (t > a) != (b > 0) { panic("int overflow") }; return t }(1000000, (func(a, b int) int { t := a + b; if (t > a) != (b > 0) { panic("int overflow") }; return t }((func(a, b int) int { t := a + b; if (t > a) != (b > 0) { panic("int overflow") }; return t }((func(a, b int) int { t := a * b; if a != 0 && t/a != b { panic("int overflow") }; return t }((m / 2), 100)), (m % 8))), ((func(a, b int) int { t := a * b; if a != 0 && t/a != b { panic("int overflow") }; return t }(n, 300000000)) / 4)))))
}

