// Code generated by oroboros. DO NOT EDIT.

export function genRun(k) {
	const b = new Array(3).fill(0);
	let b22 = b;
	let i = 0;
	let r = 999999999999999;
	for (;; i = (i + 1), r = ((Math.trunc(r / 16777216) + 0))) {
		if ((i >= 3)) {
			break;
		}
		b22[i] = (((r % 16777216) + 0));
		continue;
	}
	const a = b22;
	const b2 = new Array(3).fill(0);
	let b4 = b2;
	let i2 = 0;
	let r2 = 14000000;
	for (;; i2 = (i2 + 1), r2 = (r2 >> 24)) {
		if ((i2 >= 3)) {
			break;
		}
		b4[i2] = (r2 & 16777215);
		continue;
	}
	const b42 = b4;
	const o = new Array(3).fill(0);
	let o2 = o;
	let i3 = 0;
	let bw = 0;
	for (;; i3 = (i3 + 1)) {
		if ((i3 >= 3)) {
			break;
		}
		const t1717 = ((((i3 < 0) ? 0 : ((i3 >= a.length) ? 0 : a[i3])) - ((i3 < 0) ? 0 : ((i3 >= b42.length) ? 0 : b42[i3]))) - bw);
		o2[i3] = ((t1717 < 0) ? (t1717 + 16777216) : t1717);
		bw = ((t1717 < 0) ? 1 : 0);
		continue;
	}
	const a2 = o2;
	const o3 = new Array(3).fill(0);
	let o4 = o3;
	let i4 = 2;
	let r3 = 0;
	for (;; i4 = (i4 - 1)) {
		if ((i4 < 0)) {
			break;
		}
		const cur1717 = ((r3 * 16777216) + ((i4 < 0) ? 0 : ((i4 >= a2.length) ? 0 : a2[i4])));
		o4[i4] = ((Math.trunc(cur1717 / 7) + 0));
		r3 = (((cur1717 % 7) + 0));
		continue;
	}
	const q = o4;
	const i5 = (k + 1);
	return (((k < 0) ? 0 : ((k >= q.length) ? 0 : q[k])) + (((i5 < 0) ? 0 : ((i5 >= q.length) ? 0 : q[i5])) * 100000000));
}

