// Code generated by oroboros. DO NOT EDIT.

export function genRun(n) {
	return (((String.fromCodePoint(65)) + (String.fromCodePoint(233))) + ((String.fromCodePoint(26085)) + (String.fromCodePoint(128578))));
}

